services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - DATABASE_URL=postgresql://grubb:Unrelated7-Nimbly0-Whoever6-Trembling6-Refocus0@db:5432/budgetapp
    command: flask run --host=0.0.0.0

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: grubb
      POSTGRES_PASSWORD: Unrelated7-Nimbly0-Whoever6-Trembling6-Refocus0
      POSTGRES_DB: budgetapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: