services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/budgetapp
  db:
    image: postgres:17                # Use the official PostgreSQL version 13 image
    restart: always                   # Always restart this container if it stops unexpectedly
    environment:                      # Set up the environment variables for the database
      POSTGRES_USER: grubb         # Database username
      POSTGRES_PASSWORD: Unrelated7-Nimbly0-Whoever6-Trembling6-Refocus0     # Database password
      POSTGRES_DB: budgetapp          # Name of the default database
    ports:
      - "5432:5432"                   # Map port 5432 in the container to port 5432 on your host
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data between container restarts

volumes:
  pgdata:                             # This defines a named volume called pgdata
