"""
Shekel Budget App -- Paycheck engine: the DEDUCTION lines of a paycheck.

Everything between a paycheck's gross and its taxable income, and everything
taken after tax: the per-paycheck :class:`_DeductionContext` both timing
passes share, the two passes themselves (:func:`_compute_deductions` over
:func:`_calculate_deductions`), a line's raw amount with its inflation
escalation (:func:`_raw_deduction_amount`, :func:`_inflation_years`), and a
capped line's own year-to-date (:func:`_cumulative_deduction_before`) -- the
fourth of the package docstring's calendar questions, kept beside the lines
it caps because it replays exactly what :func:`_raw_deduction_amount` applies
to the live one.

**Which paydays a line lands on is its RECURRENCE RULE's answer, since plan
step salary:R15-b** (rulings **R-SAL3**, **R-SAL29**; ledger row **F-21**):
both passes ask :meth:`~app.services.payroll_basis.PayrollBasis
.deduction_applies_on`, which reads each line's rule once per basis through
the occurrence walk every recurring definition is generated by.  The
three-valued MODE that lived here (``deductions_per_year`` 26 / 24 / 12,
compared against the payday's month ordinal by ``_deduction_applies_at``)
is gone with its column.

Split out of the one-module engine at plan step **salary:C12** (ledger row
**P64**).  Imports :mod:`._breakdown` and :mod:`._calendar_questions` and
nothing above them, so :mod:`._pricing` may import it without a cycle.
"""

from dataclasses import dataclass
from decimal import Decimal

from app import ref_cache
from app.enums import CalcMethodEnum, PaycheckLineKindEnum
from app.services.pay_calendar import DerivedPeriod, paydays_in_year_before
from app.services.payroll_basis import PayrollBasis, gross_per_paycheck
from app.utils.deduction_cap import cap_period_amount
from app.utils.money import ZERO, round_money

from ._breakdown import DeductionBreakdown, DeductionLine


@dataclass(frozen=True)
class _DeductionContext:
    """Immutable inputs shared by the pre- and post-tax deduction passes.

    Carries the whole :class:`~app.services.payroll_basis.PayrollBasis` rather
    than a bare profile: the annual-cap cumulative replays prior paydays'
    grosses through :func:`~app.services.payroll_basis.gross_per_paycheck`,
    which needs the paycheck COUNT, and it walks those prior paydays off the
    calendar the same value carries.

    Attributes:
        basis: The owner's salary contract and pay calendar -- and, since plan
            step salary:R15-b, the one reader of each line's cadence
            (:meth:`~app.services.payroll_basis.PayrollBasis
            .deduction_applies_on`).  The payday's month ordinal travelled
            here for that question until then; it is
            :attr:`~._breakdown.PeriodInfo.is_third_paycheck`'s alone now.
        period: The pay period this paycheck is for.
        gross_biweekly: What this paycheck pays before deductions.
    """
    basis: PayrollBasis
    period: DerivedPeriod
    gross_biweekly: Decimal


def _compute_deductions(ctx):
    """Compute the pre- and post-tax deduction lines for a paycheck.

    Runs :func:`_calculate_deductions` once per timing using the shared
    :class:`_DeductionContext`, returning both line lists bundled in a
    :class:`DeductionBreakdown`.

    Args:
        ctx: The per-paycheck :class:`_DeductionContext`.

    Returns:
        DeductionBreakdown with the pre- and post-tax line items.
    """
    return DeductionBreakdown(
        pre_tax=_calculate_deductions(
            ctx, ref_cache.paycheck_line_kind_id(PaycheckLineKindEnum.PRE_TAX_DEDUCTION)
        ),
        post_tax=_calculate_deductions(
            ctx, ref_cache.paycheck_line_kind_id(PaycheckLineKindEnum.POST_TAX_DEDUCTION)
        ),
    )


def _calculate_deductions(ctx, timing_id):
    """Calculate the deduction lines for a specific timing.

    Args:
        ctx: The per-paycheck :class:`_DeductionContext` (basis, period,
            gross_biweekly).
        timing_id: Integer ID of the PaycheckLineKind to filter on.

    Handles:
    - the line's cadence: taken on the paydays its recurrence rule admits,
      every payday when it has none (``basis.deduction_applies_on``)
    - calc_method (flat vs percentage)
    - inflation adjustment
    - annual cap: once a deduction's calendar-year total reaches its
      ``annual_cap`` the period amount is clamped so the year sums to the
      cap and stops (deep-hunt #2; shares ``cap_period_amount`` with the
      investment-contribution timeline so the two surfaces agree)
    """
    deductions = []
    profile = ctx.basis.profile
    if not profile.lines:
        return deductions

    pct_id = ref_cache.calc_method_id(CalcMethodEnum.PERCENTAGE)
    for ded in profile.lines:
        if not ded.is_active:
            continue
        if ded.paycheck_line_kind_id != timing_id:
            continue
        if not ctx.basis.deduction_applies_on(ded, ctx.period.start_date):
            continue

        amount = _raw_deduction_amount(
            ded, ctx.gross_biweekly, ctx.period.start_date, profile, pct_id
        )

        # Clamp to the user-set calendar-year cap (deep-hunt #2).  Only a
        # capped deduction pays for the prior-period cumulative replay; an
        # uncapped one (the common case) passes through untouched.  Read via
        # getattr to match the sibling ``target_account_id`` line: a deduction-
        # like duck type (test fake) may omit the optional column.
        annual_cap = getattr(ded, "annual_cap", None)
        if annual_cap is not None:
            amount = cap_period_amount(
                amount,
                _cumulative_deduction_before(ded, ctx, pct_id),
                annual_cap,
            )

        deductions.append(DeductionLine(
            name=ded.name, amount=amount,
            target_account_id=getattr(ded, "target_account_id", None),
        ))

    return deductions


def _raw_deduction_amount(ded, gross_biweekly, payday, profile, pct_id):
    """Per-paycheck deduction amount before any annual-cap clamp.

    Applies the flat-vs-percentage calc method and the optional inflation
    escalation at FULL Decimal precision, then rounds ONCE at return --
    the E-26(a) rule (intermediates stay full-precision; the line amount
    is the boundary, ratified 2026-06-11).  The pre-ratification shape
    quantized the percentage product BEFORE the inflation multiply and
    again after (a true intermediate quantize, off by up to a cent on
    inflated percentage deductions), and returned flat amounts
    UNQUANTIZED at the column's 4-decimal precision (so the displayed
    2dp line could disagree with the net-pay math by sub-cents).  The
    single boundary rounding fixes both: what the user sees per line is
    exactly what the paycheck subtracts and what the annual-cap
    cumulative sums.

    Pulled out of the line-building loop so the annual-cap cumulative
    reproduces, for prior paydays, the exact amount the loop applies to
    the current one.

    Args:
        ded: The deduction to price.
        gross_biweekly: The gross of the paycheck this is taken from -- the
            base a percentage deduction is a percentage OF.
        payday: The day the paycheck arrives.  A ``date`` rather than a period
            since plan step **balance:X-bh-1**: the inflation escalation reads
            its year and month and nothing else, and the cumulative below
            replays PAYDAYS the calendar counted rather than period values.
        profile: The salary profile, read for ``created_at`` by the inflation
            escalation.
        pct_id: The ref id of the PERCENTAGE calculation method.

    Returns:
        The amount for one paycheck, quantized to the cent.
    """
    amount = Decimal(str(ded.amount))
    if ded.calc_method_id == pct_id:
        amount = gross_biweekly * amount
    if ded.inflation_enabled and ded.inflation_rate:
        inflation_rate = Decimal(str(ded.inflation_rate))
        eff_month = ded.inflation_effective_month or 1
        years = _inflation_years(payday, profile, eff_month)
        if years > 0:
            amount = amount * (1 + inflation_rate) ** years
    return round_money(amount)


def _cumulative_deduction_before(ded, ctx, pct_id):
    """Sum a deduction's raw amounts for this year's earlier paydays.

    Mirrors :func:`~._calendar_questions._get_cumulative_wages` (the FICA
    wage-base precedent): walk the calendar's paydays for this year before
    ``ctx.period``, skip the ones where the deduction is not taken (its
    rule's answer, the same read the live line makes), and sum
    each applicable payday's raw amount -- recomputing that paycheck's gross
    through
    :func:`~app.services.payroll_basis.gross_per_paycheck` so a percentage
    deduction tracks the raise-adjusted gross exactly as the live paycheck
    does.  Summing the raw (pre-cap) amounts is equivalent to summing
    the capped ones (see ``cap_period_amount``), so no capped running state has
    to be threaded across the per-paycheck calls.

    **The paydays come from ``ctx.basis.calendar``** since plan step
    **balance:X-bh-1**, through
    :func:`~app.services.pay_calendar.paydays_in_year_before` -- the same
    producer :func:`~._calendar_questions._get_cumulative_wages` reads, so the
    two cumulatives cannot be summing different years of the same owner.  It
    was ``ctx.all_periods``, where a partial-context caller under-counted the
    cumulative and DEFERRED the cap, so the deduction went on being charged
    after it should have stopped.

    **It also stopped being cubic.**  The old walk asked
    ``_is_third_paycheck(p, all_periods)`` -- itself a scan of every period --
    once per prior period, inside :func:`project_salary`'s loop over every
    period.  Measured 2026-08-30 on the owner's 63 saved paydays with one
    capped deduction, by counting the calls rather than by multiplying the
    loop bounds: **718 scans, 45,234 period comparisons**.  (Reasoning from
    the bounds gives ~250,000, five times too many, because the inner walk
    stops at the current period and at the year boundary -- which is why the
    figure here is counted.)  The ordinal became a bisect over the payday
    sequence, and since plan step salary:R15-b no ordinal is asked here at
    all: membership is one set lookup in the line's walked paydays.

    Args:
        ded: The capped deduction whose year-to-date is wanted.
        ctx: The per-paycheck :class:`_DeductionContext`.
        pct_id: The ref id of the PERCENTAGE calculation method.

    Returns:
        The sum of this deduction's raw amounts for the year's earlier
        paydays, ``ZERO`` when there are none.
    """
    basis = ctx.basis
    profile = basis.profile
    cumulative = ZERO
    for payday in paydays_in_year_before(basis.calendar, ctx.period.start_date):
        if not basis.deduction_applies_on(ded, payday):
            continue
        gross = gross_per_paycheck(basis.annual_salary_on(payday), basis.periods_per_year)
        cumulative += _raw_deduction_amount(
            ded, gross, payday, profile, pct_id,
        )
    return cumulative


def _inflation_years(payday, profile, effective_month):
    """Return the number of full inflation years between profile creation and *payday*.

    Args:
        payday: The day the paycheck arrives.  Its year and month are the whole
            of what is read.
        profile: The salary profile, read for ``created_at``.  A profile with
            no creation stamp escalates nothing.
        effective_month: The month of the year the escalation steps in.

    Returns:
        The whole number of escalations due, never negative.
    """
    created = profile.created_at
    if created is None:
        return 0

    years = payday.year - created.year
    if payday.month < effective_month:
        years -= 1

    return max(0, years)
