"""
Shekel Budget App -- Paycheck engine: the LINES of a paycheck, priced.

**One pass prices a line of any kind, since plan step salary:R18-b** (ruling
**R-SAL38**; ledger row **D59**): the per-paycheck :class:`_LineContext`
every kind's pass shares, the pass itself (:func:`_priced_lines`, run once
per kind), a line's raw amount with its inflation escalation
(:func:`_raw_line_amount`, :func:`_inflation_years`), and a capped line's own
year-to-date (:func:`_cumulative_line_before`) -- the fourth of the package
docstring's calendar questions, kept beside the lines it caps because it
replays exactly what :func:`_raw_line_amount` applies to the live one.  The
two deduction passes are bundled by :func:`_compute_deductions`; the taxable
earning pass by :func:`priced_gross`, which is also the ONE producer of a
paycheck's gross (below); the after-tax earning pass by
:func:`priced_after_tax`.

**Which paydays a line lands on is its RECURRENCE RULE's answer, since plan
step salary:R15-b** (rulings **R-SAL3**, **R-SAL29**; ledger row **F-21**):
every pass asks :meth:`~app.services.payroll_basis.PayrollBasis
.line_applies_on`, which reads each line's rule once per basis through
the occurrence walk every recurring definition is generated by.  The
three-valued MODE that lived here (``deductions_per_year`` 26 / 24 / 12,
compared against the payday's month ordinal by ``_deduction_applies_at``)
is gone with its column.

**A PERCENTAGE line is a percentage of BASE PAY** (R-SAL38), the salary rate
:func:`~app.services.payroll_basis.gross_per_paycheck` derives, and never of
gross: so no existing line moves when a taxable earning joins the gross, a
percentage EARNING is not circular, and the employer-contribution basis
(:mod:`app.services.projection_inputs`) reads the same figure.  Until R18-b
the percentage base was ``gross_biweekly``, which WAS base pay: byte-identical
for every line that existed.

**The gross has ONE producer, and the year-to-date cumulative replays it.**
:func:`priced_gross` is base pay plus the taxable earning lines admitted on
the payday; :func:`~._calendar_questions._get_cumulative_wages` sums the same
function over the year's earlier paydays, so a taxable allowance paid in
March is in the Social Security wage base by April rather than only on the
paycheck it rode -- the shape :func:`_cumulative_line_before` has always had
for a capped line (``CLAUDE.md`` rule 14: one walk).

This leaf was ``_deductions.py`` until R18-b; it was split out of the
one-module engine at plan step **salary:C12** (ledger row **P64**).  Imports
:mod:`._breakdown` and nothing above it, so :mod:`._calendar_questions` and
:mod:`._pricing` may import it without a cycle.
"""

from dataclasses import dataclass
from datetime import date
from decimal import Decimal

from app import ref_cache
from app.enums import CalcMethodEnum, PaycheckLineKindEnum
from app.services.pay_calendar import paydays_in_year_before
from app.services.payroll_basis import PayrollBasis, gross_per_paycheck
from app.utils.deduction_cap import cap_period_amount
from app.utils.money import ZERO, round_money

from ._breakdown import DeductionBreakdown, PricedLine, waterfall_gross


@dataclass(frozen=True)
class _LineContext:
    """Immutable inputs every kind's pricing pass shares for one paycheck.

    Carries the whole :class:`~app.services.payroll_basis.PayrollBasis` rather
    than a bare profile: the annual-cap cumulative replays prior paydays'
    base pay through :func:`~app.services.payroll_basis.gross_per_paycheck`,
    which needs the paycheck COUNT, and it walks those prior paydays off the
    calendar the same value carries.

    ``_DeductionContext`` until plan step salary:R18-b, keyed by a
    ``DerivedPeriod``; it is keyed by the PAYDAY now because the year-to-date
    wage cumulative prices the taxable lines of paydays that are dates off
    the calendar and not periods a caller holds, and the pass read nothing
    of a period but its start.

    Attributes:
        basis: The owner's salary contract and pay calendar -- and, since plan
            step salary:R15-b, the one reader of each line's cadence
            (:meth:`~app.services.payroll_basis.PayrollBasis
            .line_applies_on`).
        payday: The day the paycheck arrives.
        base_biweekly: What the salary pays for this paycheck, before any
            line -- the base every percentage line is a percentage of.
    """
    basis: PayrollBasis
    payday: date
    base_biweekly: Decimal


def priced_gross(ctx) -> tuple[list[PricedLine], Decimal]:
    """Price the taxable earning lines and return them with the gross they make.

    **The one producer of a paycheck's gross**: base pay plus every taxable
    earning line admitted on the payday.  :func:`~._pricing.calculate_paycheck`
    reads it for the paycheck it prices and
    :func:`~._calendar_questions._get_cumulative_wages` for each earlier payday
    of the year, so the two cannot disagree on what a payday's gross was.

    Args:
        ctx: The per-paycheck :class:`_LineContext`.

    Returns:
        ``(taxable lines, gross)`` -- the lines in the profile's order, and
        ``ctx.base_biweekly`` plus their sum.
    """
    taxable = _priced_lines(
        ctx, ref_cache.paycheck_line_kind_id(PaycheckLineKindEnum.TAXABLE_EARNING),
    )
    return taxable, waterfall_gross(
        ctx.base_biweekly, sum((line.amount for line in taxable), ZERO),
    )


def priced_after_tax(ctx) -> list[PricedLine]:
    """Price the after-tax earning lines admitted on the payday.

    Args:
        ctx: The per-paycheck :class:`_LineContext`.

    Returns:
        The after-tax earning lines, in the profile's order.
    """
    return _priced_lines(
        ctx, ref_cache.paycheck_line_kind_id(PaycheckLineKindEnum.AFTER_TAX_EARNING),
    )


def _compute_deductions(ctx):
    """Compute the pre- and post-tax deduction lines for a paycheck.

    Runs :func:`_priced_lines` once per deduction kind using the shared
    :class:`_LineContext`, returning both line lists bundled in a
    :class:`DeductionBreakdown`.

    Args:
        ctx: The per-paycheck :class:`_LineContext`.

    Returns:
        DeductionBreakdown with the pre- and post-tax line items.
    """
    return DeductionBreakdown(
        pre_tax=_priced_lines(
            ctx, ref_cache.paycheck_line_kind_id(PaycheckLineKindEnum.PRE_TAX_DEDUCTION)
        ),
        post_tax=_priced_lines(
            ctx, ref_cache.paycheck_line_kind_id(PaycheckLineKindEnum.POST_TAX_DEDUCTION)
        ),
    )


def _priced_lines(ctx, kind_id):
    """Price the lines of one kind for a paycheck.

    Args:
        ctx: The per-paycheck :class:`_LineContext` (basis, payday,
            base_biweekly).
        kind_id: Integer ID of the PaycheckLineKind to filter on.

    Handles:
    - the line's cadence: taken on the paydays its recurrence rule admits,
      every payday when it has none (``basis.line_applies_on``)
    - calc_method (flat vs percentage of BASE pay)
    - inflation adjustment
    - annual cap: once a line's calendar-year total reaches its
      ``annual_cap`` the period amount is clamped so the year sums to the
      cap and stops (deep-hunt #2; shares ``cap_period_amount`` with the
      investment-contribution timeline so the two surfaces agree)

    Returns:
        The priced lines of that kind, in the profile's line order; empty
        when the profile has none or none is taken on this payday.
    """
    priced = []
    profile = ctx.basis.profile
    if not profile.lines:
        return priced

    pct_id = ref_cache.calc_method_id(CalcMethodEnum.PERCENTAGE)
    for line in profile.lines:
        if not line.is_active:
            continue
        if line.paycheck_line_kind_id != kind_id:
            continue
        if not ctx.basis.line_applies_on(line, ctx.payday):
            continue

        amount = _raw_line_amount(
            line, ctx.base_biweekly, ctx.payday, profile, pct_id
        )

        # Clamp to the user-set calendar-year cap (deep-hunt #2).  Only a
        # capped line pays for the prior-period cumulative replay; an
        # uncapped one (the common case) passes through untouched.  Read via
        # getattr to match the sibling ``target_account_id`` line: a
        # line-like duck type (test fake) may omit the optional column.
        annual_cap = getattr(line, "annual_cap", None)
        if annual_cap is not None:
            amount = cap_period_amount(
                amount,
                _cumulative_line_before(line, ctx, pct_id),
                annual_cap,
            )

        # The row's identity rides with its price (plan step salary:S11-b), read
        # like ``target_account_id`` because the engine suite's line fakes
        # carry no ``id``.
        priced.append(PricedLine(
            name=line.name, amount=amount,
            target_account_id=getattr(line, "target_account_id", None),
            paycheck_line_id=getattr(line, "id", None),
        ))

    return priced


def _raw_line_amount(line, base_biweekly, payday, profile, pct_id):
    """Per-paycheck line amount before any annual-cap clamp.

    Applies the flat-vs-percentage calc method and the optional inflation
    escalation at FULL Decimal precision, then rounds ONCE at return --
    the E-26(a) rule (intermediates stay full-precision; the line amount
    is the boundary, ratified 2026-06-11).  The pre-ratification shape
    quantized the percentage product BEFORE the inflation multiply and
    again after (a true intermediate quantize, off by up to a cent on
    inflated percentage deductions), and returned flat amounts
    UNQUANTIZED at the column's 4-decimal precision (so the displayed
    2dp line could disagree with the net-pay math by sub-cents).  The
    single boundary rounding fixes both: what the user sees per line is
    exactly what the paycheck adds or subtracts and what the annual-cap
    cumulative sums.

    Pulled out of the line-building loop so the annual-cap cumulative
    reproduces, for prior paydays, the exact amount the loop applies to
    the current one.

    Args:
        line: The line to price.
        base_biweekly: What the salary pays for this paycheck -- the base a
            percentage line is a percentage OF (ruling R-SAL38: base pay,
            never the gross the taxable earnings make).
        payday: The day the paycheck arrives.  A ``date`` rather than a period
            since plan step **balance:X-bh-1**: the inflation escalation reads
            its year and month and nothing else, and the cumulative below
            replays PAYDAYS the calendar counted rather than period values.
        profile: The salary profile, read for ``created_at`` by the inflation
            escalation.
        pct_id: The ref id of the PERCENTAGE calculation method.

    Returns:
        The amount for one paycheck, quantized to the cent.
    """
    amount = Decimal(str(line.amount))
    if line.calc_method_id == pct_id:
        amount = base_biweekly * amount
    if line.inflation_enabled and line.inflation_rate:
        inflation_rate = Decimal(str(line.inflation_rate))
        eff_month = line.inflation_effective_month or 1
        years = _inflation_years(payday, profile, eff_month)
        if years > 0:
            amount = amount * (1 + inflation_rate) ** years
    return round_money(amount)


def _cumulative_line_before(line, ctx, pct_id):
    """Sum a line's raw amounts for this year's earlier paydays.

    Mirrors :func:`~._calendar_questions._get_cumulative_wages` (the FICA
    wage-base precedent): walk the calendar's paydays for this year before
    ``ctx.payday``, skip the ones where the line is not taken (its rule's
    answer, the same read the live line makes), and sum each applicable
    payday's raw amount -- recomputing that paycheck's base pay through
    :func:`~app.services.payroll_basis.gross_per_paycheck` so a percentage
    line tracks the raise-adjusted base exactly as the live paycheck does.
    Summing the raw (pre-cap) amounts is equivalent to summing the capped
    ones (see ``cap_period_amount``), so no capped running state has to be
    threaded across the per-paycheck calls.

    **The paydays come from ``ctx.basis.calendar``** since plan step
    **balance:X-bh-1**, through
    :func:`~app.services.pay_calendar.paydays_in_year_before` -- the same
    producer :func:`~._calendar_questions._get_cumulative_wages` reads, so the
    two cumulatives cannot be summing different years of the same owner.  It
    was ``ctx.all_periods``, where a partial-context caller under-counted the
    cumulative and DEFERRED the cap, so the deduction went on being charged
    after it should have stopped.

    **It also stopped being cubic.**  The old walk asked
    ``_is_third_paycheck(p, all_periods)`` -- itself a scan of every period --
    once per prior period, inside :func:`project_salary`'s loop over every
    period.  Measured 2026-08-30 on the owner's 63 saved paydays with one
    capped deduction, by counting the calls rather than by multiplying the
    loop bounds: **718 scans, 45,234 period comparisons**.  (Reasoning from
    the bounds gives ~250,000, five times too many, because the inner walk
    stops at the current period and at the year boundary -- which is why the
    figure here is counted.)  The ordinal became a bisect over the payday
    sequence, and since plan step salary:R15-b no ordinal is asked here at
    all: membership is one set lookup in the line's walked paydays.

    Args:
        line: The capped line whose year-to-date is wanted.
        ctx: The per-paycheck :class:`_LineContext`.
        pct_id: The ref id of the PERCENTAGE calculation method.

    Returns:
        The sum of this line's raw amounts for the year's earlier paydays,
        ``ZERO`` when there are none.
    """
    basis = ctx.basis
    profile = basis.profile
    cumulative = ZERO
    for payday in paydays_in_year_before(basis.calendar, ctx.payday):
        if not basis.line_applies_on(line, payday):
            continue
        base = gross_per_paycheck(basis.annual_salary_on(payday), basis.periods_per_year)
        cumulative += _raw_line_amount(
            line, base, payday, profile, pct_id,
        )
    return cumulative


def _inflation_years(payday, profile, effective_month):
    """Return the number of full inflation years between profile creation and *payday*.

    Args:
        payday: The day the paycheck arrives.  Its year and month are the whole
            of what is read.
        profile: The salary profile, read for ``created_at``.  A profile with
            no creation stamp escalates nothing.
        effective_month: The month of the year the escalation steps in.

    Returns:
        The whole number of escalations due, never negative.
    """
    created = profile.created_at
    if created is None:
        return 0

    years = payday.year - created.year
    if payday.month < effective_month:
        years -= 1

    return max(0, years)
