"""Deployment-layer assertions for Commit C-38.

Covers audit findings F-108 (`.env.dev` references nonexistent path),
F-109 (`.env.example` carries a functional dev `POSTGRES_PASSWORD`),
F-112 (DevConfig missing pragma comment about HTTP-localhost cookie
posture), and F-148 (env-only secrets posture migrated to operator-
optional Docker secrets).

Tests fall into three categories:

1. **Filesystem state** -- the files the audit reviewer inspects on
   disk are in the expected shape (.env.dev removed, .env.example
   sanitized, .gitignore covers .env.dev).
2. **Source-level structure** -- the production source files
   (`app/config.py`, `entrypoint.sh`, `deploy/docker-compose.prod.yml`)
   carry the expected hooks for the file-backed secrets posture.
3. **Behavioral runtime checks on the entrypoint loader** -- the
   `_load_secret` shell function is extracted from entrypoint.sh,
   rewritten to point at a test-local secrets directory, and
   exercised as a bash script.  This proves the loader actually
   reads, falls back, rejects empty files, and preserves special
   characters as the audit plan requires (the file-text-only
   assertions in category 1 cannot prove behaviour).

Style note: this file follows the test_seed_credential_hygiene.py
pattern from Commit C-34 (file-text + behaviour split, fixtures via
Path constants, parametrize for repetitive coverage).
"""
from __future__ import annotations

import base64
import re
import shutil
import subprocess
from importlib import reload
from pathlib import Path

import pytest

from app import config as config_module


REPO_ROOT = Path(__file__).resolve().parents[2]

# ── Files under assertion ──────────────────────────────────────────
ENV_EXAMPLE = REPO_ROOT / ".env.example"
ENV_DEV = REPO_ROOT / ".env.dev"
GITIGNORE = REPO_ROOT / ".gitignore"
APP_CONFIG = REPO_ROOT / "app" / "config.py"
ENTRYPOINT_SCRIPT = REPO_ROOT / "entrypoint.sh"
DOCKER_COMPOSE = REPO_ROOT / "docker-compose.yml"
DOCKER_COMPOSE_PROD = REPO_ROOT / "deploy" / "docker-compose.prod.yml"
RUNBOOK_SECRETS = REPO_ROOT / "docs" / "runbook_secrets.md"

# Length of a SECRET_KEY generated by ``token_hex(32)`` -- the
# documented production form.  Used by the loader-behaviour fixture
# below so the synthetic value matches the real one's shape.
SECRET_KEY_HEX_BYTES = 64

# Subprocess timeout for bash invocations of the extracted loader.
# The loader does no I/O beyond a single file read; 5s is generous.
BASH_TEST_TIMEOUT_S = 5

# Subprocess timeout for ``docker compose config`` invocations.
DOCKER_SUBPROCESS_TIMEOUT_S = 60


def _docker_available() -> bool:
    """Return True when ``docker`` is on PATH and ``docker info`` succeeds."""
    if shutil.which("docker") is None:
        return False
    try:
        result = subprocess.run(
            ["docker", "info"],
            capture_output=True,
            text=True,
            timeout=DOCKER_SUBPROCESS_TIMEOUT_S,
            check=False,
        )
    except (subprocess.TimeoutExpired, OSError):
        return False
    return result.returncode == 0


# ──────────────────────────────────────────────────────────────────
# F-108: .env.dev removed from the branch
# ──────────────────────────────────────────────────────────────────


class TestEnvDevRemoved:
    """``.env.dev`` is gone from the working tree and gitignored.

    The audit verified that ``.env.dev:1`` referenced
    ``FLASK_APP=src/flask_app/app.py`` -- a path that has never existed
    in this repo.  The C-38 fix deletes the file outright and adds a
    ``.gitignore`` entry so an operator who recreates a local
    ``.env.dev`` for any reason cannot accidentally commit it.
    """

    def test_env_dev_file_does_not_exist(self) -> None:
        """``.env.dev`` is absent from the working tree."""
        assert not ENV_DEV.exists(), (
            f".env.dev still present at {ENV_DEV}; the F-108 cleanup did not "
            "complete (the file referenced a nonexistent FLASK_APP path "
            "and is documented for deletion in remediation Commit C-38)."
        )

    def test_gitignore_covers_env_dev(self) -> None:
        """``.gitignore`` lists ``.env.dev`` so a recreated copy stays untracked."""
        text = GITIGNORE.read_text(encoding="utf-8")
        # We require an exact entry on a line by itself rather than a
        # broader glob match -- the audit's ask is the literal
        # ``.env.dev`` filename.  ``re.MULTILINE`` so ``^`` matches the
        # start of any line.
        assert re.search(r"^\.env\.dev\s*$", text, re.MULTILINE), (
            ".gitignore does not list ``.env.dev`` on its own line; "
            "an operator recreating a local .env.dev (e.g. for a test "
            "Flask entrypoint) could accidentally commit it (F-108)."
        )


# ──────────────────────────────────────────────────────────────────
# F-109: .env.example sanitized of the functional dev password
# ──────────────────────────────────────────────────────────────────


class TestEnvExampleSanitized:
    """``.env.example`` ships an empty ``POSTGRES_PASSWORD`` placeholder."""

    @pytest.fixture(scope="class")
    def env_example_text(self) -> str:
        """Return the full .env.example source as a string."""
        return ENV_EXAMPLE.read_text(encoding="utf-8")

    def test_postgres_password_field_is_empty(self, env_example_text: str) -> None:
        """``POSTGRES_PASSWORD=`` is empty by default in .env.example.

        Asserts on a line-anchored exact match.  A regression to
        ``POSTGRES_PASSWORD=shekel_pass`` (or any other non-empty
        functional default) would re-introduce the F-109 finding: a
        copy-paste of .env.example would carry a working dev password
        into a production environment.  The base
        ``docker-compose.yml`` then reuses that password in
        DATABASE_URL, so the audit treats it as a leaked credential
        even though the file is committed as a template.
        """
        # Match the exact assignment with nothing after the ``=``
        # except optional whitespace.  This catches both the original
        # ``POSTGRES_PASSWORD=shekel_pass`` regression AND a sneakier
        # ``POSTGRES_PASSWORD= `` (trailing space) form that bash
        # would still treat as empty but a copy-paste would not.
        assert re.search(
            r"^POSTGRES_PASSWORD=\s*$",
            env_example_text,
            re.MULTILINE,
        ), (
            ".env.example does not ship POSTGRES_PASSWORD with an "
            "empty value; F-109 regression -- the file would carry a "
            "functional dev password into production for any operator "
            "who copies it verbatim to .env."
        )

    def test_postgres_password_section_documents_generation(
        self, env_example_text: str,
    ) -> None:
        """The POSTGRES_PASSWORD section explains how to generate a value.

        Without an inline generation command the operator falls back
        to whatever they had in their previous .env, which on a fresh
        checkout means they invent a weak default (``password123``).
        The C-34 SECRET_KEY block established the precedent that
        every required secret in this file ships its own generation
        command; this test enforces that POSTGRES_PASSWORD now
        follows the same pattern.
        """
        # Find the POSTGRES_PASSWORD assignment and read backwards
        # through the comment block above it.  Comment lines are
        # ``#`` prefixed and immediately precede the assignment.
        match = re.search(
            r"((?:^#[^\n]*\n)+)^POSTGRES_PASSWORD=\s*$",
            env_example_text,
            re.MULTILINE,
        )
        assert match is not None, (
            ".env.example POSTGRES_PASSWORD assignment is not preceded "
            "by a comment block; the operator has no inline guidance "
            "for generating a value."
        )
        comment_block = match.group(1)
        # The recommended generation commands in the docs/runbook are
        # ``secrets.token_urlsafe(32)`` and ``openssl rand``.  We
        # accept either being mentioned -- the assertion is that SOME
        # generation hint exists, not which.
        assert "token_urlsafe" in comment_block or "openssl rand" in comment_block, (
            ".env.example POSTGRES_PASSWORD comment block lists no "
            "generation command; an operator copying the template "
            "would fall back to inventing a weak default."
        )

    def test_postgres_password_block_references_docker_secrets_path(
        self, env_example_text: str,
    ) -> None:
        """The POSTGRES_PASSWORD block points operators at Docker secrets.

        Defense-in-depth note: even if an operator forgets to read
        the runbook, the .env.example block tells them about the
        file-backed posture so they can opt in.
        """
        match = re.search(
            r"((?:^#[^\n]*\n)+)^POSTGRES_PASSWORD=\s*$",
            env_example_text,
            re.MULTILINE,
        )
        assert match is not None
        comment_block = match.group(1)
        # The docker-secrets escape hatch must be discoverable from
        # the .env.example comment block -- not just from the runbook.
        assert "docker secret" in comment_block.lower() or (
            "/opt/docker/shekel/secrets" in comment_block
            and "F-148" in comment_block
        ), (
            ".env.example POSTGRES_PASSWORD comment block does not "
            "mention the Docker secrets opt-in (audit finding F-148 / "
            "Commit C-38).  Operators who read only this file will "
            "not discover the file-backed posture."
        )


# ──────────────────────────────────────────────────────────────────
# F-112: DevConfig pragma comment for HTTP-localhost cookie posture
# ──────────────────────────────────────────────────────────────────


class TestProdConfigRejectsDockerSecretPlaceholder:
    """ProdConfig rejects ``replaced_by_docker_secret`` as a SECRET_KEY value.

    Defense-in-depth complement to the entrypoint.sh case statement:
    the entrypoint catches the placeholder before any deploy script
    runs; this Python-side check catches it again at Flask config
    load time.  Both fire at different layers of the boot sequence so
    a regression in either one is caught by the other.
    """

    @pytest.mark.parametrize(
        "placeholder_value",
        [
            # Exact match -- the placeholder set membership branch.
            "replaced_by_docker_secret",
            # Long-enough padding to clear the 32-char length floor;
            # the ``startswith`` branch is what catches it.
            "replaced_by_docker_secret_padded_to_be_long_enough_to_pass_length_check",
        ],
        ids=["exact-match", "padded-long"],
    )
    def test_prodconfig_rejects_docker_secret_placeholder(
        self, placeholder_value: str, monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """ProdConfig refuses to load when SECRET_KEY is the documented placeholder.

        Both the exact placeholder and longer ``startswith`` variants
        must surface the ``known placeholder`` error.  Without these
        rejections, an operator on Posture 2 whose docker secret file
        is missing or unreadable would boot under the publicly-known
        placeholder value -- exactly the F-148 weakness Commit C-38
        is closing.
        """
        # ProdConfig reads SECRET_KEY at class-attribute time
        # (BaseConfig.SECRET_KEY = os.getenv(...)) so we must set the
        # env var BEFORE the module reload.  Use monkeypatch so any
        # exception in the test body still rolls the env back.
        monkeypatch.setenv("SECRET_KEY", placeholder_value)
        monkeypatch.setenv("DATABASE_URL", "postgresql://x:x@x:5432/x")
        monkeypatch.setenv("RATELIMIT_STORAGE_URI", "redis://x:6379/0")
        try:
            reload(config_module)
            with pytest.raises(ValueError, match="known placeholder"):
                config_module.ProdConfig()
        finally:
            # Reload once more after the test so the next test that
            # touches config_module sees the original env-driven
            # class attributes.
            reload(config_module)


class TestDevConfigPragma:
    """``DevConfig`` carries an explicit pragma for its cookie posture.

    The audit-verified gap: DevConfig inherits Flask's defaults for
    ``SESSION_COOKIE_SECURE`` (False), ``SESSION_COOKIE_SAMESITE``
    (None), and ``SESSION_COOKIE_HTTPONLY`` (True), but does not
    document why it diverges from ProdConfig's hardened defaults.  An
    operator skim-reading config.py would see DevConfig as a hole.
    The C-38 pragma makes the rationale explicit so a future reader
    -- or a future audit -- understands the divergence is deliberate.
    """

    @pytest.fixture(scope="class")
    def config_text(self) -> str:
        """Return the full app/config.py source as a string."""
        return APP_CONFIG.read_text(encoding="utf-8")

    def test_devconfig_class_has_substantive_docstring(
        self, config_text: str,
    ) -> None:
        """DevConfig's docstring covers the cookie-flag pragma.

        Match the DevConfig class header and isolate its body before
        the next class or end-of-file.  The docstring must mention
        the specific cookie flags that are NOT set, not just a
        generic "dev mode" line.
        """
        # Capture from "class DevConfig" up to the next "class " or
        # end of file.  ``re.DOTALL`` lets ``.`` cross newlines.
        match = re.search(
            r"class DevConfig\(BaseConfig\):(.+?)(?=\nclass |\Z)",
            config_text,
            re.DOTALL,
        )
        assert match is not None, "DevConfig class not found in app/config.py"
        body = match.group(1)
        # Must mention the specific finding ID so a future audit
        # reviewer can match the pragma to the audit catalog.
        assert "F-112" in body, (
            "DevConfig docstring does not reference audit finding F-112; "
            "future audit reviewers cannot match the pragma to the "
            "audit catalog."
        )
        # Must mention the load-bearing cookie flag the pragma is
        # explaining.  ``SESSION_COOKIE_SECURE`` is the flag that
        # would silently break dev if DevConfig adopted ProdConfig's
        # posture, so it is the one that matters most.
        assert "SESSION_COOKIE_SECURE" in body, (
            "DevConfig docstring does not mention SESSION_COOKIE_SECURE; "
            "the pragma is supposed to explain why dev does NOT set "
            "this flag (Flask's default is False; ProdConfig sets True)."
        )


# ──────────────────────────────────────────────────────────────────
# F-148: entrypoint.sh _load_secret helper -- structural assertions
# ──────────────────────────────────────────────────────────────────


class TestEntrypointLoaderSourceShape:
    """The entrypoint carries the _load_secret helper with the right contract.

    Source-level checks pair with the behavioural tests below: a
    regression that removes the helper or changes its return-shape
    would fail BOTH this test class (immediately) and the behavioural
    class (slowly, via shell exec).  Catching it at source level
    surfaces the breakage without spawning bash.
    """

    @pytest.fixture(scope="class")
    def entrypoint_text(self) -> str:
        """Return the full entrypoint.sh source as a string."""
        return ENTRYPOINT_SCRIPT.read_text(encoding="utf-8")

    def test_loader_function_is_defined(self, entrypoint_text: str) -> None:
        """``_load_secret() {`` appears in entrypoint.sh."""
        assert re.search(
            r"^_load_secret\(\)\s*\{",
            entrypoint_text,
            re.MULTILINE,
        ), (
            "entrypoint.sh no longer defines _load_secret; the F-148 "
            "Docker secrets loader has been removed (Commit C-38 regression)."
        )

    @pytest.mark.parametrize(
        "var_name,file_name",
        [
            ("SECRET_KEY", "secret_key"),
            ("POSTGRES_PASSWORD", "postgres_password"),
            ("APP_ROLE_PASSWORD", "app_role_password"),
            ("TOTP_ENCRYPTION_KEY", "totp_encryption_key"),
            ("TOTP_ENCRYPTION_KEY_OLD", "totp_encryption_key_old"),
        ],
    )
    def test_loader_is_invoked_for_each_secret(
        self, entrypoint_text: str, var_name: str, file_name: str,
    ) -> None:
        """Every documented secret has a ``_load_secret <VAR> <file>`` call."""
        # Match the canonical invocation.  Whitespace tolerant but
        # we require the exact var/file pair so a typo
        # (``_load_secret SECRET_KEY postgres_password``) would
        # surface here instead of as a runtime auth error.
        assert re.search(
            rf"^\s*_load_secret\s+{var_name}\s+{file_name}\b",
            entrypoint_text,
            re.MULTILINE,
        ), (
            f"entrypoint.sh does not invoke ``_load_secret {var_name} "
            f"{file_name}``; the secret will not be loaded from the "
            "file-backed posture and the operator's docker secret "
            "would silently fall back to the env value (F-148 regression)."
        )

    def test_loader_invocations_precede_secret_key_validation(
        self, entrypoint_text: str,
    ) -> None:
        """Every ``_load_secret`` call appears BEFORE the SECRET_KEY shape check.

        Ordering invariant: the SECRET_KEY length / placeholder check
        only works correctly if the env var is already populated from
        whichever source (file or env).  A regression that runs the
        loader AFTER the validation would let a placeholder pass the
        shape check and then have its real value loaded -- the wrong
        value would never be inspected, defeating the validation.
        """
        loader_calls = list(re.finditer(
            r"^\s*_load_secret\s+\w+\s+\w+\b",
            entrypoint_text,
            re.MULTILINE,
        ))
        assert loader_calls, "no _load_secret invocations found"
        # The validation block opens with a ``-z "${SECRET_KEY}"``
        # check.  Find the earliest one.
        validation_match = re.search(
            r'\[\s*-z\s+"\$\{SECRET_KEY\}"\s*\]',
            entrypoint_text,
        )
        assert validation_match is not None, (
            "entrypoint.sh no longer validates SECRET_KEY shape"
        )
        last_loader_offset = max(m.start() for m in loader_calls)
        assert last_loader_offset < validation_match.start(), (
            "_load_secret invocation appears AFTER the SECRET_KEY "
            "shape check; the validation runs against the env-only "
            "value and the file-backed override would slip past it."
        )

    def test_secret_key_placeholder_rejected_at_entrypoint(
        self, entrypoint_text: str,
    ) -> None:
        """``replaced_by_docker_secret*`` rejected by the SECRET_KEY case statement.

        The placeholder is the documented form an operator leaves in
        .env when migrating to Posture 2 (file-backed secrets).  If
        the secret file at /run/secrets/secret_key is missing or
        unreadable, the placeholder remains as the active SECRET_KEY
        -- a publicly-known value.  Catching it here closes the gap
        where the operator believes they are on Posture 2 but is
        actually running on the placeholder.
        """
        # The case statement must include ``replaced_by_docker_secret*``
        # as one of the rejected patterns alongside the historical
        # placeholders.
        assert re.search(
            r"replaced_by_docker_secret\*",
            entrypoint_text,
        ), (
            "entrypoint.sh case statement does not reject the "
            "``replaced_by_docker_secret*`` placeholder; an operator "
            "whose docker secret file is missing would silently boot "
            "under the public placeholder value (audit finding F-148 "
            "regression / hole in Commit C-38)."
        )

    def test_loader_rebuilds_database_url_when_postgres_secret_loaded(
        self, entrypoint_text: str,
    ) -> None:
        """The DATABASE_URL rebuild branch fires when POSTGRES_PASSWORD comes from a file.

        Compose interpolates ``DATABASE_URL`` from
        ``${POSTGRES_PASSWORD}`` at config-time, baking whatever
        placeholder the operator put in .env into the URI.  When the
        loader overwrites ``POSTGRES_PASSWORD`` with the real value
        from /run/secrets, ``DATABASE_URL`` goes stale and the deploy
        scripts (init_database.py, seed_*.py) connect under the
        placeholder -- which the postgres role does not recognise.
        Asserting on the rebuild branch catches a regression that
        removes it.
        """
        # The rebuild block is conditional on the
        # ``_postgres_password_loaded_from_file`` flag.  Match the
        # opening conditional.
        assert re.search(
            r'_postgres_password_loaded_from_file.*?-eq\s+1.*?\bexport\s+DATABASE_URL=',
            entrypoint_text,
            re.DOTALL,
        ), (
            "entrypoint.sh no longer rebuilds DATABASE_URL when "
            "POSTGRES_PASSWORD comes from a docker secret file; the "
            "deploy scripts will connect under the .env placeholder "
            "instead of the real password."
        )
        # And DB_PASSWORD must be rebuilt too -- psql calls in the
        # entrypoint use it directly.
        assert re.search(
            r'_postgres_password_loaded_from_file.*?-eq\s+1.*?\bexport\s+DB_PASSWORD=',
            entrypoint_text,
            re.DOTALL,
        ), (
            "entrypoint.sh no longer rebuilds DB_PASSWORD when "
            "POSTGRES_PASSWORD comes from a docker secret file; the "
            "psql schema-creation and role-provisioning calls will "
            "use the .env placeholder password instead."
        )


# ──────────────────────────────────────────────────────────────────
# F-148: entrypoint.sh _load_secret helper -- behavioural tests
# ──────────────────────────────────────────────────────────────────


def _extract_loader_function(test_secrets_dir: Path) -> str:
    """Return the bash source of ``_load_secret`` rewritten to look in
    ``test_secrets_dir`` instead of /run/secrets.

    Extracts the function from the live entrypoint.sh so the
    behavioural tests exercise the production code (not a
    duplicate).  The single string substitution ``"/run/secrets/"`` ->
    ``"<test_dir>/"`` lets the otherwise-unmodified function read
    from the test fixture.

    The substitution ONLY targets the literal path inside the
    ``secret_path`` assignment.  The error-message references to
    ``/opt/docker/shekel/secrets/`` are operator hints and are not
    rewritten -- their content is irrelevant to behaviour and a
    rewrite would obscure the test output if a failure surfaces.
    """
    text = ENTRYPOINT_SCRIPT.read_text(encoding="utf-8")
    # Capture the function from "_load_secret() {" to the matching
    # "}" at column 0.  ``re.MULTILINE`` so ``^`` matches the start
    # of any line; ``re.DOTALL`` so ``.`` crosses newlines.
    match = re.search(
        r"^(_load_secret\(\)\s*\{.*?\n^\})",
        text,
        re.MULTILINE | re.DOTALL,
    )
    if match is None:
        pytest.fail(
            "Could not extract _load_secret from entrypoint.sh; the "
            "function must start with ``_load_secret() {`` at column "
            "0 and end with ``}`` at column 0."
        )
    func_source = match.group(1)
    # Rewrite only the literal path inside the secret_path
    # assignment.  The function uses
    # ``local secret_path="/run/secrets/${file_name}"`` -- we replace
    # ``/run/secrets/`` with the absolute test path.
    rewritten = func_source.replace("/run/secrets/", f"{test_secrets_dir}/")
    return rewritten


def _run_loader_script(loader_func_source: str, body: str) -> subprocess.CompletedProcess[str]:
    """Run a bash script that sources the loader and executes ``body``."""
    script = (
        "#!/bin/bash\n"
        "set -eEo pipefail\n"
        f"{loader_func_source}\n\n"
        f"{body}\n"
    )
    return subprocess.run(
        ["bash", "-c", script],
        capture_output=True,
        text=True,
        timeout=BASH_TEST_TIMEOUT_S,
        check=False,
    )


class TestEntrypointLoaderBehaviour:
    """Run the extracted ``_load_secret`` against real fixture files.

    These tests prove the function actually:
    1. Loads a value when the file exists.
    2. Falls back silently (env unchanged) when the file is absent.
    3. Rejects an empty file with a clear diagnostic.
    4. Strips trailing newlines (``echo`` writes them) without
       mangling internal newlines or special characters.
    """

    def test_loader_reads_secret_when_file_present(self, tmp_path: Path) -> None:
        """A populated file overrides any env value the helper sees."""
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        (secrets_dir / "secret_key").write_text("a" * SECRET_KEY_HEX_BYTES)
        loader = _extract_loader_function(secrets_dir)

        result = _run_loader_script(
            loader,
            (
                # Pre-set the env var to a known wrong value so we
                # can prove the loader OVERWROTE it (not merely
                # appended to a missing var).
                "export TEST_SECRET_KEY=stale-env-value\n"
                "_load_secret TEST_SECRET_KEY secret_key\n"
                "echo \"VAR=${TEST_SECRET_KEY}\""
            ),
        )

        assert result.returncode == 0, (
            f"loader exited non-zero: stderr={result.stderr!r}"
        )
        # Exact match: 64 ``a`` characters, no trailing whitespace.
        assert f"VAR={'a' * SECRET_KEY_HEX_BYTES}\n" in result.stdout, (
            f"loader did not overwrite env var with file content; "
            f"stdout={result.stdout!r}"
        )

    def test_loader_falls_back_to_env_when_file_absent(self, tmp_path: Path) -> None:
        """A missing file is a silent no-op; env value is preserved."""
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        # Note: NO file created.  The loader should not error.
        loader = _extract_loader_function(secrets_dir)

        result = _run_loader_script(
            loader,
            (
                "export TEST_SECRET=fallback-env-value\n"
                # The argument 'nonexistent_file' has no matching
                # file in secrets_dir, so the loader returns 0
                # without touching the var.
                "_load_secret TEST_SECRET nonexistent_file\n"
                "echo \"VAR=${TEST_SECRET}\""
            ),
        )

        assert result.returncode == 0, (
            f"loader exited non-zero on missing file: stderr={result.stderr!r}"
        )
        assert "VAR=fallback-env-value" in result.stdout, (
            "loader mutated the env var when the secret file was "
            f"absent; stdout={result.stdout!r}"
        )
        # No "Loaded ..." log line should fire when the file is absent.
        assert "Loaded " not in result.stdout, (
            "loader logged a ``Loaded ...`` line for a missing file; "
            "the no-op branch should be silent."
        )

    def test_loader_rejects_empty_secret_file(self, tmp_path: Path) -> None:
        """A present-but-empty file is a misconfiguration -- fail fast."""
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        # Touch the file so it exists but contains no bytes.
        (secrets_dir / "empty_file").write_bytes(b"")
        loader = _extract_loader_function(secrets_dir)

        result = _run_loader_script(
            loader,
            "_load_secret TEST_SECRET empty_file",
        )

        assert result.returncode != 0, (
            "loader accepted an empty secret file and would have "
            "exported an empty value -- the operator's intent to use "
            "file-backed secrets is clear (file exists) but the file "
            "is empty; this is a misconfiguration that must fail fast."
        )
        assert "is present but empty" in result.stderr, (
            f"loader did not emit the expected diagnostic for an empty "
            f"secret file; stderr={result.stderr!r}"
        )

    def test_loader_strips_trailing_newline(self, tmp_path: Path) -> None:
        """``echo "value" > file`` writes a trailing newline; loader strips it.

        Bash's ``$(< file)`` command substitution strips trailing
        newlines, so a file written by the typical ``echo`` pattern
        produces the same in-process value as ``printf 'value' >
        file``.  This is documented in the helper's source comment
        and is the load-bearing reason the helper uses ``$(< ...)``
        instead of ``cat``.
        """
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        # Use ``write_text`` -- Python's text-mode write does NOT add
        # a trailing newline, so we add one explicitly to mirror the
        # ``echo "value" > file`` shell pattern.
        (secrets_dir / "with_newline").write_text("value-with-trailing-newline\n")
        loader = _extract_loader_function(secrets_dir)

        result = _run_loader_script(
            loader,
            (
                "_load_secret TEST_VAR with_newline\n"
                # ``${#TEST_VAR}`` is the byte length.  29 chars
                # without the trailing newline; 30 with it.  We
                # assert on the length directly so a regression that
                # leaves the newline in surfaces as a precise number,
                # not a fuzzy "not equal".
                "echo \"LEN=${#TEST_VAR}\"\n"
                "echo \"VAL=${TEST_VAR}\""
            ),
        )

        assert result.returncode == 0, result.stderr
        # 27 = len("value-with-trailing-newline").
        assert "LEN=27" in result.stdout, (
            f"loader did not strip the trailing newline; stdout={result.stdout!r}"
        )
        assert "VAL=value-with-trailing-newline" in result.stdout

    def test_entrypoint_rejects_placeholder_when_secret_file_missing(
        self,
    ) -> None:
        """The entrypoint case statement rejects ``replaced_by_docker_secret*``.

        Behavioural check: extract the SECRET_KEY validation block
        from entrypoint.sh, run it in bash with the placeholder set
        as SECRET_KEY, assert the script exits non-zero with the
        placeholder diagnostic.  Mirrors the source-shape assertion
        in TestEntrypointLoaderSourceShape so a regression that
        leaves the case statement intact but breaks the case match
        (e.g. typo in the pattern) is still caught.
        """
        # Extract the entire SECRET_KEY validation section (header
        # ``# ── 0a.``) up to the next section (``# ── 0b.``).  The
        # placeholder (32+ chars) clears the length check, so the
        # case statement is what must catch it.  We capture the
        # whole 0a section because the case statement now contains
        # a nested case for the docker-secret hint -- a regex that
        # tries to capture only up to the first ``esac`` would
        # truncate at the inner one.
        text = ENTRYPOINT_SCRIPT.read_text(encoding="utf-8")
        match = re.search(
            r"(# ── 0a\. Validate SECRET_KEY shape.*?)(?=\n# ── 0b\.)",
            text,
            re.DOTALL,
        )
        if match is None:
            pytest.fail(
                "Could not extract SECRET_KEY validation section "
                "from entrypoint.sh; the section must start with "
                "``# ── 0a. Validate SECRET_KEY shape`` and end "
                "before ``# ── 0b.``."
            )
        validation = match.group(1)
        script = (
            "#!/bin/bash\n"
            "set -eEo pipefail\n"
            # 32+ char placeholder so the length check passes.
            'export SECRET_KEY="replaced_by_docker_secret_padded_to_be_long_enough"\n'
            f"{validation}\n"
            'echo "should-not-reach"\n'
        )
        result = subprocess.run(
            ["bash", "-c", script],
            capture_output=True,
            text=True,
            timeout=BASH_TEST_TIMEOUT_S,
            check=False,
        )
        assert result.returncode != 0, (
            "entrypoint.sh validation accepted "
            "``replaced_by_docker_secret_padded_...`` as a valid "
            "SECRET_KEY; the placeholder pattern is not in the "
            "rejected case branches."
        )
        assert "known placeholder" in result.stderr, (
            f"entrypoint.sh did not emit the ``known placeholder`` "
            f"diagnostic for the docker-secret placeholder; "
            f"stderr={result.stderr!r}"
        )
        # The hint about the missing /run/secrets/secret_key file
        # must surface so the operator knows where to look.
        assert "Migrating to Docker secrets" in result.stderr, (
            "entrypoint.sh placeholder rejection does not point the "
            "operator at the runbook section; the operator has no "
            "discoverable hint that the secret file is missing."
        )
        # ``should-not-reach`` confirms exit fired.
        assert "should-not-reach" not in result.stdout

    def test_loader_preserves_special_characters(self, tmp_path: Path) -> None:
        """Special characters (URL-safe base64, punctuation) survive the load.

        Fernet keys are URL-safe base64 (``A-Za-z0-9_-=``).  TOTP
        encryption keys generated by ``Fernet.generate_key()`` end
        with ``=`` padding which a sloppy shell substitution
        (``eval``, double-quoted ``$VAR`` in the wrong context) could
        mangle.  Random bash special chars (``$``, `` ``, ``"``)
        are tested so a future use of ``$()`` or unquoted variable
        expansion in the helper surfaces here.
        """
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        # Use printf via Python directly to avoid any shell parsing.
        special = "k_AbC123-_=+/!@#$%^&*() with spaces and \"quotes\""
        (secrets_dir / "special_secret").write_text(special)
        loader = _extract_loader_function(secrets_dir)

        # We base64-encode the loaded value to assert on it without
        # going through any further shell quoting -- this isolates
        # the test from quoting bugs in the assertion harness itself.
        result = _run_loader_script(
            loader,
            (
                "_load_secret TEST_VAR special_secret\n"
                # ``printf '%s' "$TEST_VAR" | base64 -w0`` produces a
                # single-line base64 string we can compare exactly.
                "printf '%s' \"$TEST_VAR\" | base64 -w0\n"
                "echo \"\""  # newline so output is parseable
            ),
        )

        assert result.returncode == 0, result.stderr
        expected_b64 = base64.b64encode(special.encode("utf-8")).decode("ascii")
        assert expected_b64 in result.stdout, (
            f"loader mangled special characters; expected b64="
            f"{expected_b64!r}, got stdout={result.stdout!r}"
        )


# ──────────────────────────────────────────────────────────────────
# F-148: deploy/docker-compose.prod.yml secrets block
# ──────────────────────────────────────────────────────────────────


class TestProdComposeSecretsBlock:
    """The shared-mode prod override declares Docker secrets and grants access.

    Source-text checks complement the ``docker compose config``
    integration test below: text checks catch a misshapen secret
    declaration immediately, while the integration check catches
    structural bugs that pass the text scan but fail compose's
    schema validation.
    """

    @pytest.fixture(scope="class")
    def compose_text(self) -> str:
        """Return the full deploy/docker-compose.prod.yml source as a string."""
        return DOCKER_COMPOSE_PROD.read_text(encoding="utf-8")

    @pytest.mark.parametrize(
        "secret_name",
        [
            "secret_key",
            "postgres_password",
            "app_role_password",
            "totp_encryption_key",
        ],
    )
    def test_top_level_secrets_block_declares_secret(
        self, compose_text: str, secret_name: str,
    ) -> None:
        """Each required secret has a top-level declaration with a file path."""
        # Match the YAML block: ``<name>:`` followed by an indented
        # ``file: /opt/docker/shekel/secrets/<name>`` line.
        pattern = (
            rf"^  {secret_name}:\n"
            rf"\s+file:\s+/opt/docker/shekel/secrets/{secret_name}\b"
        )
        assert re.search(pattern, compose_text, re.MULTILINE), (
            f"deploy/docker-compose.prod.yml does not declare the "
            f"``{secret_name}`` secret with a file path under "
            f"/opt/docker/shekel/secrets/.  The runbook documents "
            "this exact path; a drift would silently break operator "
            "pre-flight commands."
        )

    @pytest.mark.parametrize(
        "secret_name",
        [
            "secret_key",
            "postgres_password",
            "app_role_password",
            "totp_encryption_key",
        ],
    )
    def test_app_service_grants_access_to_secret(
        self, compose_text: str, secret_name: str,
    ) -> None:
        """The app service's ``secrets:`` list grants access to every required secret."""
        # Capture the app service's body up to the next service or
        # top-level block.  We then scan inside it for the secret
        # name on a list item line.
        app_match = re.search(
            r"\n  app:\n(.+?)(?=\n  \w|\nnetworks:|\nsecrets:|\Z)",
            compose_text,
            re.DOTALL,
        )
        assert app_match is not None, (
            "deploy/docker-compose.prod.yml no longer defines an "
            "``app`` service block."
        )
        app_body = app_match.group(1)
        # The list item appears as ``      - secret_name`` (six
        # spaces of indent inside the secrets: block).  Match
        # whitespace tolerantly so a future indentation cleanup does
        # not break the test.
        assert re.search(rf"\n\s+-\s+{secret_name}\b", app_body), (
            f"app service in deploy/docker-compose.prod.yml does not "
            f"reference ``{secret_name}`` in its ``secrets:`` list; "
            "the secret will be declared at the top level but never "
            "mounted into /run/secrets/ for the container."
        )

    def test_db_service_grants_access_to_postgres_password(
        self, compose_text: str,
    ) -> None:
        """The db service mounts the postgres_password secret natively."""
        db_match = re.search(
            r"\n  db:\n(.+?)(?=\n  \w|\nnetworks:|\nsecrets:|\Z)",
            compose_text,
            re.DOTALL,
        )
        assert db_match is not None, "db service block missing"
        db_body = db_match.group(1)
        assert re.search(r"\n\s+-\s+postgres_password\b", db_body), (
            "db service does not mount the ``postgres_password`` "
            "docker secret; the postgres image cannot read /run/"
            "secrets/postgres_password and the POSTGRES_PASSWORD_FILE "
            "handoff will fail at container start."
        )

    def test_db_service_uses_postgres_password_file(
        self, compose_text: str,
    ) -> None:
        """``POSTGRES_PASSWORD_FILE`` is set in the db environment.

        The postgres image's docker-entrypoint.sh reads this env var
        natively to populate the superuser password from a file.
        """
        db_match = re.search(
            r"\n  db:\n(.+?)(?=\n  \w|\nnetworks:|\nsecrets:|\Z)",
            compose_text,
            re.DOTALL,
        )
        assert db_match is not None, "db service block missing"
        db_body = db_match.group(1)
        assert re.search(
            r"POSTGRES_PASSWORD_FILE:\s+/run/secrets/postgres_password",
            db_body,
        ), (
            "db service environment does not set "
            "POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password; "
            "the postgres image will not read the docker secret."
        )

    def test_db_service_overrides_postgres_password_to_empty(
        self, compose_text: str,
    ) -> None:
        """``POSTGRES_PASSWORD: ""`` is required for the postgres image's mutex.

        The postgres image's ``file_env`` helper errors when both
        POSTGRES_PASSWORD and POSTGRES_PASSWORD_FILE are non-empty
        (the "both set are exclusive" check).  Setting
        POSTGRES_PASSWORD to the empty string lets the file-backed
        branch run.
        """
        db_match = re.search(
            r"\n  db:\n(.+?)(?=\n  \w|\nnetworks:|\nsecrets:|\Z)",
            compose_text,
            re.DOTALL,
        )
        assert db_match is not None, "db service block missing"
        db_body = db_match.group(1)
        # Match either ``POSTGRES_PASSWORD: ""`` or
        # ``POSTGRES_PASSWORD: ''`` -- both are valid YAML for an
        # empty string.  The pattern is built explicitly via raw
        # strings so the pylint implicit-str-concat warning does not
        # fire on adjacent string literals.
        empty_yaml_pattern = r'POSTGRES_PASSWORD:\s+(""|' + "''" + r')'
        assert re.search(empty_yaml_pattern, db_body), (
            "db service environment does not override the base file's "
            "POSTGRES_PASSWORD interpolation to an empty string; the "
            "postgres image's file_env helper will see both env vars "
            "as non-empty and error with ``both ... are exclusive``."
        )


# ──────────────────────────────────────────────────────────────────
# F-148: docker compose merged config integration check
# ──────────────────────────────────────────────────────────────────


class TestProdComposeMergedConfig:
    """``docker compose config`` parses the secrets block successfully.

    Skipped on hosts without docker.  Catches a structural break in
    the secrets block that the source-text tests above might miss
    (e.g. a YAML indentation error that slips past the regex but
    fails the schema validator).
    """

    def test_docker_compose_config_succeeds_with_secrets_block(self) -> None:
        """The merged config parses and includes every declared secret."""
        if not _docker_available():
            pytest.skip("docker not available; cannot run docker compose config")

        env = {
            "PATH": "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin",
            "POSTGRES_PASSWORD": "test-postgres-password",
            "SECRET_KEY": "test-secret-key",
            "APP_ROLE_PASSWORD": "test-app-role-password",
            "SHEKEL_IMAGE_DIGEST": "sha256:" + "0" * 64,
        }
        result = subprocess.run(
            [
                "docker",
                "compose",
                "--env-file",
                "/dev/null",
                "-f",
                str(DOCKER_COMPOSE),
                "-f",
                str(DOCKER_COMPOSE_PROD),
                "config",
            ],
            capture_output=True,
            text=True,
            timeout=DOCKER_SUBPROCESS_TIMEOUT_S,
            check=False,
            cwd=str(REPO_ROOT),
            env=env,
        )
        assert result.returncode == 0, (
            "docker compose config failed for the merged base + "
            "shared-mode override:\n"
            f"  stdout: {result.stdout}\n"
            f"  stderr: {result.stderr}"
        )
        merged = result.stdout

        # Every required secret appears in the merged top-level
        # secrets: block.  Compose annotates each secret with a
        # ``name: shekel-prod_<name>`` line; we match on the file:
        # line which must reference /opt/docker/shekel/secrets/.
        for secret in (
            "secret_key",
            "postgres_password",
            "app_role_password",
            "totp_encryption_key",
        ):
            expected = f"file: /opt/docker/shekel/secrets/{secret}"
            assert expected in merged, (
                f"merged compose config does not include the {secret} "
                f"secret with file path /opt/docker/shekel/secrets/"
                f"{secret}; the shared-mode prod stack would not mount "
                "the file at /run/secrets/<name> for the container."
            )

        # The db service's POSTGRES_PASSWORD must be the empty
        # string in the merged config -- the override step that
        # bypasses the postgres image's mutex check.
        assert 'POSTGRES_PASSWORD: ""' in merged, (
            "merged compose config does not show POSTGRES_PASSWORD as "
            'an empty string ("") on the db service; the postgres '
            "image will see both POSTGRES_PASSWORD and "
            "POSTGRES_PASSWORD_FILE as non-empty and error at start."
        )

        # The app service must mount each required secret to
        # /run/secrets/<name>.  Compose's expanded form is
        # ``- source: <name>\n  target: /run/secrets/<name>``.
        for secret in (
            "secret_key",
            "postgres_password",
            "app_role_password",
            "totp_encryption_key",
        ):
            target_line = f"target: /run/secrets/{secret}"
            assert target_line in merged, (
                f"merged compose config does not mount {secret} at "
                f"/run/secrets/{secret} for any container; the "
                "entrypoint.sh _load_secret helper will not find the "
                "file at the documented path."
            )


# ──────────────────────────────────────────────────────────────────
# Documentation -- the runbook covers the docker-secrets posture
# ──────────────────────────────────────────────────────────────────


class TestRunbookDocumentsDockerSecretsPosture:
    """``docs/runbook_secrets.md`` covers the file-backed posture.

    Operator-documentation check: the runbook is the source of truth
    for migration and rotation procedures.  A code change that adds
    docker-secrets support without runbook coverage leaves operators
    with no procedure for the new posture.
    """

    @pytest.fixture(scope="class")
    def runbook_text(self) -> str:
        """Return the full docs/runbook_secrets.md source as a string."""
        return RUNBOOK_SECRETS.read_text(encoding="utf-8")

    def test_runbook_describes_two_postures(self, runbook_text: str) -> None:
        """The runbook explicitly contrasts env-backed and file-backed postures."""
        assert "Posture 1" in runbook_text and "Posture 2" in runbook_text, (
            "runbook_secrets.md does not split the two postures into "
            "named sections; operators cannot easily decide which "
            "posture they are running."
        )
        assert "env-backed" in runbook_text.lower(), (
            "runbook does not name the env-backed posture explicitly"
        )
        assert "file-backed" in runbook_text.lower(), (
            "runbook does not name the file-backed posture explicitly"
        )

    def test_runbook_documents_migration_procedure(
        self, runbook_text: str,
    ) -> None:
        """A concrete migration procedure appears under a section header."""
        assert "Migrating to Docker secrets" in runbook_text, (
            "runbook does not include a ``Migrating to Docker secrets`` "
            "section; operators have no documented step-by-step path "
            "from env-backed to file-backed."
        )
        # The procedure must reference the canonical secrets
        # directory path.  A drift between this path and the compose
        # file's secret declarations would silently break operators
        # following the runbook.
        assert "/opt/docker/shekel/secrets" in runbook_text, (
            "runbook migration procedure does not reference "
            "/opt/docker/shekel/secrets/; operators following the "
            "runbook would not know where to put the secret files."
        )

    def test_runbook_secret_inventory_lists_app_role_password(
        self, runbook_text: str,
    ) -> None:
        """The Secret Inventory table includes APP_ROLE_PASSWORD.

        Pre-C-38 the inventory listed three secrets; C-13 added
        APP_ROLE_PASSWORD without updating the inventory.  C-38
        closes that gap.  A regression that drops the row would
        re-create the documentation hole the audit surfaced.
        """
        # Find the inventory table -- a heading-3 ``## Secret
        # Inventory`` followed by a markdown table.  The table rows
        # have ``| `VAR` |`` shape.
        inventory_match = re.search(
            r"## Secret Inventory(.+?)## ", runbook_text, re.DOTALL,
        )
        assert inventory_match is not None, "Secret Inventory section missing"
        table_body = inventory_match.group(1)
        assert "`APP_ROLE_PASSWORD`" in table_body, (
            "Secret Inventory table does not list APP_ROLE_PASSWORD; "
            "the C-13 secret is undocumented in the inventory and "
            "operators rebuilding from disaster would miss it."
        )
