"""Deployment-layer assertions for Commit C-38.

Covers audit findings F-108 (`.env.dev` references nonexistent path),
F-109 (`.env.example` carries a functional dev `POSTGRES_PASSWORD`),
F-112 (DevConfig missing pragma comment about HTTP-localhost cookie
posture), and F-148 (env-only secrets posture migrated to operator-
optional Docker secrets).

Tests fall into three categories:

1. **Filesystem state** -- the files the audit reviewer inspects on
   disk are in the expected shape (.env.dev removed, .env.example
   sanitized, .gitignore covers .env.dev).
2. **Source-level structure** -- the production source files
   (`app/config.py`, `entrypoint.sh`, `deploy/docker-compose.prod.yml`)
   carry the expected hooks for the file-backed secrets posture.
3. **Behavioral runtime checks on the entrypoint loader** -- the
   `_load_secret` shell function is extracted from entrypoint.sh,
   rewritten to point at a test-local secrets directory, and
   exercised as a bash script.  This proves the loader actually
   reads, falls back, rejects empty files, and preserves special
   characters as the audit plan requires (the file-text-only
   assertions in category 1 cannot prove behaviour).

Style note: this file follows the test_seed_credential_hygiene.py
pattern from Commit C-34 (file-text + behaviour split, fixtures via
Path constants, parametrize for repetitive coverage).
"""
from __future__ import annotations

import base64
import re
import shutil
import subprocess
from importlib import reload
from pathlib import Path

import pytest

from app import config as config_module


REPO_ROOT = Path(__file__).resolve().parents[2]

# ── Files under assertion ──────────────────────────────────────────
ENV_EXAMPLE = REPO_ROOT / ".env.example"
ENV_DEV = REPO_ROOT / ".env.dev"
GITIGNORE = REPO_ROOT / ".gitignore"
APP_CONFIG = REPO_ROOT / "app" / "config.py"
ENTRYPOINT_SCRIPT = REPO_ROOT / "entrypoint.sh"
DOCKER_COMPOSE = REPO_ROOT / "docker-compose.yml"
DOCKER_COMPOSE_PROD = REPO_ROOT / "deploy" / "docker-compose.prod.yml"
RUNBOOK_SECRETS = REPO_ROOT / "docs" / "runbook_secrets.md"
VERIFY_BACKUP_SCRIPT = REPO_ROOT / "scripts" / "verify_backup.sh"

# The sentinel token shipped in .env.example's DATABASE_URL and
# TEST_DATABASE_URL templates.  Mirrors ``_DATABASE_URL_SENTINEL`` in
# app/config.py; cross-referenced here as a string literal so a
# regression that renames the constant on one side without the other
# surfaces as a test failure (rather than as a silent acceptance of
# the leaked default at runtime).
ENV_EXAMPLE_DB_URL_SENTINEL = "REPLACE-ME-WITH-YOUR-POSTGRES-PASSWORD"

# Length of a SECRET_KEY generated by ``token_hex(32)`` -- the
# documented production form.  Used by the loader-behaviour fixture
# below so the synthetic value matches the real one's shape.
SECRET_KEY_HEX_BYTES = 64

# Subprocess timeout for bash invocations of the extracted loader.
# The loader does no I/O beyond a single file read; 5s is generous.
BASH_TEST_TIMEOUT_S = 5

# Subprocess timeout for ``docker compose config`` invocations.
DOCKER_SUBPROCESS_TIMEOUT_S = 60


def _docker_available() -> bool:
    """Return True when ``docker`` is on PATH and ``docker info`` succeeds."""
    if shutil.which("docker") is None:
        return False
    try:
        result = subprocess.run(
            ["docker", "info"],
            capture_output=True,
            text=True,
            timeout=DOCKER_SUBPROCESS_TIMEOUT_S,
            check=False,
        )
    except (subprocess.TimeoutExpired, OSError):
        return False
    return result.returncode == 0


# ──────────────────────────────────────────────────────────────────
# F-108: .env.dev removed from the branch
# ──────────────────────────────────────────────────────────────────


class TestEnvDevRemoved:
    """``.env.dev`` is gone from the working tree and gitignored.

    The audit verified that ``.env.dev:1`` referenced
    ``FLASK_APP=src/flask_app/app.py`` -- a path that has never existed
    in this repo.  The C-38 fix deletes the file outright and adds a
    ``.gitignore`` entry so an operator who recreates a local
    ``.env.dev`` for any reason cannot accidentally commit it.
    """

    def test_env_dev_file_does_not_exist(self) -> None:
        """``.env.dev`` is absent from the working tree."""
        assert not ENV_DEV.exists(), (
            f".env.dev still present at {ENV_DEV}; the F-108 cleanup did not "
            "complete (the file referenced a nonexistent FLASK_APP path "
            "and is documented for deletion in remediation Commit C-38)."
        )

    def test_gitignore_covers_env_dev(self) -> None:
        """``.gitignore`` lists ``.env.dev`` so a recreated copy stays untracked."""
        text = GITIGNORE.read_text(encoding="utf-8")
        # We require an exact entry on a line by itself rather than a
        # broader glob match -- the audit's ask is the literal
        # ``.env.dev`` filename.  ``re.MULTILINE`` so ``^`` matches the
        # start of any line.
        assert re.search(r"^\.env\.dev\s*$", text, re.MULTILINE), (
            ".gitignore does not list ``.env.dev`` on its own line; "
            "an operator recreating a local .env.dev (e.g. for a test "
            "Flask entrypoint) could accidentally commit it (F-108)."
        )


# ──────────────────────────────────────────────────────────────────
# F-109: .env.example sanitized of the functional dev password
# ──────────────────────────────────────────────────────────────────


class TestEnvExampleSanitized:
    """``.env.example`` ships an empty ``POSTGRES_PASSWORD`` placeholder."""

    @pytest.fixture(scope="class")
    def env_example_text(self) -> str:
        """Return the full .env.example source as a string."""
        return ENV_EXAMPLE.read_text(encoding="utf-8")

    def test_postgres_password_field_is_empty(self, env_example_text: str) -> None:
        """``POSTGRES_PASSWORD=`` is empty by default in .env.example.

        Asserts on a line-anchored exact match.  A regression to
        ``POSTGRES_PASSWORD=shekel_pass`` (or any other non-empty
        functional default) would re-introduce the F-109 finding: a
        copy-paste of .env.example would carry a working dev password
        into a production environment.  The base
        ``docker-compose.yml`` then reuses that password in
        DATABASE_URL, so the audit treats it as a leaked credential
        even though the file is committed as a template.
        """
        # Match the exact assignment with nothing after the ``=``
        # except optional whitespace.  This catches both the original
        # ``POSTGRES_PASSWORD=shekel_pass`` regression AND a sneakier
        # ``POSTGRES_PASSWORD= `` (trailing space) form that bash
        # would still treat as empty but a copy-paste would not.
        assert re.search(
            r"^POSTGRES_PASSWORD=\s*$",
            env_example_text,
            re.MULTILINE,
        ), (
            ".env.example does not ship POSTGRES_PASSWORD with an "
            "empty value; F-109 regression -- the file would carry a "
            "functional dev password into production for any operator "
            "who copies it verbatim to .env."
        )

    def test_postgres_password_section_documents_generation(
        self, env_example_text: str,
    ) -> None:
        """The POSTGRES_PASSWORD section explains how to generate a value.

        Without an inline generation command the operator falls back
        to whatever they had in their previous .env, which on a fresh
        checkout means they invent a weak default (``password123``).
        The C-34 SECRET_KEY block established the precedent that
        every required secret in this file ships its own generation
        command; this test enforces that POSTGRES_PASSWORD now
        follows the same pattern.
        """
        # Find the POSTGRES_PASSWORD assignment and read backwards
        # through the comment block above it.  Comment lines are
        # ``#`` prefixed and immediately precede the assignment.
        match = re.search(
            r"((?:^#[^\n]*\n)+)^POSTGRES_PASSWORD=\s*$",
            env_example_text,
            re.MULTILINE,
        )
        assert match is not None, (
            ".env.example POSTGRES_PASSWORD assignment is not preceded "
            "by a comment block; the operator has no inline guidance "
            "for generating a value."
        )
        comment_block = match.group(1)
        # The recommended generation commands in the docs/runbook are
        # ``secrets.token_urlsafe(32)`` and ``openssl rand``.  We
        # accept either being mentioned -- the assertion is that SOME
        # generation hint exists, not which.
        assert "token_urlsafe" in comment_block or "openssl rand" in comment_block, (
            ".env.example POSTGRES_PASSWORD comment block lists no "
            "generation command; an operator copying the template "
            "would fall back to inventing a weak default."
        )

    def test_postgres_password_block_references_docker_secrets_path(
        self, env_example_text: str,
    ) -> None:
        """The POSTGRES_PASSWORD block points operators at Docker secrets.

        Defense-in-depth note: even if an operator forgets to read
        the runbook, the .env.example block tells them about the
        file-backed posture so they can opt in.
        """
        match = re.search(
            r"((?:^#[^\n]*\n)+)^POSTGRES_PASSWORD=\s*$",
            env_example_text,
            re.MULTILINE,
        )
        assert match is not None
        comment_block = match.group(1)
        # The docker-secrets escape hatch must be discoverable from
        # the .env.example comment block -- not just from the runbook.
        assert "docker secret" in comment_block.lower() or (
            "/opt/docker/shekel/secrets" in comment_block
            and "F-148" in comment_block
        ), (
            ".env.example POSTGRES_PASSWORD comment block does not "
            "mention the Docker secrets opt-in (audit finding F-148 / "
            "Commit C-38).  Operators who read only this file will "
            "not discover the file-backed posture."
        )


# ──────────────────────────────────────────────────────────────────
# F-109 (URI form): .env.example DATABASE_URL templates use a sentinel
# ──────────────────────────────────────────────────────────────────


class TestEnvExampleUriTemplatesSanitized:
    """``.env.example`` no longer embeds ``shekel_pass`` in connection URIs.

    The standalone ``POSTGRES_PASSWORD=`` line was sanitised in C-38
    (covered by ``TestEnvExampleSanitized`` above).  The DATABASE_URL
    and TEST_DATABASE_URL templates that EMBED the same password
    inside a connection URI are the second F-109 surface, closed by
    the C-38 follow-up Issue 3 work documented in
    ``docs/audits/security-2026-04-15/c-38-followups.md``.

    These tests assert the URI lines never contain the historical
    ``shekel_pass`` default and always contain the sentinel token
    that ``app/config.py:_reject_sentinel`` rejects at load time.
    The two together form a closed feedback loop: an operator who
    edits the URI in .env to a real password keeps the application
    running; an operator who copies .env.example verbatim is caught
    at config load time with a clear app-level error.
    """

    @pytest.fixture(scope="class")
    def env_example_text(self) -> str:
        """Return the full .env.example source as a string."""
        return ENV_EXAMPLE.read_text(encoding="utf-8")

    @pytest.mark.parametrize(
        "var_name",
        ["DATABASE_URL", "TEST_DATABASE_URL"],
    )
    def test_uri_template_does_not_embed_shekel_pass(
        self, env_example_text: str, var_name: str,
    ) -> None:
        """The URI line for ``var_name`` does not contain ``shekel_pass``.

        Anchored on the start-of-line ``<var_name>=`` assignment so
        the assertion targets the URI template specifically and does
        not also reject the historical reference in the comment
        block above (audit trail context is acceptable in comments;
        a functional credential in the assignment is not).
        """
        # Match the assignment line up to end-of-line.  The pattern
        # then asserts ``shekel_pass`` is NOT present anywhere in
        # the captured assignment.
        match = re.search(
            rf"^{var_name}=([^\n]*)$",
            env_example_text,
            re.MULTILINE,
        )
        assert match is not None, (
            f".env.example does not define ``{var_name}=`` on a line "
            "by itself; the template URI documenting password-auth is "
            "missing entirely.  An operator with no example to copy "
            "would invent one and likely embed a weak default."
        )
        assignment = match.group(1)
        assert "shekel_pass" not in assignment, (
            f".env.example ``{var_name}`` URI still embeds "
            "``shekel_pass`` (audit finding F-109 / Commit C-38 "
            "follow-up Issue 3 regression).  The URI must use the "
            f"sentinel token ``{ENV_EXAMPLE_DB_URL_SENTINEL}`` so "
            "app/config.py:_reject_sentinel fires when an operator "
            "copies the template without substituting a real password."
        )

    @pytest.mark.parametrize(
        "var_name",
        ["DATABASE_URL", "TEST_DATABASE_URL"],
    )
    def test_uri_template_carries_sentinel(
        self, env_example_text: str, var_name: str,
    ) -> None:
        """The URI line for ``var_name`` carries the sentinel token.

        Without the sentinel, the C-38 follow-up rejection helper
        has nothing to match against -- an operator who copies the
        template would silently authenticate against whatever
        password they happen to have in their dev database.  The
        sentinel is the load-bearing piece that makes the
        unsubstituted-template failure mode loud rather than silent.
        """
        match = re.search(
            rf"^{var_name}=([^\n]*)$",
            env_example_text,
            re.MULTILINE,
        )
        assert match is not None
        assignment = match.group(1)
        assert ENV_EXAMPLE_DB_URL_SENTINEL in assignment, (
            f".env.example ``{var_name}`` URI does not embed the "
            f"sentinel token ``{ENV_EXAMPLE_DB_URL_SENTINEL}``; "
            "app/config.py:_reject_sentinel cannot enforce the "
            "copy-paste-without-substitution failure mode the C-38 "
            "follow-up Issue 3 work introduces."
        )

    def test_database_section_documents_substitution(
        self, env_example_text: str,
    ) -> None:
        """Operator is told to replace the sentinel before booting.

        The audit-trail comment block above the DATABASE_URL block
        must explicitly call out the substitution -- otherwise an
        operator who skims the file may not realise the URI is a
        template requiring an edit.  We accept any reasonable hint
        (``REPLACE``, ``substitute``, etc.) tied to the sentinel
        token spelling, so a future copyedit that rewords the
        guidance does not break the assertion.
        """
        # Capture the comment block (one or more ``#``-prefixed
        # lines) that precedes the DATABASE_URL assignment.
        match = re.search(
            r"((?:^#[^\n]*\n)+)^DATABASE_URL=",
            env_example_text,
            re.MULTILINE,
        )
        assert match is not None, (
            ".env.example DATABASE_URL assignment is not preceded by "
            "an explanatory comment block; the operator has no inline "
            "context for the sentinel substitution requirement."
        )
        comment_block = match.group(1)
        # The sentinel must be named in the comment so the operator
        # can map their .env's literal value to the documented one.
        assert ENV_EXAMPLE_DB_URL_SENTINEL in comment_block, (
            ".env.example DATABASE_URL comment block does not name "
            f"the sentinel token ``{ENV_EXAMPLE_DB_URL_SENTINEL}``; "
            "an operator who hits the _reject_sentinel ValueError "
            "would have to grep the codebase to discover what the "
            "token means."
        )


# ──────────────────────────────────────────────────────────────────
# F-109 (script form): scripts/verify_backup.sh removed shekel_pass
# ──────────────────────────────────────────────────────────────────


class TestVerifyBackupScriptCredentialHygiene:
    """``scripts/verify_backup.sh`` no longer hard-codes ``shekel_pass``.

    Two F-109 surfaces in the script (documented in
    ``docs/audits/security-2026-04-15/c-38-followups.md`` Issue 3
    "Related cleanup"):

    1. Line 236 (pre-C-38-followup): ``|| echo "shekel_pass"``
       fallback fires when the live DB container does not expose
       POSTGRES_PASSWORD, silently constructing a leaked-credential
       URL.  Replaced with a ``get_db_password()`` helper that exits
       1 with a clear diagnostic.
    2. Line 243 (pre-C-38-followup): unconditional
       ``shekel_pass`` URL in the dev branch, ignoring the
       ``db_password`` variable resolved in the prod branch.
       Refactored to share the helper's output across both branches.

    Text-level assertions below pair with the behavioural class
    further down that proves the helper's failure mode.
    """

    @pytest.fixture(scope="class")
    def script_text(self) -> str:
        """Return the full verify_backup.sh source as a string."""
        return VERIFY_BACKUP_SCRIPT.read_text(encoding="utf-8")

    def test_script_does_not_embed_shekel_pass_in_uri(
        self, script_text: str,
    ) -> None:
        """No literal ``:shekel_pass@`` credential fragment remains.

        Anchored on the URI fragment ``user:password@host`` so the
        assertion targets functional credentials specifically.  The
        word ``shekel_pass`` still appears in the audit-trail
        comments naming the historical default -- those are
        deliberate and must not be rejected.
        """
        assert ":shekel_pass@" not in script_text, (
            "scripts/verify_backup.sh still embeds ``:shekel_pass@`` "
            "as a literal credential fragment in a connection URI "
            "(audit finding F-109 / Commit C-38 follow-up Issue 3 "
            "regression).  Resolve the password via the "
            "``get_db_password`` helper instead of hard-coding the "
            "historical leaked default."
        )

    def test_script_does_not_fall_back_to_shekel_pass(
        self, script_text: str,
    ) -> None:
        """No EXECUTABLE ``|| echo "shekel_pass"`` fallback remains.

        The historical pattern was
        ``$(docker exec ... printenv POSTGRES_PASSWORD || echo "shekel_pass")``.
        The ``|| echo`` fallback silently constructed a leaked-
        credential URL when the live DB container did not expose
        POSTGRES_PASSWORD -- a misconfiguration that must surface
        as a hard failure, not as a working connection to a
        leaked-credential database.

        Audit-trail comments that QUOTE the historical pattern (for
        documentation of why the fix exists) are deliberate and
        must not be flagged.  The line-by-line scan below skips
        comment-only lines so those references survive while a
        regression in executable code is still caught.
        """
        pattern = re.compile(r"\|\|\s*echo\s+[\"']?shekel_pass[\"']?")
        for line_no, line in enumerate(script_text.splitlines(), start=1):
            stripped = line.lstrip()
            # Skip comment-only lines.  Inline comments after
            # executable code (e.g. ``foo  # bar``) are extremely
            # rare in shell and the audit-trail comments use the
            # full-line form, so a strict "starts with #" filter is
            # sufficient.  An executable line that has a trailing
            # comment with a quoted ``|| echo "shekel_pass"`` is
            # not anticipated; if such a line is ever introduced,
            # the failure mode is "rejected with a false positive"
            # which the developer can resolve by lifting the
            # comment to its own line.
            if stripped.startswith("#"):
                continue
            assert not pattern.search(line), (
                f"scripts/verify_backup.sh line {line_no} still "
                f"falls back to ``shekel_pass`` (audit F-109).  "
                f"Line: {line!r}.  Replace the fallback with a hard "
                "exit via the ``get_db_password`` helper."
            )

    def test_script_defines_get_db_password(self, script_text: str) -> None:
        """The ``get_db_password()`` function is defined in the script.

        Source-level assertion that the helper exists -- a refactor
        that inlines the resolution back into ``run_integrity_checks``
        would weaken the encapsulation and reopen the fallback
        surface this test class closes.
        """
        assert re.search(
            r"^get_db_password\(\)\s*\{",
            script_text,
            re.MULTILINE,
        ), (
            "scripts/verify_backup.sh does not define a "
            "``get_db_password`` function; the encapsulation that "
            "the C-38 follow-up introduces has been lost."
        )

    def test_get_db_password_returns_nonzero_on_empty(
        self, script_text: str,
    ) -> None:
        """The helper signals failure with ``return 1`` (or ``exit 1``).

        The load-bearing behaviour: when POSTGRES_PASSWORD is not
        discoverable, the helper must propagate failure to the
        caller's ``set -e`` so the script exits before constructing
        a connection URL.  ``return`` is preferred (function scope)
        but ``exit 1`` would also work, so accept either.
        """
        # Extract the function body and assert it contains a
        # non-zero return or exit on the empty-password branch.
        match = re.search(
            r"^get_db_password\(\)\s*\{(.*?)^\}",
            script_text,
            re.MULTILINE | re.DOTALL,
        )
        assert match is not None, (
            "Could not extract the body of ``get_db_password`` from "
            "scripts/verify_backup.sh; the function definition is "
            "malformed or missing."
        )
        body = match.group(1)
        # Look for the empty-check branch followed by a non-zero
        # return / exit.  We accept either ordering.
        assert re.search(r"return\s+[1-9]\d*\b|exit\s+[1-9]\d*\b", body), (
            "``get_db_password`` does not return or exit non-zero on "
            "the empty-password branch; the caller's ``set -e`` "
            "would not propagate the failure and the script would "
            "construct a connection URL with an empty password."
        )

    def test_run_integrity_checks_uses_shared_db_password(
        self, script_text: str,
    ) -> None:
        """Both branches of ``run_integrity_checks`` use ``${db_password}``.

        The pre-C-38-followup script resolved the password only in
        the prod branch and then unconditionally hard-coded
        ``shekel_pass`` in the dev branch.  The fix is to resolve
        once via the helper and share the resolved value across
        both branches.  This test locks in the shared usage so a
        future refactor cannot accidentally reintroduce a hard-coded
        password in either branch.
        """
        # Extract the run_integrity_checks function body.
        match = re.search(
            r"^run_integrity_checks\(\)\s*\{(.*?)^\}",
            script_text,
            re.MULTILINE | re.DOTALL,
        )
        assert match is not None, (
            "Could not extract the body of ``run_integrity_checks`` "
            "from scripts/verify_backup.sh."
        )
        body = match.group(1)
        # Both DATABASE_URL constructions must reference db_password.
        prod_branch_uses_var = re.search(
            r"DATABASE_URL=postgresql://[^@\n]*\$\{db_password\}@",
            body,
        )
        dev_branch_uses_var = re.search(
            r"verify_url=\"postgresql://[^@\n]*\$\{db_password\}@",
            body,
        )
        assert prod_branch_uses_var, (
            "``run_integrity_checks`` prod-branch DATABASE_URL does "
            "not reference ``${db_password}``; the resolved password "
            "is being shadowed or replaced with a literal."
        )
        assert dev_branch_uses_var, (
            "``run_integrity_checks`` dev-branch verify_url does "
            "not reference ``${db_password}``; the dev branch is "
            "still constructing a URL with a hard-coded password "
            "(audit F-109 regression)."
        )


def _extract_get_db_password_function(stub_container: str) -> str:
    """Return the bash source of ``get_db_password`` from verify_backup.sh.

    The function is returned verbatim; the caller is expected to
    wrap it in a harness script that defines ``log``, sets
    ``DB_CONTAINER=stub_container``, and stubs ``docker`` to
    simulate ``docker exec`` returning a chosen value.

    Args:
        stub_container: The DB_CONTAINER value the test harness
            will set.  Returned by reference for documentation
            purposes; the function body itself reads
            ``${DB_CONTAINER}`` dynamically so no source rewrite is
            needed.

    Returns:
        The full ``get_db_password() { ... }`` source as a string.
    """
    del stub_container  # informational arg only -- see docstring
    text = VERIFY_BACKUP_SCRIPT.read_text(encoding="utf-8")
    match = re.search(
        r"^(get_db_password\(\)\s*\{.*?\n^\})",
        text,
        re.MULTILINE | re.DOTALL,
    )
    if match is None:
        pytest.fail(
            "Could not extract get_db_password from "
            "scripts/verify_backup.sh; the function must start with "
            "``get_db_password() {`` at column 0 and end with "
            "``}`` at column 0."
        )
    return match.group(1)


def _run_get_db_password_harness(
    docker_stub_body: str,
) -> subprocess.CompletedProcess[str]:
    """Run a bash script that exercises ``get_db_password``.

    The harness defines a ``docker`` function whose body the caller
    supplies, then sources the extracted production
    ``get_db_password`` and tries to capture its output into
    ``db_password``.  ``set -euo pipefail`` mirrors the production
    script's ``set`` flags so the command-substitution propagation
    of non-zero exits is exercised exactly as in production.

    Args:
        docker_stub_body: Bash body inserted into a stub ``docker``
            function.  Typical contents: ``return 0`` to simulate
            empty output, or ``echo "value"`` to simulate a real
            POSTGRES_PASSWORD lookup.

    Returns:
        The ``subprocess.CompletedProcess`` from running the
        harness via ``bash -c``.  The caller asserts on returncode,
        stdout (which carries the captured password on success),
        and stderr (which carries the diagnostic on failure).
    """
    get_db_password_src = _extract_get_db_password_function("fake-db-container")
    harness = (
        "#!/bin/bash\n"
        "set -euo pipefail\n"
        # Mirror the production script's ``log`` helper so the
        # extracted function's log calls do not fail with "command
        # not found".
        "log() {\n"
        '    local level="$1"\n'
        "    shift\n"
        "    echo \"[stub-log] [${level}] $*\"\n"
        "}\n"
        # DB_CONTAINER is read by get_db_password.  The value does
        # not matter (the stub docker function ignores it) but it
        # must be set or ``${DB_CONTAINER}`` expansion would trip
        # the ``set -u`` flag.
        'DB_CONTAINER="fake-db-container"\n'
        # Stub docker so the function's ``docker exec ... printenv``
        # call routes through here instead of the real binary.
        "docker() {\n"
        f"    {docker_stub_body}\n"
        "}\n"
        # Insert the production function under test.
        f"{get_db_password_src}\n"
        # Capture the function's output into a variable.  ``set -e``
        # propagates a non-zero exit from the command substitution
        # to the harness; we therefore wrap the invocation in an
        # ``if`` to keep going so the test can inspect the exit
        # code rather than aborting the harness.
        "if db_password=$(get_db_password); then\n"
        '    echo "OK: db_password=${db_password}"\n'
        "    exit 0\n"
        "else\n"
        "    rc=$?\n"
        '    echo "FAIL: rc=${rc}"\n'
        "    exit ${rc}\n"
        "fi\n"
    )
    return subprocess.run(
        ["bash", "-c", harness],
        capture_output=True,
        text=True,
        timeout=BASH_TEST_TIMEOUT_S,
        check=False,
    )


class TestVerifyBackupScriptGetDbPasswordBehaviour:
    """Run the extracted ``get_db_password`` against stubbed docker.

    The script-level subprocess tests below prove the helper's
    failure mode at the bash layer -- a stubbed ``docker`` function
    simulates the ``docker exec ... printenv POSTGRES_PASSWORD``
    failure modes the live runtime would experience.  The text-level
    tests above prove the function is wired correctly; these prove
    it actually exits with the right code and message.
    """

    def test_returns_password_when_docker_exec_succeeds(self) -> None:
        """A non-empty stub return value is echoed by the helper."""
        result = _run_get_db_password_harness(
            docker_stub_body="echo 'real-postgres-secret'",
        )
        assert result.returncode == 0, (
            f"get_db_password failed when docker stub returned a "
            f"real value: stdout={result.stdout!r}, "
            f"stderr={result.stderr!r}"
        )
        # The harness echoes "OK: db_password=<value>" on success.
        assert "OK: db_password=real-postgres-secret" in result.stdout, (
            f"get_db_password did not echo the stub-supplied "
            f"password verbatim; stdout={result.stdout!r}"
        )

    def test_exits_nonzero_when_docker_exec_returns_empty(self) -> None:
        """An empty docker-exec output triggers a hard failure.

        The load-bearing assertion of the C-38 follow-up.  Without
        this branch firing, the script would build a connection
        URL with an empty password and surface a misleading
        Postgres "password authentication failed" error.
        """
        result = _run_get_db_password_harness(
            # Simulate ``docker exec ... printenv POSTGRES_PASSWORD``
            # returning success with no output -- the most realistic
            # production failure mode (container running but env
            # channel scrubbed).
            docker_stub_body="return 0",
        )
        assert result.returncode != 0, (
            "get_db_password accepted an empty docker exec output "
            "and built a URL with an empty password; the audit "
            "F-109 follow-up failure mode is not enforced."
        )

    def test_exits_nonzero_when_docker_exec_itself_fails(self) -> None:
        """A non-zero docker exec also triggers the empty-password branch.

        The function uses ``|| password=""`` to fold a failing
        ``docker exec`` into the same empty-password branch.  This
        is the right behaviour: an unreachable container is just
        as bad as one with a missing env var.
        """
        result = _run_get_db_password_harness(
            # Simulate ``docker exec`` failing entirely (e.g.
            # container died, daemon unreachable).
            docker_stub_body="return 1",
        )
        assert result.returncode != 0, (
            "get_db_password accepted a failing docker exec and "
            "did not propagate the failure; an unreachable "
            "container should be treated as missing-password too."
        )

    def test_failure_diagnostic_refuses_shekel_pass_fallback(self) -> None:
        """The error message points at the historical fallback.

        Operator-facing context: the diagnostic must make it
        obvious WHY the script refuses to proceed.  Without this
        wording, an operator might assume the script is buggy and
        patch it back to the ``|| echo "shekel_pass"`` form.  The
        explicit "refusing to fall back" phrasing names the
        failure mode and points at the audit finding.
        """
        result = _run_get_db_password_harness(
            docker_stub_body="return 0",
        )
        # log() writes its full prefix to stdout; in get_db_password
        # we redirect log() calls to stderr.  Either stream carries
        # the message in practice -- assert on the combined output
        # so a future log-redirect refactor does not break us.
        combined = result.stdout + result.stderr
        assert "POSTGRES_PASSWORD" in combined, (
            f"get_db_password failure diagnostic does not name "
            f"POSTGRES_PASSWORD; the operator has no obvious clue "
            f"where to look.  stdout={result.stdout!r}, "
            f"stderr={result.stderr!r}"
        )
        # The diagnostic should mention the refusal to fall back so
        # an operator does not patch the script back to the unsafe
        # form.  We accept either ``refus`` (refuse/refusing/...) or
        # the explicit audit finding number.
        assert "refus" in combined.lower() or "F-109" in combined, (
            f"get_db_password failure diagnostic does not explain "
            f"why the script refuses to construct a URL with the "
            f"historical default; an operator may patch the script "
            f"back to the unsafe ``|| echo \"shekel_pass\"`` form. "
            f"stdout={result.stdout!r}, stderr={result.stderr!r}"
        )


# ──────────────────────────────────────────────────────────────────
# F-112: DevConfig pragma comment for HTTP-localhost cookie posture
# ──────────────────────────────────────────────────────────────────


class TestProdConfigRejectsDockerSecretPlaceholder:
    """ProdConfig rejects ``replaced_by_docker_secret`` as a SECRET_KEY value.

    Defense-in-depth complement to the entrypoint.sh case statement:
    the entrypoint catches the placeholder before any deploy script
    runs; this Python-side check catches it again at Flask config
    load time.  Both fire at different layers of the boot sequence so
    a regression in either one is caught by the other.
    """

    @pytest.mark.parametrize(
        "placeholder_value",
        [
            # Exact match -- the placeholder set membership branch.
            "replaced_by_docker_secret",
            # Long-enough padding to clear the 32-char length floor;
            # the ``startswith`` branch is what catches it.
            "replaced_by_docker_secret_padded_to_be_long_enough_to_pass_length_check",
        ],
        ids=["exact-match", "padded-long"],
    )
    def test_prodconfig_rejects_docker_secret_placeholder(
        self, placeholder_value: str, monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """ProdConfig refuses to load when SECRET_KEY is the documented placeholder.

        Both the exact placeholder and longer ``startswith`` variants
        must surface the ``known placeholder`` error.  Without these
        rejections, an operator on Posture 2 whose docker secret file
        is missing or unreadable would boot under the publicly-known
        placeholder value -- exactly the F-148 weakness Commit C-38
        is closing.
        """
        # ProdConfig reads SECRET_KEY at class-attribute time
        # (BaseConfig.SECRET_KEY = os.getenv(...)) so we must set the
        # env var BEFORE the module reload.  Use monkeypatch so any
        # exception in the test body still rolls the env back.
        monkeypatch.setenv("SECRET_KEY", placeholder_value)
        monkeypatch.setenv("DATABASE_URL", "postgresql://x:x@x:5432/x")
        monkeypatch.setenv("RATELIMIT_STORAGE_URI", "redis://x:6379/0")
        try:
            reload(config_module)
            with pytest.raises(ValueError, match="known placeholder"):
                config_module.ProdConfig()
        finally:
            # Reload once more after the test so the next test that
            # touches config_module sees the original env-driven
            # class attributes.
            reload(config_module)


class TestDevConfigPragma:
    """``DevConfig`` carries an explicit pragma for its cookie posture.

    The audit-verified gap: DevConfig inherits Flask's defaults for
    ``SESSION_COOKIE_SECURE`` (False), ``SESSION_COOKIE_SAMESITE``
    (None), and ``SESSION_COOKIE_HTTPONLY`` (True), but does not
    document why it diverges from ProdConfig's hardened defaults.  An
    operator skim-reading config.py would see DevConfig as a hole.
    The C-38 pragma makes the rationale explicit so a future reader
    -- or a future audit -- understands the divergence is deliberate.
    """

    @pytest.fixture(scope="class")
    def config_text(self) -> str:
        """Return the full app/config.py source as a string."""
        return APP_CONFIG.read_text(encoding="utf-8")

    def test_devconfig_class_has_substantive_docstring(
        self, config_text: str,
    ) -> None:
        """DevConfig's docstring covers the cookie-flag pragma.

        Match the DevConfig class header and isolate its body before
        the next class or end-of-file.  The docstring must mention
        the specific cookie flags that are NOT set, not just a
        generic "dev mode" line.
        """
        # Capture from "class DevConfig" up to the next "class " or
        # end of file.  ``re.DOTALL`` lets ``.`` cross newlines.
        match = re.search(
            r"class DevConfig\(BaseConfig\):(.+?)(?=\nclass |\Z)",
            config_text,
            re.DOTALL,
        )
        assert match is not None, "DevConfig class not found in app/config.py"
        body = match.group(1)
        # Must mention the specific finding ID so a future audit
        # reviewer can match the pragma to the audit catalog.
        assert "F-112" in body, (
            "DevConfig docstring does not reference audit finding F-112; "
            "future audit reviewers cannot match the pragma to the "
            "audit catalog."
        )
        # Must mention the load-bearing cookie flag the pragma is
        # explaining.  ``SESSION_COOKIE_SECURE`` is the flag that
        # would silently break dev if DevConfig adopted ProdConfig's
        # posture, so it is the one that matters most.
        assert "SESSION_COOKIE_SECURE" in body, (
            "DevConfig docstring does not mention SESSION_COOKIE_SECURE; "
            "the pragma is supposed to explain why dev does NOT set "
            "this flag (Flask's default is False; ProdConfig sets True)."
        )


# ──────────────────────────────────────────────────────────────────
# F-148: entrypoint.sh _load_secret helper -- structural assertions
# ──────────────────────────────────────────────────────────────────


class TestEntrypointLoaderSourceShape:
    """The entrypoint carries the _load_secret helper with the right contract.

    Source-level checks pair with the behavioural tests below: a
    regression that removes the helper or changes its return-shape
    would fail BOTH this test class (immediately) and the behavioural
    class (slowly, via shell exec).  Catching it at source level
    surfaces the breakage without spawning bash.
    """

    @pytest.fixture(scope="class")
    def entrypoint_text(self) -> str:
        """Return the full entrypoint.sh source as a string."""
        return ENTRYPOINT_SCRIPT.read_text(encoding="utf-8")

    def test_loader_function_is_defined(self, entrypoint_text: str) -> None:
        """``_load_secret() {`` appears in entrypoint.sh."""
        assert re.search(
            r"^_load_secret\(\)\s*\{",
            entrypoint_text,
            re.MULTILINE,
        ), (
            "entrypoint.sh no longer defines _load_secret; the F-148 "
            "Docker secrets loader has been removed (Commit C-38 regression)."
        )

    @pytest.mark.parametrize(
        "var_name,file_name",
        [
            ("SECRET_KEY", "secret_key"),
            ("POSTGRES_PASSWORD", "postgres_password"),
            ("APP_ROLE_PASSWORD", "app_role_password"),
            ("TOTP_ENCRYPTION_KEY", "totp_encryption_key"),
            ("TOTP_ENCRYPTION_KEY_OLD", "totp_encryption_key_old"),
        ],
    )
    def test_loader_is_invoked_for_each_secret(
        self, entrypoint_text: str, var_name: str, file_name: str,
    ) -> None:
        """Every documented secret has a ``_load_secret <VAR> <file>`` call."""
        # Match the canonical invocation.  Whitespace tolerant but
        # we require the exact var/file pair so a typo
        # (``_load_secret SECRET_KEY postgres_password``) would
        # surface here instead of as a runtime auth error.
        assert re.search(
            rf"^\s*_load_secret\s+{var_name}\s+{file_name}\b",
            entrypoint_text,
            re.MULTILINE,
        ), (
            f"entrypoint.sh does not invoke ``_load_secret {var_name} "
            f"{file_name}``; the secret will not be loaded from the "
            "file-backed posture and the operator's docker secret "
            "would silently fall back to the env value (F-148 regression)."
        )

    def test_loader_invocations_precede_secret_key_validation(
        self, entrypoint_text: str,
    ) -> None:
        """Every ``_load_secret`` call appears BEFORE the SECRET_KEY shape check.

        Ordering invariant: the SECRET_KEY length / placeholder check
        only works correctly if the env var is already populated from
        whichever source (file or env).  A regression that runs the
        loader AFTER the validation would let a placeholder pass the
        shape check and then have its real value loaded -- the wrong
        value would never be inspected, defeating the validation.
        """
        loader_calls = list(re.finditer(
            r"^\s*_load_secret\s+\w+\s+\w+\b",
            entrypoint_text,
            re.MULTILINE,
        ))
        assert loader_calls, "no _load_secret invocations found"
        # The validation block opens with a ``-z "${SECRET_KEY}"``
        # check.  Find the earliest one.
        validation_match = re.search(
            r'\[\s*-z\s+"\$\{SECRET_KEY\}"\s*\]',
            entrypoint_text,
        )
        assert validation_match is not None, (
            "entrypoint.sh no longer validates SECRET_KEY shape"
        )
        last_loader_offset = max(m.start() for m in loader_calls)
        assert last_loader_offset < validation_match.start(), (
            "_load_secret invocation appears AFTER the SECRET_KEY "
            "shape check; the validation runs against the env-only "
            "value and the file-backed override would slip past it."
        )

    def test_secret_key_placeholder_rejected_at_entrypoint(
        self, entrypoint_text: str,
    ) -> None:
        """``replaced_by_docker_secret*`` rejected by the SECRET_KEY case statement.

        The placeholder is the documented form an operator leaves in
        .env when migrating to Posture 2 (file-backed secrets).  If
        the secret file at /run/secrets/secret_key is missing or
        unreadable, the placeholder remains as the active SECRET_KEY
        -- a publicly-known value.  Catching it here closes the gap
        where the operator believes they are on Posture 2 but is
        actually running on the placeholder.
        """
        # The case statement must include ``replaced_by_docker_secret*``
        # as one of the rejected patterns alongside the historical
        # placeholders.
        assert re.search(
            r"replaced_by_docker_secret\*",
            entrypoint_text,
        ), (
            "entrypoint.sh case statement does not reject the "
            "``replaced_by_docker_secret*`` placeholder; an operator "
            "whose docker secret file is missing would silently boot "
            "under the public placeholder value (audit finding F-148 "
            "regression / hole in Commit C-38)."
        )

    def test_loader_rebuilds_database_url_when_postgres_secret_loaded(
        self, entrypoint_text: str,
    ) -> None:
        """The DATABASE_URL rebuild branch fires when POSTGRES_PASSWORD comes from a file.

        Compose interpolates ``DATABASE_URL`` from
        ``${POSTGRES_PASSWORD}`` at config-time, baking whatever
        placeholder the operator put in .env into the URI.  When the
        loader overwrites ``POSTGRES_PASSWORD`` with the real value
        from /run/secrets, ``DATABASE_URL`` goes stale and the deploy
        scripts (init_database.py, seed_*.py) connect under the
        placeholder -- which the postgres role does not recognise.
        Asserting on the rebuild branch catches a regression that
        removes it.
        """
        # The rebuild block is conditional on the
        # ``_postgres_password_loaded_from_file`` flag.  Match the
        # opening conditional.
        assert re.search(
            r'_postgres_password_loaded_from_file.*?-eq\s+1.*?\bexport\s+DATABASE_URL=',
            entrypoint_text,
            re.DOTALL,
        ), (
            "entrypoint.sh no longer rebuilds DATABASE_URL when "
            "POSTGRES_PASSWORD comes from a docker secret file; the "
            "deploy scripts will connect under the .env placeholder "
            "instead of the real password."
        )
        # And DB_PASSWORD must be rebuilt too -- psql calls in the
        # entrypoint use it directly.
        assert re.search(
            r'_postgres_password_loaded_from_file.*?-eq\s+1.*?\bexport\s+DB_PASSWORD=',
            entrypoint_text,
            re.DOTALL,
        ), (
            "entrypoint.sh no longer rebuilds DB_PASSWORD when "
            "POSTGRES_PASSWORD comes from a docker secret file; the "
            "psql schema-creation and role-provisioning calls will "
            "use the .env placeholder password instead."
        )


# ──────────────────────────────────────────────────────────────────
# F-148: entrypoint.sh _load_secret helper -- behavioural tests
# ──────────────────────────────────────────────────────────────────


def _extract_loader_function(test_secrets_dir: Path) -> str:
    """Return the bash source of ``_load_secret`` rewritten to look in
    ``test_secrets_dir`` instead of /run/secrets.

    Extracts the function from the live entrypoint.sh so the
    behavioural tests exercise the production code (not a
    duplicate).  The single string substitution ``"/run/secrets/"`` ->
    ``"<test_dir>/"`` lets the otherwise-unmodified function read
    from the test fixture.

    The substitution ONLY targets the literal path inside the
    ``secret_path`` assignment.  The error-message references to
    ``/opt/docker/shekel/secrets/`` are operator hints and are not
    rewritten -- their content is irrelevant to behaviour and a
    rewrite would obscure the test output if a failure surfaces.
    """
    text = ENTRYPOINT_SCRIPT.read_text(encoding="utf-8")
    # Capture the function from "_load_secret() {" to the matching
    # "}" at column 0.  ``re.MULTILINE`` so ``^`` matches the start
    # of any line; ``re.DOTALL`` so ``.`` crosses newlines.
    match = re.search(
        r"^(_load_secret\(\)\s*\{.*?\n^\})",
        text,
        re.MULTILINE | re.DOTALL,
    )
    if match is None:
        pytest.fail(
            "Could not extract _load_secret from entrypoint.sh; the "
            "function must start with ``_load_secret() {`` at column "
            "0 and end with ``}`` at column 0."
        )
    func_source = match.group(1)
    # Rewrite only the literal path inside the secret_path
    # assignment.  The function uses
    # ``local secret_path="/run/secrets/${file_name}"`` -- we replace
    # ``/run/secrets/`` with the absolute test path.
    rewritten = func_source.replace("/run/secrets/", f"{test_secrets_dir}/")
    return rewritten


def _run_loader_script(loader_func_source: str, body: str) -> subprocess.CompletedProcess[str]:
    """Run a bash script that sources the loader and executes ``body``."""
    script = (
        "#!/bin/bash\n"
        "set -eEo pipefail\n"
        f"{loader_func_source}\n\n"
        f"{body}\n"
    )
    return subprocess.run(
        ["bash", "-c", script],
        capture_output=True,
        text=True,
        timeout=BASH_TEST_TIMEOUT_S,
        check=False,
    )


class TestEntrypointLoaderBehaviour:
    """Run the extracted ``_load_secret`` against real fixture files.

    These tests prove the function actually:
    1. Loads a value when the file exists.
    2. Falls back silently (env unchanged) when the file is absent.
    3. Rejects an empty file with a clear diagnostic.
    4. Strips trailing newlines (``echo`` writes them) without
       mangling internal newlines or special characters.
    """

    def test_loader_reads_secret_when_file_present(self, tmp_path: Path) -> None:
        """A populated file overrides any env value the helper sees."""
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        (secrets_dir / "secret_key").write_text("a" * SECRET_KEY_HEX_BYTES)
        loader = _extract_loader_function(secrets_dir)

        result = _run_loader_script(
            loader,
            (
                # Pre-set the env var to a known wrong value so we
                # can prove the loader OVERWROTE it (not merely
                # appended to a missing var).
                "export TEST_SECRET_KEY=stale-env-value\n"
                "_load_secret TEST_SECRET_KEY secret_key\n"
                "echo \"VAR=${TEST_SECRET_KEY}\""
            ),
        )

        assert result.returncode == 0, (
            f"loader exited non-zero: stderr={result.stderr!r}"
        )
        # Exact match: 64 ``a`` characters, no trailing whitespace.
        assert f"VAR={'a' * SECRET_KEY_HEX_BYTES}\n" in result.stdout, (
            f"loader did not overwrite env var with file content; "
            f"stdout={result.stdout!r}"
        )

    def test_loader_falls_back_to_env_when_file_absent(self, tmp_path: Path) -> None:
        """A missing file is a silent no-op; env value is preserved."""
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        # Note: NO file created.  The loader should not error.
        loader = _extract_loader_function(secrets_dir)

        result = _run_loader_script(
            loader,
            (
                "export TEST_SECRET=fallback-env-value\n"
                # The argument 'nonexistent_file' has no matching
                # file in secrets_dir, so the loader returns 0
                # without touching the var.
                "_load_secret TEST_SECRET nonexistent_file\n"
                "echo \"VAR=${TEST_SECRET}\""
            ),
        )

        assert result.returncode == 0, (
            f"loader exited non-zero on missing file: stderr={result.stderr!r}"
        )
        assert "VAR=fallback-env-value" in result.stdout, (
            "loader mutated the env var when the secret file was "
            f"absent; stdout={result.stdout!r}"
        )
        # No "Loaded ..." log line should fire when the file is absent.
        assert "Loaded " not in result.stdout, (
            "loader logged a ``Loaded ...`` line for a missing file; "
            "the no-op branch should be silent."
        )

    def test_loader_rejects_empty_secret_file(self, tmp_path: Path) -> None:
        """A present-but-empty file is a misconfiguration -- fail fast."""
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        # Touch the file so it exists but contains no bytes.
        (secrets_dir / "empty_file").write_bytes(b"")
        loader = _extract_loader_function(secrets_dir)

        result = _run_loader_script(
            loader,
            "_load_secret TEST_SECRET empty_file",
        )

        assert result.returncode != 0, (
            "loader accepted an empty secret file and would have "
            "exported an empty value -- the operator's intent to use "
            "file-backed secrets is clear (file exists) but the file "
            "is empty; this is a misconfiguration that must fail fast."
        )
        assert "is present but empty" in result.stderr, (
            f"loader did not emit the expected diagnostic for an empty "
            f"secret file; stderr={result.stderr!r}"
        )

    def test_loader_strips_trailing_newline(self, tmp_path: Path) -> None:
        """``echo "value" > file`` writes a trailing newline; loader strips it.

        Bash's ``$(< file)`` command substitution strips trailing
        newlines, so a file written by the typical ``echo`` pattern
        produces the same in-process value as ``printf 'value' >
        file``.  This is documented in the helper's source comment
        and is the load-bearing reason the helper uses ``$(< ...)``
        instead of ``cat``.
        """
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        # Use ``write_text`` -- Python's text-mode write does NOT add
        # a trailing newline, so we add one explicitly to mirror the
        # ``echo "value" > file`` shell pattern.
        (secrets_dir / "with_newline").write_text("value-with-trailing-newline\n")
        loader = _extract_loader_function(secrets_dir)

        result = _run_loader_script(
            loader,
            (
                "_load_secret TEST_VAR with_newline\n"
                # ``${#TEST_VAR}`` is the byte length.  29 chars
                # without the trailing newline; 30 with it.  We
                # assert on the length directly so a regression that
                # leaves the newline in surfaces as a precise number,
                # not a fuzzy "not equal".
                "echo \"LEN=${#TEST_VAR}\"\n"
                "echo \"VAL=${TEST_VAR}\""
            ),
        )

        assert result.returncode == 0, result.stderr
        # 27 = len("value-with-trailing-newline").
        assert "LEN=27" in result.stdout, (
            f"loader did not strip the trailing newline; stdout={result.stdout!r}"
        )
        assert "VAL=value-with-trailing-newline" in result.stdout

    def test_entrypoint_rejects_placeholder_when_secret_file_missing(
        self,
    ) -> None:
        """The entrypoint case statement rejects ``replaced_by_docker_secret*``.

        Behavioural check: extract the SECRET_KEY validation block
        from entrypoint.sh, run it in bash with the placeholder set
        as SECRET_KEY, assert the script exits non-zero with the
        placeholder diagnostic.  Mirrors the source-shape assertion
        in TestEntrypointLoaderSourceShape so a regression that
        leaves the case statement intact but breaks the case match
        (e.g. typo in the pattern) is still caught.
        """
        # Extract the entire SECRET_KEY validation section (header
        # ``# ── 0a.``) up to the next section (``# ── 0b.``).  The
        # placeholder (32+ chars) clears the length check, so the
        # case statement is what must catch it.  We capture the
        # whole 0a section because the case statement now contains
        # a nested case for the docker-secret hint -- a regex that
        # tries to capture only up to the first ``esac`` would
        # truncate at the inner one.
        text = ENTRYPOINT_SCRIPT.read_text(encoding="utf-8")
        match = re.search(
            r"(# ── 0a\. Validate SECRET_KEY shape.*?)(?=\n# ── 0b\.)",
            text,
            re.DOTALL,
        )
        if match is None:
            pytest.fail(
                "Could not extract SECRET_KEY validation section "
                "from entrypoint.sh; the section must start with "
                "``# ── 0a. Validate SECRET_KEY shape`` and end "
                "before ``# ── 0b.``."
            )
        validation = match.group(1)
        script = (
            "#!/bin/bash\n"
            "set -eEo pipefail\n"
            # 32+ char placeholder so the length check passes.
            'export SECRET_KEY="replaced_by_docker_secret_padded_to_be_long_enough"\n'
            f"{validation}\n"
            'echo "should-not-reach"\n'
        )
        result = subprocess.run(
            ["bash", "-c", script],
            capture_output=True,
            text=True,
            timeout=BASH_TEST_TIMEOUT_S,
            check=False,
        )
        assert result.returncode != 0, (
            "entrypoint.sh validation accepted "
            "``replaced_by_docker_secret_padded_...`` as a valid "
            "SECRET_KEY; the placeholder pattern is not in the "
            "rejected case branches."
        )
        assert "known placeholder" in result.stderr, (
            f"entrypoint.sh did not emit the ``known placeholder`` "
            f"diagnostic for the docker-secret placeholder; "
            f"stderr={result.stderr!r}"
        )
        # The hint about the missing /run/secrets/secret_key file
        # must surface so the operator knows where to look.
        assert "Migrating to Docker secrets" in result.stderr, (
            "entrypoint.sh placeholder rejection does not point the "
            "operator at the runbook section; the operator has no "
            "discoverable hint that the secret file is missing."
        )
        # ``should-not-reach`` confirms exit fired.
        assert "should-not-reach" not in result.stdout

    def test_loader_preserves_special_characters(self, tmp_path: Path) -> None:
        """Special characters (URL-safe base64, punctuation) survive the load.

        Fernet keys are URL-safe base64 (``A-Za-z0-9_-=``).  TOTP
        encryption keys generated by ``Fernet.generate_key()`` end
        with ``=`` padding which a sloppy shell substitution
        (``eval``, double-quoted ``$VAR`` in the wrong context) could
        mangle.  Random bash special chars (``$``, `` ``, ``"``)
        are tested so a future use of ``$()`` or unquoted variable
        expansion in the helper surfaces here.
        """
        secrets_dir = tmp_path / "secrets"
        secrets_dir.mkdir()
        # Use printf via Python directly to avoid any shell parsing.
        special = "k_AbC123-_=+/!@#$%^&*() with spaces and \"quotes\""
        (secrets_dir / "special_secret").write_text(special)
        loader = _extract_loader_function(secrets_dir)

        # We base64-encode the loaded value to assert on it without
        # going through any further shell quoting -- this isolates
        # the test from quoting bugs in the assertion harness itself.
        result = _run_loader_script(
            loader,
            (
                "_load_secret TEST_VAR special_secret\n"
                # ``printf '%s' "$TEST_VAR" | base64 -w0`` produces a
                # single-line base64 string we can compare exactly.
                "printf '%s' \"$TEST_VAR\" | base64 -w0\n"
                "echo \"\""  # newline so output is parseable
            ),
        )

        assert result.returncode == 0, result.stderr
        expected_b64 = base64.b64encode(special.encode("utf-8")).decode("ascii")
        assert expected_b64 in result.stdout, (
            f"loader mangled special characters; expected b64="
            f"{expected_b64!r}, got stdout={result.stdout!r}"
        )


# ──────────────────────────────────────────────────────────────────
# F-148: deploy/docker-compose.prod.yml secrets block
# ──────────────────────────────────────────────────────────────────


class TestProdComposeSecretsBlock:
    """The shared-mode prod override declares Docker secrets and grants access.

    Source-text checks complement the ``docker compose config``
    integration test below: text checks catch a misshapen secret
    declaration immediately, while the integration check catches
    structural bugs that pass the text scan but fail compose's
    schema validation.
    """

    @pytest.fixture(scope="class")
    def compose_text(self) -> str:
        """Return the full deploy/docker-compose.prod.yml source as a string."""
        return DOCKER_COMPOSE_PROD.read_text(encoding="utf-8")

    @pytest.mark.parametrize(
        "secret_name",
        [
            "secret_key",
            "postgres_password",
            "app_role_password",
            "totp_encryption_key",
        ],
    )
    def test_top_level_secrets_block_declares_secret(
        self, compose_text: str, secret_name: str,
    ) -> None:
        """Each required secret has a top-level declaration with a file path."""
        # Match the YAML block: ``<name>:`` followed by an indented
        # ``file: /opt/docker/shekel/secrets/<name>`` line.
        pattern = (
            rf"^  {secret_name}:\n"
            rf"\s+file:\s+/opt/docker/shekel/secrets/{secret_name}\b"
        )
        assert re.search(pattern, compose_text, re.MULTILINE), (
            f"deploy/docker-compose.prod.yml does not declare the "
            f"``{secret_name}`` secret with a file path under "
            f"/opt/docker/shekel/secrets/.  The runbook documents "
            "this exact path; a drift would silently break operator "
            "pre-flight commands."
        )

    @pytest.mark.parametrize(
        "secret_name",
        [
            "secret_key",
            "postgres_password",
            "app_role_password",
            "totp_encryption_key",
        ],
    )
    def test_app_service_grants_access_to_secret(
        self, compose_text: str, secret_name: str,
    ) -> None:
        """The app service's ``secrets:`` list grants access to every required secret."""
        # Capture the app service's body up to the next service or
        # top-level block.  We then scan inside it for the secret
        # name on a list item line.
        app_match = re.search(
            r"\n  app:\n(.+?)(?=\n  \w|\nnetworks:|\nsecrets:|\Z)",
            compose_text,
            re.DOTALL,
        )
        assert app_match is not None, (
            "deploy/docker-compose.prod.yml no longer defines an "
            "``app`` service block."
        )
        app_body = app_match.group(1)
        # The list item appears as ``      - secret_name`` (six
        # spaces of indent inside the secrets: block).  Match
        # whitespace tolerantly so a future indentation cleanup does
        # not break the test.
        assert re.search(rf"\n\s+-\s+{secret_name}\b", app_body), (
            f"app service in deploy/docker-compose.prod.yml does not "
            f"reference ``{secret_name}`` in its ``secrets:`` list; "
            "the secret will be declared at the top level but never "
            "mounted into /run/secrets/ for the container."
        )

    def test_db_service_grants_access_to_postgres_password(
        self, compose_text: str,
    ) -> None:
        """The db service mounts the postgres_password secret natively."""
        db_match = re.search(
            r"\n  db:\n(.+?)(?=\n  \w|\nnetworks:|\nsecrets:|\Z)",
            compose_text,
            re.DOTALL,
        )
        assert db_match is not None, "db service block missing"
        db_body = db_match.group(1)
        assert re.search(r"\n\s+-\s+postgres_password\b", db_body), (
            "db service does not mount the ``postgres_password`` "
            "docker secret; the postgres image cannot read /run/"
            "secrets/postgres_password and the POSTGRES_PASSWORD_FILE "
            "handoff will fail at container start."
        )

    def test_db_service_uses_postgres_password_file(
        self, compose_text: str,
    ) -> None:
        """``POSTGRES_PASSWORD_FILE`` is set in the db environment.

        The postgres image's docker-entrypoint.sh reads this env var
        natively to populate the superuser password from a file.
        """
        db_match = re.search(
            r"\n  db:\n(.+?)(?=\n  \w|\nnetworks:|\nsecrets:|\Z)",
            compose_text,
            re.DOTALL,
        )
        assert db_match is not None, "db service block missing"
        db_body = db_match.group(1)
        assert re.search(
            r"POSTGRES_PASSWORD_FILE:\s+/run/secrets/postgres_password",
            db_body,
        ), (
            "db service environment does not set "
            "POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password; "
            "the postgres image will not read the docker secret."
        )

    def test_db_service_overrides_postgres_password_to_empty(
        self, compose_text: str,
    ) -> None:
        """``POSTGRES_PASSWORD: ""`` is required for the postgres image's mutex.

        The postgres image's ``file_env`` helper errors when both
        POSTGRES_PASSWORD and POSTGRES_PASSWORD_FILE are non-empty
        (the "both set are exclusive" check).  Setting
        POSTGRES_PASSWORD to the empty string lets the file-backed
        branch run.
        """
        db_match = re.search(
            r"\n  db:\n(.+?)(?=\n  \w|\nnetworks:|\nsecrets:|\Z)",
            compose_text,
            re.DOTALL,
        )
        assert db_match is not None, "db service block missing"
        db_body = db_match.group(1)
        # Match either ``POSTGRES_PASSWORD: ""`` or
        # ``POSTGRES_PASSWORD: ''`` -- both are valid YAML for an
        # empty string.  The pattern is built explicitly via raw
        # strings so the pylint implicit-str-concat warning does not
        # fire on adjacent string literals.
        empty_yaml_pattern = r'POSTGRES_PASSWORD:\s+(""|' + "''" + r')'
        assert re.search(empty_yaml_pattern, db_body), (
            "db service environment does not override the base file's "
            "POSTGRES_PASSWORD interpolation to an empty string; the "
            "postgres image's file_env helper will see both env vars "
            "as non-empty and error with ``both ... are exclusive``."
        )


# ──────────────────────────────────────────────────────────────────
# F-148: docker compose merged config integration check
# ──────────────────────────────────────────────────────────────────


class TestProdComposeMergedConfig:
    """``docker compose config`` parses the secrets block successfully.

    Skipped on hosts without docker.  Catches a structural break in
    the secrets block that the source-text tests above might miss
    (e.g. a YAML indentation error that slips past the regex but
    fails the schema validator).
    """

    def test_docker_compose_config_succeeds_with_secrets_block(self) -> None:
        """The merged config parses and includes every declared secret."""
        if not _docker_available():
            pytest.skip("docker not available; cannot run docker compose config")

        env = {
            "PATH": "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin",
            "POSTGRES_PASSWORD": "test-postgres-password",
            "SECRET_KEY": "test-secret-key",
            "APP_ROLE_PASSWORD": "test-app-role-password",
            "SHEKEL_IMAGE_DIGEST": "sha256:" + "0" * 64,
        }
        result = subprocess.run(
            [
                "docker",
                "compose",
                "--env-file",
                "/dev/null",
                "-f",
                str(DOCKER_COMPOSE),
                "-f",
                str(DOCKER_COMPOSE_PROD),
                "config",
            ],
            capture_output=True,
            text=True,
            timeout=DOCKER_SUBPROCESS_TIMEOUT_S,
            check=False,
            cwd=str(REPO_ROOT),
            env=env,
        )
        assert result.returncode == 0, (
            "docker compose config failed for the merged base + "
            "shared-mode override:\n"
            f"  stdout: {result.stdout}\n"
            f"  stderr: {result.stderr}"
        )
        merged = result.stdout

        # Every required secret appears in the merged top-level
        # secrets: block.  Compose annotates each secret with a
        # ``name: shekel-prod_<name>`` line; we match on the file:
        # line which must reference /opt/docker/shekel/secrets/.
        for secret in (
            "secret_key",
            "postgres_password",
            "app_role_password",
            "totp_encryption_key",
        ):
            expected = f"file: /opt/docker/shekel/secrets/{secret}"
            assert expected in merged, (
                f"merged compose config does not include the {secret} "
                f"secret with file path /opt/docker/shekel/secrets/"
                f"{secret}; the shared-mode prod stack would not mount "
                "the file at /run/secrets/<name> for the container."
            )

        # The db service's POSTGRES_PASSWORD must be the empty
        # string in the merged config -- the override step that
        # bypasses the postgres image's mutex check.
        assert 'POSTGRES_PASSWORD: ""' in merged, (
            "merged compose config does not show POSTGRES_PASSWORD as "
            'an empty string ("") on the db service; the postgres '
            "image will see both POSTGRES_PASSWORD and "
            "POSTGRES_PASSWORD_FILE as non-empty and error at start."
        )

        # The app service must mount each required secret to
        # /run/secrets/<name>.  Compose's expanded form is
        # ``- source: <name>\n  target: /run/secrets/<name>``.
        for secret in (
            "secret_key",
            "postgres_password",
            "app_role_password",
            "totp_encryption_key",
        ):
            target_line = f"target: /run/secrets/{secret}"
            assert target_line in merged, (
                f"merged compose config does not mount {secret} at "
                f"/run/secrets/{secret} for any container; the "
                "entrypoint.sh _load_secret helper will not find the "
                "file at the documented path."
            )


# ──────────────────────────────────────────────────────────────────
# Documentation -- the runbook covers the docker-secrets posture
# ──────────────────────────────────────────────────────────────────


class TestRunbookDocumentsDockerSecretsPosture:
    """``docs/runbook_secrets.md`` covers the file-backed posture.

    Operator-documentation check: the runbook is the source of truth
    for migration and rotation procedures.  A code change that adds
    docker-secrets support without runbook coverage leaves operators
    with no procedure for the new posture.
    """

    @pytest.fixture(scope="class")
    def runbook_text(self) -> str:
        """Return the full docs/runbook_secrets.md source as a string."""
        return RUNBOOK_SECRETS.read_text(encoding="utf-8")

    def test_runbook_describes_two_postures(self, runbook_text: str) -> None:
        """The runbook explicitly contrasts env-backed and file-backed postures."""
        assert "Posture 1" in runbook_text and "Posture 2" in runbook_text, (
            "runbook_secrets.md does not split the two postures into "
            "named sections; operators cannot easily decide which "
            "posture they are running."
        )
        assert "env-backed" in runbook_text.lower(), (
            "runbook does not name the env-backed posture explicitly"
        )
        assert "file-backed" in runbook_text.lower(), (
            "runbook does not name the file-backed posture explicitly"
        )

    def test_runbook_documents_migration_procedure(
        self, runbook_text: str,
    ) -> None:
        """A concrete migration procedure appears under a section header."""
        assert "Migrating to Docker secrets" in runbook_text, (
            "runbook does not include a ``Migrating to Docker secrets`` "
            "section; operators have no documented step-by-step path "
            "from env-backed to file-backed."
        )
        # The procedure must reference the canonical secrets
        # directory path.  A drift between this path and the compose
        # file's secret declarations would silently break operators
        # following the runbook.
        assert "/opt/docker/shekel/secrets" in runbook_text, (
            "runbook migration procedure does not reference "
            "/opt/docker/shekel/secrets/; operators following the "
            "runbook would not know where to put the secret files."
        )

    def test_runbook_secret_inventory_lists_app_role_password(
        self, runbook_text: str,
    ) -> None:
        """The Secret Inventory table includes APP_ROLE_PASSWORD.

        Pre-C-38 the inventory listed three secrets; C-13 added
        APP_ROLE_PASSWORD without updating the inventory.  C-38
        closes that gap.  A regression that drops the row would
        re-create the documentation hole the audit surfaced.
        """
        # Find the inventory table -- a heading-3 ``## Secret
        # Inventory`` followed by a markdown table.  The table rows
        # have ``| `VAR` |`` shape.
        inventory_match = re.search(
            r"## Secret Inventory(.+?)## ", runbook_text, re.DOTALL,
        )
        assert inventory_match is not None, "Secret Inventory section missing"
        table_body = inventory_match.group(1)
        assert "`APP_ROLE_PASSWORD`" in table_body, (
            "Secret Inventory table does not list APP_ROLE_PASSWORD; "
            "the C-13 secret is undocumented in the inventory and "
            "operators rebuilding from disaster would miss it."
        )
