"""Add salary schema tables

Revision ID: 22b3dd9d9ed3
Revises: 44460d8fe471
Create Date: 2026-02-24 06:42:08.549170
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision = '22b3dd9d9ed3'
down_revision = '44460d8fe471'
branch_labels = None
depends_on = None


def _constraint_exists(name, schema):
    """Check if a constraint exists (for fresh vs. migrated DB compat)."""
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT 1 FROM pg_constraint c "
        "JOIN pg_namespace n ON c.connamespace = n.oid "
        "WHERE c.conname = :name AND n.nspname = :schema"
    ), {"name": name, "schema": schema})
    return result.fetchone() is not None


def _rename_unique(old_name, new_name, table, columns, schema):
    """Rename a unique constraint if the old name exists."""
    if _constraint_exists(old_name, schema):
        op.drop_constraint(old_name, table, schema=schema, type_='unique')
        op.create_unique_constraint(new_name, table, columns, schema=schema)


def upgrade():
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mfa_configs', 'backup_codes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='auth')
    op.drop_index('idx_anchor_history_account', table_name='account_anchor_history', schema='budget')
    op.create_index('idx_anchor_history_account', 'account_anchor_history', ['account_id', 'created_at'], unique=False, schema='budget')
    _rename_unique('accounts_user_id_name_key', 'uq_accounts_user_name',
                   'accounts', ['user_id', 'name'], 'budget')
    _rename_unique('categories_user_id_group_name_item_name_key', 'uq_categories_user_group_item',
                   'categories', ['user_id', 'group_name', 'item_name'], 'budget')
    _rename_unique('pay_periods_user_id_start_date_key', 'uq_pay_periods_user_start',
                   'pay_periods', ['user_id', 'start_date'], 'budget')
    _rename_unique('scenarios_user_id_name_key', 'uq_scenarios_user_name',
                   'scenarios', ['user_id', 'name'], 'budget')
    op.alter_column('fica_configs', 'ss_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False,
               existing_server_default=sa.text('0.0620'),
               schema='salary')
    op.alter_column('fica_configs', 'ss_wage_base',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('168600.00'),
               schema='salary')
    op.alter_column('fica_configs', 'medicare_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False,
               existing_server_default=sa.text('0.0145'),
               schema='salary')
    op.alter_column('fica_configs', 'medicare_surtax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False,
               existing_server_default=sa.text('0.0090'),
               schema='salary')
    op.alter_column('fica_configs', 'medicare_surtax_threshold',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('200000.00'),
               schema='salary')
    _rename_unique('fica_configs_user_id_tax_year_key', 'uq_fica_configs_user_year',
                   'fica_configs', ['user_id', 'tax_year'], 'salary')
    op.alter_column('paycheck_deductions', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False,
               schema='salary')
    op.drop_index('idx_deductions_profile', table_name='paycheck_deductions', schema='salary')
    op.alter_column('salary_profiles', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False,
               existing_server_default=sa.text("'Primary'::character varying"),
               schema='salary')
    op.alter_column('salary_profiles', 'state_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=False,
               schema='salary')
    op.alter_column('salary_profiles', 'pay_periods_per_year',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('26'),
               schema='salary')
    _rename_unique('salary_profiles_user_id_scenario_id_name_key', 'uq_salary_profiles_user_scenario_name',
                   'salary_profiles', ['user_id', 'scenario_id', 'name'], 'salary')
    if _constraint_exists('salary_profiles_template_id_fkey', 'salary'):
        op.drop_constraint('salary_profiles_template_id_fkey', 'salary_profiles', schema='salary', type_='foreignkey')
        op.create_foreign_key(None, 'salary_profiles', 'transaction_templates', ['template_id'], ['id'], source_schema='salary', referent_schema='budget', ondelete='SET NULL')
    op.alter_column('salary_raises', 'notes',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True,
               schema='salary')
    op.drop_index('idx_salary_raises_profile', table_name='salary_raises', schema='salary')
    _rename_unique('state_tax_configs_user_id_state_code_key', 'uq_state_tax_configs_user_state',
                   'state_tax_configs', ['user_id', 'state_code'], 'salary')
    _rename_unique('tax_bracket_sets_user_id_tax_year_filing_status_id_key', 'uq_tax_bracket_sets_user_year_status',
                   'tax_bracket_sets', ['user_id', 'tax_year', 'filing_status_id'], 'salary')
    op.alter_column('tax_brackets', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='salary')
    op.drop_index('idx_tax_brackets_set', table_name='tax_brackets', schema='salary')
    # ### end Alembic commands ###


def downgrade():
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tax_brackets_set', 'tax_brackets', ['bracket_set_id', 'sort_order'], unique=False, schema='salary')
    op.alter_column('tax_brackets', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='salary')
    op.drop_constraint('uq_tax_bracket_sets_user_year_status', 'tax_bracket_sets', schema='salary', type_='unique')
    op.create_unique_constraint('tax_bracket_sets_user_id_tax_year_filing_status_id_key', 'tax_bracket_sets', ['user_id', 'tax_year', 'filing_status_id'], schema='salary')
    op.drop_constraint('uq_state_tax_configs_user_state', 'state_tax_configs', schema='salary', type_='unique')
    op.create_unique_constraint('state_tax_configs_user_id_state_code_key', 'state_tax_configs', ['user_id', 'state_code'], schema='salary')
    op.create_index('idx_salary_raises_profile', 'salary_raises', ['salary_profile_id'], unique=False, schema='salary')
    op.alter_column('salary_raises', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True,
               schema='salary')
    op.drop_constraint(None, 'salary_profiles', schema='salary', type_='foreignkey')
    op.create_foreign_key('salary_profiles_template_id_fkey', 'salary_profiles', 'transaction_templates', ['template_id'], ['id'], source_schema='salary', referent_schema='budget')
    op.drop_constraint('uq_salary_profiles_user_scenario_name', 'salary_profiles', schema='salary', type_='unique')
    op.create_unique_constraint('salary_profiles_user_id_scenario_id_name_key', 'salary_profiles', ['user_id', 'scenario_id', 'name'], schema='salary')
    op.alter_column('salary_profiles', 'pay_periods_per_year',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('26'),
               schema='salary')
    op.alter_column('salary_profiles', 'state_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=True,
               schema='salary')
    op.alter_column('salary_profiles', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'Primary'::character varying"),
               schema='salary')
    op.create_index('idx_deductions_profile', 'paycheck_deductions', ['salary_profile_id'], unique=False, schema='salary')
    op.alter_column('paycheck_deductions', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               schema='salary')
    op.drop_constraint('uq_fica_configs_user_year', 'fica_configs', schema='salary', type_='unique')
    op.create_unique_constraint('fica_configs_user_id_tax_year_key', 'fica_configs', ['user_id', 'tax_year'], schema='salary')
    op.alter_column('fica_configs', 'medicare_surtax_threshold',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('200000.00'),
               schema='salary')
    op.alter_column('fica_configs', 'medicare_surtax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True,
               existing_server_default=sa.text('0.0090'),
               schema='salary')
    op.alter_column('fica_configs', 'medicare_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True,
               existing_server_default=sa.text('0.0145'),
               schema='salary')
    op.alter_column('fica_configs', 'ss_wage_base',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('168600.00'),
               schema='salary')
    op.alter_column('fica_configs', 'ss_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True,
               existing_server_default=sa.text('0.0620'),
               schema='salary')
    op.drop_constraint('uq_scenarios_user_name', 'scenarios', schema='budget', type_='unique')
    op.create_unique_constraint('scenarios_user_id_name_key', 'scenarios', ['user_id', 'name'], schema='budget')
    op.drop_constraint('uq_pay_periods_user_start', 'pay_periods', schema='budget', type_='unique')
    op.create_unique_constraint('pay_periods_user_id_start_date_key', 'pay_periods', ['user_id', 'start_date'], schema='budget')
    op.drop_constraint('uq_categories_user_group_item', 'categories', schema='budget', type_='unique')
    op.create_unique_constraint('categories_user_id_group_name_item_name_key', 'categories', ['user_id', 'group_name', 'item_name'], schema='budget')
    op.drop_constraint('uq_accounts_user_name', 'accounts', schema='budget', type_='unique')
    op.create_unique_constraint('accounts_user_id_name_key', 'accounts', ['user_id', 'name'], schema='budget')
    op.drop_index('idx_anchor_history_account', table_name='account_anchor_history', schema='budget')
    op.create_index('idx_anchor_history_account', 'account_anchor_history', ['account_id', sa.text('created_at DESC')], unique=False, schema='budget')
    op.alter_column('mfa_configs', 'backup_codes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='auth')
    # ### end Alembic commands ###
