"""finish hysa_params -> interest_params rename: PK, FK, sequence, idx, audit trigger

Closes M-1 of docs/audits/security-2026-04-15/model-migration-drift.md.
The earlier ``b4a6bb55f78b_rename_hysa_params_to_interest_params``
migration renamed the table itself plus its check constraint and the
unique index on ``account_id``, but left five legacy artifacts on a
fresh-from-migrations DB:

  * Primary key constraint ``hysa_params_pkey`` (auto-generated by
    SERIAL + PRIMARY KEY in the original f1a2b3c4d5e6 CREATE TABLE)
  * Foreign key constraint ``hysa_params_account_id_fkey`` (auto-
    generated by the column FK)
  * Sequence ``budget.hysa_params_id_seq`` (the SERIAL backing
    sequence; PostgreSQL does not rename it when the table renames)
  * Non-unique index ``idx_hysa_params_account`` (a separate
    explicit index on ``account_id``; redundant with the unique
    index ``interest_params_account_id_key`` that already covers
    the column)
  * Audit trigger ``audit_hysa_params`` (created by the original
    a8b1c2d3e4f5 migration on ``budget.hysa_params``; PostgreSQL
    leaves triggers attached to the renamed table.  The rebuild
    migration ``a5be2a99ea14`` then created
    ``audit_interest_params`` via ``apply_audit_infrastructure``
    -- which loops over ``AUDITED_TABLES`` carrying the new name --
    WITHOUT dropping the orphan.  Result: every interest_params
    write fires both triggers, double-writing system.audit_log
    entries.)

Production was bootstrapped via ``db.create_all()`` + Alembic
``stamp head`` per the rebuild migration's docstring, so prod likely
does not carry the legacy artifacts.  Every artifact-rename / drop
is guarded by ``IF EXISTS`` so the migration succeeds whether the
target carries the legacy names or not.

Revision ID: 44893a9dbcc3
Revises: b2b1ff4c3cea
Create Date: 2026-05-10
"""
from alembic import op


# Revision identifiers, used by Alembic.
revision = "44893a9dbcc3"
down_revision = "b2b1ff4c3cea"
branch_labels = None
depends_on = None


def _constraint_exists_sql(name: str, schema: str = "budget") -> str:
    """Return SQL that checks whether a constraint exists.

    Used inline in the conditional ``DO $$`` blocks below to make the
    PK / FK renames idempotent on databases that already carry the
    new names.  PostgreSQL does not provide ``ALTER TABLE ... RENAME
    CONSTRAINT IF EXISTS``, so the rename is wrapped in a
    procedural block that no-ops when the source name is absent.
    """
    return (
        f"EXISTS (SELECT 1 FROM pg_constraint c "
        f"JOIN pg_namespace n ON c.connamespace = n.oid "
        f"WHERE c.conname = '{name}' AND n.nspname = '{schema}')"
    )


def upgrade():
    """Rename legacy artifacts and drop the orphan audit trigger.

    Every operation tolerates the legacy artifact's absence so the
    migration succeeds against any combination present:

      * Production (db.create_all + stamp head) carries none of the
        legacy names -- every operation is a no-op.
      * Fresh-from-migrations DBs (test template path) carry all
        five -- every operation is a real rename / drop.
      * A partially-renamed DB (hand intervention) -- each operation
        independently checks before acting.
    """
    # 1. Rename PK constraint.  Wrapped in DO block because PostgreSQL
    # has no IF EXISTS form for ALTER TABLE RENAME CONSTRAINT.
    op.execute(
        f"DO $$ BEGIN "
        f"IF {_constraint_exists_sql('hysa_params_pkey')} THEN "
        f"ALTER TABLE budget.interest_params "
        f"RENAME CONSTRAINT hysa_params_pkey "
        f"TO interest_params_pkey; "
        f"END IF; END $$"
    )
    # 2. Rename FK constraint.
    op.execute(
        f"DO $$ BEGIN "
        f"IF {_constraint_exists_sql('hysa_params_account_id_fkey')} THEN "
        f"ALTER TABLE budget.interest_params "
        f"RENAME CONSTRAINT hysa_params_account_id_fkey "
        f"TO interest_params_account_id_fkey; "
        f"END IF; END $$"
    )
    # 3. Rename sequence.  The SERIAL/BIGSERIAL backing sequence is
    # named after the original column-and-table at CREATE TABLE time;
    # ALTER SEQUENCE supports IF EXISTS directly.
    op.execute(
        "ALTER SEQUENCE IF EXISTS budget.hysa_params_id_seq "
        "RENAME TO interest_params_id_seq"
    )
    # 4. Drop the legacy non-unique index.  account_id is already
    # covered by the unique index interest_params_account_id_key
    # (created by the unique=True on the column), so the separate
    # idx_hysa_params_account is dead weight that index_scan would
    # never prefer over the unique one.
    op.execute(
        "DROP INDEX IF EXISTS budget.idx_hysa_params_account"
    )
    # 5. Drop the orphan audit trigger.  apply_audit_infrastructure()
    # already maintains audit_interest_params on this table, so the
    # legacy trigger is redundant; without this drop, every write
    # double-records into system.audit_log.
    op.execute(
        "DROP TRIGGER IF EXISTS audit_hysa_params "
        "ON budget.interest_params"
    )


def downgrade():
    """Restore the legacy artifact names and the orphan trigger.

    The downgrade is symmetric: every IF EXISTS rename can be reversed,
    and the dropped artifacts are recreated in their pre-upgrade form.
    The recreated audit_hysa_params trigger uses the same trigger
    function as the modern audit_interest_params trigger, so the
    double-write hazard returns -- which is the documented pre-
    upgrade state of a fresh-from-migrations DB.

    Each operation is guarded so the downgrade succeeds whether the
    modern names exist or not.
    """
    # 5. Recreate the orphan audit trigger.  Use DROP+CREATE pattern
    # so the recreate is itself idempotent against a database that
    # somehow still carries the legacy trigger name.
    op.execute(
        "DROP TRIGGER IF EXISTS audit_hysa_params "
        "ON budget.interest_params"
    )
    op.execute(
        "CREATE TRIGGER audit_hysa_params "
        "AFTER INSERT OR UPDATE OR DELETE ON budget.interest_params "
        "FOR EACH ROW EXECUTE FUNCTION system.audit_trigger_func()"
    )
    # 4. Recreate the legacy non-unique index.  IF NOT EXISTS so a
    # database that somehow already carries it survives the downgrade.
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_hysa_params_account "
        "ON budget.interest_params (account_id)"
    )
    # 3. Rename sequence back.
    op.execute(
        "ALTER SEQUENCE IF EXISTS budget.interest_params_id_seq "
        "RENAME TO hysa_params_id_seq"
    )
    # 2. Rename FK constraint back.
    op.execute(
        f"DO $$ BEGIN "
        f"IF {_constraint_exists_sql('interest_params_account_id_fkey')} THEN "
        f"ALTER TABLE budget.interest_params "
        f"RENAME CONSTRAINT interest_params_account_id_fkey "
        f"TO hysa_params_account_id_fkey; "
        f"END IF; END $$"
    )
    # 1. Rename PK constraint back.
    op.execute(
        f"DO $$ BEGIN "
        f"IF {_constraint_exists_sql('interest_params_pkey')} THEN "
        f"ALTER TABLE budget.interest_params "
        f"RENAME CONSTRAINT interest_params_pkey "
        f"TO hysa_params_pkey; "
        f"END IF; END $$"
    )
