"""a payroll deduction's cadence is a recurrence rule

Plan step **salary:R15-b** (the second leaf of R15; rulings **R-SAL3**,
**R-SAL29** as amended, **R-SAL30**, **R-SAL32**, **R-SAL35**; ledger rows
**F-21** and **SAL-549**): how often a payroll deduction is taken becomes a
recurrence rule on the row -- the third arm of ``budget.recurrence_rules``'
owning arc -- and ``salary.paycheck_deductions.deductions_per_year`` is
dropped.

**What the column was.**  A three-valued MODE wearing a biweekly count: 26
meant *every paycheck*, 24 *skip the month's third paycheck*, 12 *the month's
first paycheck only*, and the paycheck engine only ever COMPARED it against
the payday's position in its month.  At a weekly cadence "every paycheck" is
52 and "skip the 3rd" names nothing; eleven of the developer's twelve live
deductions carry 24 (the 24-lines sum to ``$517.21`` a paycheck), one carries
26, none 12.

**What each value becomes, spelled ONCE here and read by the engine through
the occurrence walk every recurring definition is generated by**:

* ``24`` -> ``every 1 paycheck, at most 2 a month`` from the owner's opening
  payday: ``unit = period``, ``interval_n = 1``, ``placement =
  containing_date``, ``shift = none``, ``max_per_month = 2`` (the ceiling
  plan step R15-a added, which for a paycheck cadence counts the month's
  paydays on the owner's calendar -- exactly the engine's month ordinal, so a
  third paycheck is skipped as it was);
* ``12`` -> ``every 1 month, on the first paycheck on or after the 1st``:
  ``unit = month``, ``interval_n = 1``, ``placement =
  period_starting_on_or_after``, ``starts_on`` the first of the opening
  payday's month, no ceiling;
* ``26`` -> NO rule, which is ruling R-SAL3's ``NULL``: every paycheck.

**The first occurrence is the owner's opening payday** (ruling **R-SAL30**):
``MIN(start_date)`` of the owner's ``budget.pay_periods``, the same bound the
salary profile's own paycheck rule is authored from.  **The D39-shaped bound
this leaves under a STATED history, measured in both directions** (R-SAL30
recorded the first; an adversarial review of this step measured the second
and found the remedy the first draft named does not exist): the calendar
runs BELOW the recorded opening payday for an owner who states
``history_opens_on`` (plan step balance:X-bh-2), while the occurrence walk
projects nothing backward and a rule's first occurrence clamps to the
opening.  (1) A backdated payday -- below the record, which only a CAPPED
line's year-to-date ever replays -- took every 24 / 12 line under the old
reading and takes none under the rule.  (2) The recorded opening payday
itself: under the old reading its month ordinal counted the backdated
paydays before it (a backdated March 12 makes March 26 the month's SECOND),
so a 12 line was NOT taken on it; under the rule the month's 1st places on
the first SAVED paycheck, so it IS.  No authored ``starts_on`` reaches a
backdated payday, so there is no re-authoring remedy; what a deduction rule
means below the record is an open ruling, filed as a ledger row.  ``$0.00``
today and on production: ``history_opens_on`` is NULL, no line is capped,
and no line is a 12.

**Refusals, before anything is dropped**: a 24 / 12 line whose owner has no
pay period at all (there is no opening payday to start the rule from -- and
no paycheck to price either, but the rule must not be invented), and a value
other than 26 / 24 / 12 (the schema admits no other, the CHECK only refused
non-positives; a fourth value would be silently re-expressed as *every
paycheck* otherwise).  Both are ``RuntimeError``s naming the rows.

**The downgrade rebuilds the column from the two shapes** and refuses a
deduction-owned rule of any other shape -- one authored on R15-c's form with
a cadence the column could not say -- naming it, because writing 26 for a
line the owner said is monthly moves money.  It then deletes every
deduction-owned rule (``budget.recurrence_rules`` is audited, so each survives
in ``system.audit_log.old_data``) and drops the arm.  **The release that
carries this is a MIGRATION release** in ``deploy/shekel-deploy.sh``'s sense:
that script never downgrades; a rollback across this revision is the
pre-deploy dump (ruling **R-R14**).

Graded byte-identical over the developer's saved paychecks by the leaf's
harness: every deduction line on every priced payday equal before and after.

Revision ID: 542c61e48ee8
Revises: 3ec5291ca4e2
Create Date: 2026-09-13 21:40:00.000000
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "542c61e48ee8"
# Re-pointed from ef32dfe4cd8e (R15-a's) at 3ec5291ca4e2 (pay_calendar
# C17-d-2's, merged as #366) the day this leaf's PR opened: whoever lands
# later re-points, so the tree holds ONE head.  Neither touches the other's
# tables.
down_revision = "3ec5291ca4e2"
branch_labels = None
depends_on = None

#: The three arms of the owning arc, exactly one set (ruling R-SAL32).
_ONE_OF_THREE = (
    "(transaction_template_id IS NOT NULL)::int"
    " + (transfer_template_id IS NOT NULL)::int"
    " + (paycheck_deduction_id IS NOT NULL)::int = 1"
)
#: The two-arm XOR the arc carried from plan step R-F6 until this revision.
_ONE_OF_TWO = "(transaction_template_id IS NULL) <> (transfer_template_id IS NULL)"

#: Every deduction the column names a cadence for, with its owner and that
#: owner's opening payday (NULL when the owner has no pay period).
_LINES = sa.text("""
    SELECT d.id, d.name, d.deductions_per_year, sp.user_id,
           (SELECT MIN(pp.start_date) FROM budget.pay_periods pp
             WHERE pp.user_id = sp.user_id) AS opening_payday
      FROM salary.paycheck_deductions d
      JOIN salary.salary_profiles sp ON sp.id = d.salary_profile_id
     ORDER BY d.id
""")

#: One rule per 24-per-year line: every paycheck, at most 2 a month, from the
#: owner's opening payday.
_INSERT_TWENTY_FOUR = sa.text("""
    INSERT INTO budget.recurrence_rules
        (paycheck_deduction_id, unit_id, placement_id, shift_id,
         interval_n, starts_on, max_per_month)
    SELECT d.id,
           (SELECT id FROM ref.recurrence_units WHERE name = 'period'),
           (SELECT id FROM ref.period_placements WHERE name = 'containing_date'),
           (SELECT id FROM ref.business_day_shifts WHERE name = 'none'),
           1,
           (SELECT MIN(pp.start_date) FROM budget.pay_periods pp
             WHERE pp.user_id = sp.user_id),
           2
      FROM salary.paycheck_deductions d
      JOIN salary.salary_profiles sp ON sp.id = d.salary_profile_id
     WHERE d.deductions_per_year = 24
""")

#: One rule per 12-per-year line: monthly, on the first paycheck on or after
#: the 1st, from the first of the opening payday's month.
_INSERT_TWELVE = sa.text("""
    INSERT INTO budget.recurrence_rules
        (paycheck_deduction_id, unit_id, placement_id, shift_id,
         interval_n, starts_on, max_per_month)
    SELECT d.id,
           (SELECT id FROM ref.recurrence_units WHERE name = 'month'),
           (SELECT id FROM ref.period_placements
             WHERE name = 'period_starting_on_or_after'),
           (SELECT id FROM ref.business_day_shifts WHERE name = 'none'),
           1,
           date_trunc('month', (SELECT MIN(pp.start_date) FROM budget.pay_periods pp
                                 WHERE pp.user_id = sp.user_id))::date,
           NULL
      FROM salary.paycheck_deductions d
      JOIN salary.salary_profiles sp ON sp.id = d.salary_profile_id
     WHERE d.deductions_per_year = 12
""")

#: Every deduction-owned rule, with the fields the two shapes are told apart
#: by, for the downgrade's rebuild and its refusal.
_DEDUCTION_RULES = sa.text("""
    SELECT r.id, r.paycheck_deduction_id, u.name AS unit, r.interval_n,
           p.name AS placement, s.name AS shift, r.max_per_month, r.starts_on,
           r.end_date, r.max_occurrences, r.nominal_day, r.due_day_of_month
      FROM budget.recurrence_rules r
      JOIN ref.recurrence_units u ON u.id = r.unit_id
      JOIN ref.period_placements p ON p.id = r.placement_id
      JOIN ref.business_day_shifts s ON s.id = r.shift_id
     WHERE r.paycheck_deduction_id IS NOT NULL
     ORDER BY r.id
""")


def _unadorned(row) -> bool:
    """Whether a rule carries none of the fields neither shape writes.

    A shift, a nominal day, a due day or a closing bound is a cadence the
    column could not say, whatever the two axes read.
    """
    return (
        row.shift == "none" and row.nominal_day is None
        and row.due_day_of_month is None
        and row.end_date is None and row.max_occurrences is None
    )


def _is_twenty_four(row) -> bool:
    """Whether a deduction-owned rule is the 24-per-year shape, exactly.

    Every paycheck, at most 2 a month, and nothing else; ``starts_on`` is
    whatever payday the line was started from, which the count never said.
    """
    return (
        _unadorned(row)
        and row.unit == "period" and row.interval_n == 1
        and row.placement == "containing_date" and row.max_per_month == 2
    )


def _is_twelve(row) -> bool:
    """Whether a deduction-owned rule is the 12-per-year shape, exactly.

    Monthly on the first paycheck on or after the 1st -- so ``starts_on``
    must BE a 1st: a monthly rule from the 26th is *the first paycheck on or
    after the 26th*, a cadence the column's 12 never meant (an adversarial
    review of this step).
    """
    return (
        _unadorned(row)
        and row.unit == "month" and row.interval_n == 1
        and row.placement == "period_starting_on_or_after"
        and row.max_per_month is None and row.starts_on.day == 1
    )


def upgrade():
    """Add the arm, write one rule per 24 / 12 line, drop the column.

    Ordered so that nothing is dropped before its replacement is written and
    the rows it cannot express have refused: add the arm and its constraints,
    refuse what has no opening payday or no shape, write the rules, and only
    then drop the column and its CHECK.
    """
    bind = op.get_bind()
    op.add_column(
        "recurrence_rules",
        sa.Column("paycheck_deduction_id", sa.Integer(), nullable=True),
        schema="budget",
    )
    op.create_foreign_key(
        "fk_recurrence_rules_paycheck_deduction_id",
        "recurrence_rules", "paycheck_deductions",
        ["paycheck_deduction_id"], ["id"],
        source_schema="budget", referent_schema="salary",
        ondelete="CASCADE",
    )
    op.create_index(
        "uq_recurrence_rules_paycheck_deduction_id",
        "recurrence_rules",
        ["paycheck_deduction_id"],
        unique=True,
        schema="budget",
        postgresql_where=sa.text("paycheck_deduction_id IS NOT NULL"),
    )
    op.drop_constraint(
        "ck_recurrence_rules_one_owner", "recurrence_rules",
        schema="budget", type_="check",
    )
    op.create_check_constraint(
        "ck_recurrence_rules_one_owner", "recurrence_rules", _ONE_OF_THREE,
        schema="budget",
    )

    lines = bind.execute(_LINES).fetchall()
    unspellable = [row for row in lines if row.deductions_per_year not in (12, 24, 26)]
    if unspellable:
        listed = "; ".join(
            f"deduction {row.id} ({row.name!r}) carries {row.deductions_per_year}"
            for row in unspellable
        )
        raise RuntimeError(
            f"Cannot re-express deductions_per_year as a recurrence rule: "
            f"{len(unspellable)} row(s) carry a value that is neither 26, 24 "
            f"nor 12 -- {listed}.  The engine read every such value as every "
            f"paycheck and the form never offered one; state what each line "
            f"means (UPDATE salary.paycheck_deductions SET deductions_per_year "
            f"= 26 | 24 | 12 WHERE id = ...) and re-run."
        )
    unstartable = [
        row for row in lines
        if row.deductions_per_year in (12, 24) and row.opening_payday is None
    ]
    if unstartable:
        listed = "; ".join(
            f"deduction {row.id} ({row.name!r}, {row.deductions_per_year}/yr) "
            f"of user {row.user_id}"
            for row in unstartable
        )
        raise RuntimeError(
            f"Cannot write a recurrence rule for {len(unstartable)} deduction(s) "
            f"whose owner has no pay period -- {listed}.  A rule starts on the "
            f"owner's opening payday (ruling R-SAL30) and there is none to "
            f"start it from; generate the owner's pay periods and re-run, or "
            f"set the line to 26 (every paycheck) if that is what it means."
        )
    op.execute(_INSERT_TWENTY_FOUR)
    op.execute(_INSERT_TWELVE)
    written = bind.execute(sa.text(
        "SELECT count(*) FROM budget.recurrence_rules WHERE paycheck_deduction_id IS NOT NULL"
    )).scalar()
    print(f"R15-b: wrote {written} deduction cadence rule(s) for "
          f"{sum(1 for row in lines if row.deductions_per_year in (12, 24))} 24 / 12 line(s)")

    op.drop_constraint(
        "ck_paycheck_deductions_positive_per_year", "paycheck_deductions",
        schema="salary", type_="check",
    )
    op.drop_column("paycheck_deductions", "deductions_per_year", schema="salary")


def downgrade():
    """Rebuild the column from the two shapes, delete the rules, drop the arm.

    Refuses a deduction-owned rule of any other shape rather than writing 26
    for a line the owner said is monthly, or 24 for one they said is
    quarterly: each is money the old column cannot hold.
    """
    bind = op.get_bind()
    op.add_column(
        "paycheck_deductions",
        sa.Column(
            "deductions_per_year", sa.Integer(), nullable=False,
            server_default=sa.text("26"),
        ),
        schema="salary",
    )
    op.create_check_constraint(
        "ck_paycheck_deductions_positive_per_year", "paycheck_deductions",
        "deductions_per_year > 0", schema="salary",
    )

    rules = bind.execute(_DEDUCTION_RULES).fetchall()
    other = [row for row in rules if not (_is_twenty_four(row) or _is_twelve(row))]
    if other:
        listed = "; ".join(
            f"rule {row.id} on deduction {row.paycheck_deduction_id} "
            f"(every {row.interval_n} {row.unit}, {row.placement}, "
            f"at most {row.max_per_month} a month, ends {row.end_date}, "
            f"after {row.max_occurrences})"
            for row in other
        )
        raise RuntimeError(
            f"Cannot rebuild salary.paycheck_deductions.deductions_per_year: "
            f"{len(other)} deduction rule(s) state a cadence the column "
            f"cannot say -- {listed}.  The column knows every paycheck (26), "
            f"a month's first two paychecks (24) and its first (12); writing "
            f"one of those for any other cadence moves money.  Re-author "
            f"each line to one of the three shapes on the form, accepting "
            f"that money change, then re-run."
        )
    for row in rules:
        bind.execute(
            sa.text(
                "UPDATE salary.paycheck_deductions SET deductions_per_year = :n "
                "WHERE id = :id"
            ),
            {"n": 24 if _is_twenty_four(row) else 12, "id": row.paycheck_deduction_id},
        )
    deleted = bind.execute(sa.text(
        "DELETE FROM budget.recurrence_rules WHERE paycheck_deduction_id IS NOT NULL "
        "RETURNING id"
    )).fetchall()
    print(f"R15-b downgrade: rebuilt {len(rules)} line(s), deleted {len(deleted)} rule(s)")

    op.drop_constraint(
        "ck_recurrence_rules_one_owner", "recurrence_rules",
        schema="budget", type_="check",
    )
    op.create_check_constraint(
        "ck_recurrence_rules_one_owner", "recurrence_rules", _ONE_OF_TWO,
        schema="budget",
    )
    op.drop_index(
        "uq_recurrence_rules_paycheck_deduction_id", table_name="recurrence_rules",
        schema="budget",
    )
    op.drop_constraint(
        "fk_recurrence_rules_paycheck_deduction_id", "recurrence_rules",
        schema="budget", type_="foreignkey",
    )
    op.drop_column("recurrence_rules", "paycheck_deduction_id", schema="budget")
