"""initial schema

Revision ID: 9dea99d4e33e
Revises: 
Create Date: 2026-02-21 13:43:52.466705
"""
from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision = '9dea99d4e33e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    op.create_table('account_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ref'
    )
    op.create_table('calc_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ref'
    )
    op.create_table('deduction_timings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ref'
    )
    op.create_table('filing_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ref'
    )
    op.create_table('raise_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ref'
    )
    op.create_table('recurrence_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ref'
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ref'
    )
    op.create_table('tax_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ref'
    )
    op.create_table('transaction_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ref'
    )
    op.create_table('mfa_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('backup_codes', sa.JSON(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='auth'
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_inflation_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('grid_default_periods', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='auth'
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_name', 'item_name', name='uq_categories_user_group_item'),
    schema='budget'
    )
    op.create_index('idx_categories_user_group', 'categories', ['user_id', 'group_name'], unique=False, schema='budget')
    op.create_table('pay_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('period_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'start_date', name='uq_pay_periods_user_start'),
    schema='budget'
    )
    op.create_index('idx_pay_periods_user_index', 'pay_periods', ['user_id', 'period_index'], unique=False, schema='budget')
    op.create_table('recurrence_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('interval_n', sa.Integer(), nullable=True),
    sa.Column('offset_periods', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('month_of_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['ref.recurrence_patterns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=True),
    sa.Column('cloned_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cloned_from_id'], ['budget.scenarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_scenarios_user_name'),
    schema='budget'
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('current_anchor_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_anchor_period_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_type_id'], ['ref.account_types.id'], ),
    sa.ForeignKeyConstraint(['current_anchor_period_id'], ['budget.pay_periods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_accounts_user_name'),
    schema='budget'
    )
    op.create_table('account_anchor_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('pay_period_id', sa.Integer(), nullable=False),
    sa.Column('anchor_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['budget.accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pay_period_id'], ['budget.pay_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    op.create_index('idx_anchor_history_account', 'account_anchor_history', ['account_id', 'created_at'], unique=False, schema='budget')
    op.create_table('savings_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('contribution_per_period', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['budget.accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    op.create_table('transaction_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('recurrence_rule_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['budget.accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['budget.categories.id'], ),
    sa.ForeignKeyConstraint(['recurrence_rule_id'], ['budget.recurrence_rules.id'], ),
    sa.ForeignKeyConstraint(['transaction_type_id'], ['ref.transaction_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    op.create_index('idx_templates_user_type', 'transaction_templates', ['user_id', 'transaction_type_id'], unique=False, schema='budget')
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=False),
    sa.Column('to_account_id', sa.Integer(), nullable=False),
    sa.Column('pay_period_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('from_account_id != to_account_id', name='ck_transfers_different_accounts'),
    sa.ForeignKeyConstraint(['from_account_id'], ['budget.accounts.id'], ),
    sa.ForeignKeyConstraint(['pay_period_id'], ['budget.pay_periods.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['budget.scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['ref.statuses.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['budget.accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    op.create_index('idx_transfers_period_scenario', 'transfers', ['pay_period_id', 'scenario_id'], unique=False, schema='budget')
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('pay_period_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type_id', sa.Integer(), nullable=False),
    sa.Column('estimated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('credit_payback_for_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['budget.categories.id'], ),
    sa.ForeignKeyConstraint(['credit_payback_for_id'], ['budget.transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pay_period_id'], ['budget.pay_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['budget.scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['ref.statuses.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['budget.transaction_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_type_id'], ['ref.transaction_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='budget'
    )
    op.create_index('idx_transactions_credit_payback', 'transactions', ['credit_payback_for_id'], unique=False, schema='budget')
    op.create_index('idx_transactions_period_scenario', 'transactions', ['pay_period_id', 'scenario_id'], unique=False, schema='budget')
    op.create_index('idx_transactions_template', 'transactions', ['template_id'], unique=False, schema='budget')
    op.create_index('idx_transactions_template_period_scenario', 'transactions', ['template_id', 'pay_period_id', 'scenario_id'], unique=True, schema='budget', postgresql_where=sa.text('template_id IS NOT NULL AND is_deleted = FALSE'))
    # ### end Alembic commands ###


def downgrade():
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_template_period_scenario', table_name='transactions', schema='budget', postgresql_where=sa.text('template_id IS NOT NULL AND is_deleted = FALSE'))
    op.drop_index('idx_transactions_template', table_name='transactions', schema='budget')
    op.drop_index('idx_transactions_period_scenario', table_name='transactions', schema='budget')
    op.drop_index('idx_transactions_credit_payback', table_name='transactions', schema='budget')
    op.drop_table('transactions', schema='budget')
    op.drop_index('idx_transfers_period_scenario', table_name='transfers', schema='budget')
    op.drop_table('transfers', schema='budget')
    op.drop_index('idx_templates_user_type', table_name='transaction_templates', schema='budget')
    op.drop_table('transaction_templates', schema='budget')
    op.drop_table('savings_goals', schema='budget')
    op.drop_index('idx_anchor_history_account', table_name='account_anchor_history', schema='budget')
    op.drop_table('account_anchor_history', schema='budget')
    op.drop_table('accounts', schema='budget')
    op.drop_table('scenarios', schema='budget')
    op.drop_table('recurrence_rules', schema='budget')
    op.drop_index('idx_pay_periods_user_index', table_name='pay_periods', schema='budget')
    op.drop_table('pay_periods', schema='budget')
    op.drop_index('idx_categories_user_group', table_name='categories', schema='budget')
    op.drop_table('categories', schema='budget')
    op.drop_table('user_settings', schema='auth')
    op.drop_table('mfa_configs', schema='auth')
    op.drop_table('transaction_types', schema='ref')
    op.drop_table('tax_types', schema='ref')
    op.drop_table('statuses', schema='ref')
    op.drop_table('recurrence_patterns', schema='ref')
    op.drop_table('raise_types', schema='ref')
    op.drop_table('filing_statuses', schema='ref')
    op.drop_table('deduction_timings', schema='ref')
    op.drop_table('calc_methods', schema='ref')
    op.drop_table('account_types', schema='ref')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
