"""phase1 create budget.pay_schedule + cadence backfill

Revision ID: af8254074bef
Revises: f75485db6757
Create Date: 2026-06-13 17:48:36.196220

Pay-period CRUD Phase 1.  Creates the ``budget.pay_schedule`` table --
one row per user holding the persisted pay cadence plus the
continuous-rolling-window configuration -- and backfills a row for
every user who already has pay periods.

A pay period records only ``(start_date, end_date, period_index)``;
cadence is a generation-time argument that is never stored on the
period.  Extend / regenerate / rolling-top-up therefore have nothing
to continue an existing schedule from unless cadence is persisted, and
this table is that storage.  See ``app/models/pay_schedule.py`` for the
column contract; this migration's DDL was autogenerated against that
model and then hand-extended with the backfill and the audit trigger,
so a future ``flask db migrate --autogenerate`` produces an empty diff.

Three forward steps:

  1. **Create budget.pay_schedule** -- columns and named constraints
     mirror the SQLAlchemy model.  No ``anchor_start_date`` column: it
     equals ``min(pay_periods.start_date)`` and has no consumer, so
     storing it would only invite drift.

  2. **Attach the audit trigger** -- a manual DROP TRIGGER IF EXISTS +
     CREATE TRIGGER for just the new table, following the
     ``loan_anchor_events`` (``d3d25212504b``) precedent.  Calling
     ``apply_audit_infrastructure`` here would break a fresh-DB
     migration replay: the earlier rebuild migration (``a5be2a99ea14``)
     runs the same routine against the CURRENT ``AUDITED_TABLES`` --
     which now references ``budget.pay_schedule``, a table that does
     not exist at that earlier point.  The narrow manual attach keeps
     every prior migration replayable.  ``budget.pay_schedule`` is
     registered in ``app/audit_infrastructure.py:AUDITED_TABLES``, so
     the entrypoint trigger-count health check picks up the new total
     automatically (``EXPECTED_TRIGGER_COUNT = len(AUDITED_TABLES)``).
     The trigger is attached BEFORE the backfill so the backfill
     INSERTs are themselves audited (with a NULL ``user_id``, the
     migration-context sentinel).

  3. **Backfill one row per user with periods** -- ``cadence_days`` is
     derived from the user's LAST period (highest ``period_index``) as
     ``(end_date - start_date) + 1``: ``generate_pay_periods`` sets
     ``end_date = start_date + (cadence_days - 1)``, so this inverts
     that exactly.  ``rolling_enabled`` and ``rolling_target_periods``
     fall to their column server-defaults (false / 52).  Users with no
     periods get no row.  Idempotent via ``ON CONFLICT (user_id) DO
     NOTHING`` against ``uq_pay_schedule_user`` so a re-run after a
     partial failure inserts nothing extra.

Self-contained dependency policy: this migration imports nothing from
``app`` (no models, no services, no ref_cache).  The backfill is raw
SQL against the catalog the migration is itself constructing, so it
survives any future refactor of the application layer.

Downgrade drops the table; PostgreSQL cascades the row-level audit
trigger as a dependent object, so no explicit DROP TRIGGER is needed.
Reversible because the backfill is fully reproducible from the
surviving ``budget.pay_periods`` rows on the next upgrade.
"""
from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision = 'af8254074bef'
down_revision = 'f75485db6757'
branch_labels = None
depends_on = None


# Backfill SQL.  One row per user who already has pay periods, with
# ``cadence_days`` inferred from that user's last period's length.
# ``DISTINCT ON (user_id) ... ORDER BY user_id, period_index DESC``
# selects the highest-index (latest) period per user; PostgreSQL date
# subtraction yields an integer day count, so ``(end_date - start_date)
# + 1`` reconstructs the cadence ``generate_pay_periods`` used.  The
# rolling columns are omitted so their server-defaults (false / 52)
# apply -- the default horizon lives in one place (the column DDL).
# ``ON CONFLICT (user_id) DO NOTHING`` makes the step idempotent.
_BACKFILL_CADENCE_SQL = (
    "INSERT INTO budget.pay_schedule (user_id, cadence_days) "
    "SELECT lp.user_id, (lp.end_date - lp.start_date) + 1 "
    "  FROM ( "
    "    SELECT DISTINCT ON (user_id) user_id, start_date, end_date "
    "      FROM budget.pay_periods "
    "     ORDER BY user_id, period_index DESC "
    "  ) lp "
    "ON CONFLICT (user_id) DO NOTHING"
)


def upgrade():
    """Create budget.pay_schedule, attach its audit trigger, backfill."""
    # ── Step 1: create the table ────────────────────────────────────
    op.create_table(
        'pay_schedule',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cadence_days', sa.Integer(), nullable=False),
        sa.Column(
            'rolling_enabled', sa.Boolean(),
            server_default=sa.text('false'), nullable=False,
        ),
        sa.Column(
            'rolling_target_periods', sa.Integer(),
            server_default=sa.text('52'), nullable=False,
        ),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=False,
        ),
        sa.CheckConstraint(
            'cadence_days BETWEEN 1 AND 365',
            name='ck_pay_schedule_cadence_range',
        ),
        sa.CheckConstraint(
            'rolling_target_periods > 0',
            name='ck_pay_schedule_positive_target',
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['auth.users.id'], ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', name='uq_pay_schedule_user'),
        schema='budget',
    )

    # ── Step 2: attach the audit trigger (before backfill) ──────────
    op.execute(
        "DROP TRIGGER IF EXISTS audit_pay_schedule ON budget.pay_schedule"
    )
    op.execute(
        "CREATE TRIGGER audit_pay_schedule "
        "AFTER INSERT OR UPDATE OR DELETE ON budget.pay_schedule "
        "FOR EACH ROW EXECUTE FUNCTION system.audit_trigger_func()"
    )

    # ── Step 3: backfill one row per user with existing periods ─────
    op.execute(_BACKFILL_CADENCE_SQL)


def downgrade():
    """Drop budget.pay_schedule.

    The row-level audit trigger ``audit_pay_schedule`` is a dependent
    object of the table and is dropped automatically by DROP TABLE, so
    no explicit DROP TRIGGER is required.  Reversible: the backfill is
    reproducible from the surviving ``budget.pay_periods`` rows on the
    next upgrade.
    """
    op.drop_table('pay_schedule', schema='budget')
