"""add property type, appreciation params, collateral link

Revision ID: b483e2b8a6d2
Revises: af8254074bef
Create Date: 2026-06-25 09:08:18.749406

Review: solo developer, 2026-06-25 (home-equity mini-sprint -- new audited
table ``budget.asset_appreciation_params``, seeds the ``Property`` account
type, and adds the ``budget.accounts.collateral_account_id`` self-link)

Home-equity / physical-asset mini-sprint.  Adds everything the Property
(Real Estate) asset type needs so a home can be tracked as a first-class
Asset whose market value appreciates and nets against its mortgage:

  1. **``ref.account_types.has_appreciation``** -- a boolean flag, added
     FIRST because the Property seed in step 4 sets it.  ``server_default
     false`` makes the NOT NULL safe on the populated table in one step;
     every existing type is non-appreciating.

  2. **``budget.asset_appreciation_params``** -- the one-to-one params
     table (DDL autogenerated against
     ``app/models/asset_appreciation_params.py`` then hand-extended with
     the trigger and seed, so a future ``flask db migrate --autogenerate``
     produces an empty diff).  ``account_id`` is the
     ``AccountScopedUniqueMixin`` 1:1 FK (unnamed, so the convention-default
     ``asset_appreciation_params_account_id_fkey`` matches the model);
     ``annual_appreciation_rate`` is a decimal fraction bounded by
     ``ck_asset_appreciation_params_valid_rate``.

  3. **Audit trigger** -- a manual DROP TRIGGER IF EXISTS + CREATE TRIGGER
     for just the new table, following the ``loan_anchor_events``
     (``d3d25212504b``) and ``pay_schedule`` (``af8254074bef``) precedent.
     Calling ``apply_audit_infrastructure`` here would break a fresh-DB
     replay (the earlier rebuild migration runs it against the CURRENT
     ``AUDITED_TABLES``, which now references a table that does not yet
     exist at that point).  ``budget.asset_appreciation_params`` is
     registered in ``AUDITED_TABLES`` so the entrypoint trigger-count
     health check picks up the new total automatically.

  4. **Seed the Property type** -- idempotent INSERT into
     ``ref.account_types`` selecting the Asset category id.  Seeded inline
     (not only via ``seed_reference_data``) so the type exists the moment
     this migration runs: ``ref_cache.init`` raises once
     ``AcctTypeEnum.PROPERTY`` (added in the same commit) has no matching
     row, so the enum member and its row must land together.  ``ON
     CONFLICT DO NOTHING`` keeps it idempotent against a re-run and against
     the deploy-time ``seed_ref_tables.py`` upsert.

  5. **``budget.accounts.collateral_account_id``** -- a nullable
     self-referential FK (``ON DELETE SET NULL``) letting a secured
     liability point at the Asset it is secured by, plus
     ``ck_accounts_collateral_not_self`` (autogenerate does not diff CHECK
     constraints on an existing table, so it is added explicitly here).

Self-contained dependency policy: this migration imports nothing from
``app`` -- the seed and the downgrade guard run as raw SQL against the
catalog the migration is itself constructing.

Downgrade reverses in order.  Dropping the asset_appreciation_params
table cascades its row-level audit trigger.  Deleting the Property type
is guarded by a pre-check that raises a clear ``RuntimeError`` (rather
than surfacing the bare FK RESTRICT error) when any account still
references it.
"""
from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision = 'b483e2b8a6d2'
down_revision = 'af8254074bef'
branch_labels = None
depends_on = None


# Idempotent seed for the Property account type.  Resolves the Asset
# category id by name in the same statement so no id is hardcoded.  ``ON
# CONFLICT DO NOTHING`` (no target) no-ops on any unique violation,
# including the partial ``uq_account_types_seeded_name`` index, so a
# re-run -- or the deploy seed upsert touching the same row -- inserts
# nothing extra.
_SEED_PROPERTY_TYPE_SQL = (
    "INSERT INTO ref.account_types "
    "    (name, category_id, has_parameters, has_amortization, has_interest, "
    "     is_pretax, is_liquid, has_appreciation, icon_class, user_id) "
    "SELECT 'Property', c.id, true, false, false, false, false, true, "
    "       'bi-houses', NULL "
    "  FROM ref.account_type_categories c "
    " WHERE c.name = 'Asset' "
    "ON CONFLICT DO NOTHING"
)


def upgrade():
    """Add the has_appreciation flag, params table, Property seed, link."""
    # ── Step 1: has_appreciation flag (before the Property seed) ─────
    op.add_column(
        'account_types',
        sa.Column(
            'has_appreciation', sa.Boolean(),
            server_default=sa.text('false'), nullable=False,
        ),
        schema='ref',
    )

    # ── Step 2: the one-to-one appreciation params table ────────────
    op.create_table(
        'asset_appreciation_params',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.Column(
            'annual_appreciation_rate', sa.Numeric(precision=7, scale=5),
            nullable=False,
        ),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=False,
        ),
        sa.Column(
            'updated_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=False,
        ),
        sa.CheckConstraint(
            'annual_appreciation_rate > -1 AND annual_appreciation_rate <= 1',
            name='ck_asset_appreciation_params_valid_rate',
        ),
        # Unnamed FK: the convention-default ``<table>_account_id_fkey``
        # name matches ``db.create_all()`` for the
        # ``AccountScopedUniqueMixin`` account_id (the same shape
        # ``loan_params`` / ``investment_params`` use), so the migrated
        # schema and the model converge.
        sa.ForeignKeyConstraint(
            ['account_id'], ['budget.accounts.id'], ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('account_id'),
        schema='budget',
    )

    # ── Step 3: attach the audit trigger for the new table ──────────
    op.execute(
        "DROP TRIGGER IF EXISTS audit_asset_appreciation_params "
        "ON budget.asset_appreciation_params"
    )
    op.execute(
        "CREATE TRIGGER audit_asset_appreciation_params "
        "AFTER INSERT OR UPDATE OR DELETE ON budget.asset_appreciation_params "
        "FOR EACH ROW EXECUTE FUNCTION system.audit_trigger_func()"
    )

    # ── Step 4: seed the Property account type ──────────────────────
    op.execute(_SEED_PROPERTY_TYPE_SQL)

    # ── Step 5: the collateral self-link on accounts ────────────────
    op.add_column(
        'accounts',
        sa.Column('collateral_account_id', sa.Integer(), nullable=True),
        schema='budget',
    )
    op.create_foreign_key(
        'fk_accounts_collateral_account', 'accounts', 'accounts',
        ['collateral_account_id'], ['id'],
        source_schema='budget', referent_schema='budget', ondelete='SET NULL',
    )
    op.create_check_constraint(
        'ck_accounts_collateral_not_self', 'accounts',
        'collateral_account_id IS NULL OR collateral_account_id != id',
        schema='budget',
    )


def downgrade():
    """Reverse the mini-sprint schema changes.

    Drops the collateral link, the seeded Property type (guarded), the
    appreciation params table (cascading its audit trigger), and the
    has_appreciation flag, in inverse order of :func:`upgrade`.
    """
    # ── Inverse step 5: collateral self-link ────────────────────────
    op.drop_constraint(
        'ck_accounts_collateral_not_self', 'accounts',
        schema='budget', type_='check',
    )
    op.drop_constraint(
        'fk_accounts_collateral_account', 'accounts',
        schema='budget', type_='foreignkey',
    )
    op.drop_column('accounts', 'collateral_account_id', schema='budget')

    # ── Inverse step 4: delete the Property type (guarded) ──────────
    # The account_type_id FK is ON DELETE RESTRICT, so a referencing
    # account would surface a bare integrity error.  Pre-check and raise
    # a clear message naming the offending accounts instead.
    bind = op.get_bind()
    blocking = bind.execute(sa.text(
        "SELECT a.id FROM budget.accounts a "
        "  JOIN ref.account_types t ON t.id = a.account_type_id "
        " WHERE t.name = 'Property' AND t.user_id IS NULL"
    )).fetchall()
    if blocking:
        ids = ", ".join(str(row.id) for row in blocking)
        raise RuntimeError(
            "Cannot downgrade: the seeded 'Property' account type is still "
            f"referenced by account(s) [{ids}].  Reassign or delete those "
            "accounts, then re-run the downgrade."
        )
    bind.execute(sa.text(
        "DELETE FROM ref.account_types "
        " WHERE name = 'Property' AND user_id IS NULL"
    ))

    # ── Inverse step 2-3: params table (cascades its audit trigger) ─
    op.drop_table('asset_appreciation_params', schema='budget')

    # ── Inverse step 1: has_appreciation flag ───────────────────────
    op.drop_column('account_types', 'has_appreciation', schema='ref')
