"""create loan_anchor_events table for event-derived loan resolver (E-18)

Revision ID: d3d25212504b
Revises: cfb15e782f86
Create Date: 2026-05-20

Review: solo developer, 2026-05-20 (audit financial_calculations CRIT-02/E-18, new audited table)

CRIT-02 / F-014: ``budget.loan_params.current_principal`` has zero
settle-driven writers in the codebase
(``grep -rEn '\\.current_principal\\s*=[^=]' app/ scripts/`` -> empty),
so confirmed PITI transfers never reduce it.  E-18 (decision D-A)
makes the loan principal event-derived: the resolver (Commit 13)
replays confirmed payments forward from the latest row in
:class:`budget.loan_anchor_events`.  This migration creates the
append-only table that backs the resolver and seeds it for every
existing loan account so the resolver reproduces today's displayed
principal exactly on first run -- no visible jump for the user.

The forward migration is composed of five steps:

  1. **Create ref.loan_anchor_sources** -- two-row reference table
     tagging every event row with its provenance
     (``origination`` / ``user_trueup``).  Seeded inline because
     downstream backfill in step 5 needs the source IDs in the same
     migration; ``seed_reference_data`` runs from the entrypoint
     after migrations and would not be visible to step 5.

  2. **Create budget.loan_anchor_events** -- the append-only event
     log.  Columns and constraints match the SQLAlchemy model
     declaration in ``app/models/loan_anchor_event.py``; this
     migration's autogenerated DDL was hand-checked against that
     module so a future ``flask db migrate --autogenerate`` produces
     an empty diff.

  3. **Attach the audit trigger** -- manual DROP TRIGGER IF EXISTS
     + CREATE TRIGGER for just the new table, following the C-28
     precedent (commit ``d477228fee56``).  Calling
     ``apply_audit_infrastructure`` here would work today but breaks
     a fresh-DB migration replay: the rebuild migration
     ``a5be2a99ea14`` is earlier in the chain and runs the SAME
     ``apply_audit_infrastructure`` against the CURRENT in-code
     ``AUDITED_TABLES`` -- which (after this commit) already
     references ``budget.loan_anchor_events``, a table that does
     not exist at that earlier point.  The narrow manual attach
     here keeps every prior migration replayable without modification.
     The entrypoint trigger-count health check picks up the new
     total automatically because
     ``EXPECTED_TRIGGER_COUNT = len(AUDITED_TABLES)``.

  4. **Backfill origination events** -- for every loan account
     (``account_type.has_amortization = True`` AND a LoanParams row
     exists), insert exactly one ``(origination_date,
     original_principal, source=origination)`` event.  The derivation
     is reproducible: those two fields are immutable on LoanParams
     by design.  Idempotent via ``WHERE NOT EXISTS`` on the natural
     ``(account_id, source=origination)`` shape so the migration is
     safe to re-run after a partial failure.

  5. **Backfill user_trueup events when stored differs from replay**
     -- this is the "display continuity" half of decision D-A.  Two
     classes of loan need a trueup so the resolver's first read
     matches the dashboard's current display:

     * **ARM loans:** the from-origination replay would have to use
       the current rate as a proxy for every historical month
       (rate history is partial or absent in production), which
       diverges from reality.  Symptom #3 verifies this: an ARM
       stored at $300,000.00 never moved through four settled
       transfers even though the expected post-transfer balance was
       $299,611.64.  The pragmatic backfill is a dated trueup at
       ``(today, current_principal)`` so the resolver projects
       forward from the user-verified value.

     * **Fixed-rate loans where stored != replay:** the from-
       origination replay using the original rate and term is
       mathematically exact, so a divergence here means the operator
       manually edited ``current_principal`` via the dashboard form
       at some point.  The trueup preserves that manual override
       through the Commit 15 cutover.

     Fixed-rate loans whose stored ``current_principal`` already
     matches the from-origination replay get no trueup row -- the
     origination event alone suffices, and adding a trueup would
     just clutter the audit trail.

Backfill replay helper:

The plan's Commit 12 specification notes ``you may use the existing
debt_strategy._compute_real_principal for the fixed-rate comparison
since the loan resolver does not exist yet`` -- but that helper
short-circuits for ARMs (returns the stored value as-is) and falls
back to the stored value for fixed-rate loans with no payment
history, both of which would erase the divergence signal this
backfill depends on.  Instead, the migration ships a small
:func:`_replay_from_origination_inline` pure-math helper plus the
:func:`_replay_from_origination` wrapper that fetches payment rows
via raw SQL against ``budget.transactions`` and feeds them through
the inline replay.  The replay applies uniformly to ARM and
fixed-rate loans; the ARM-as-trueup classification falls out of the
divergence rule rather than a special case.

The inline replay was originally a delegated call to the
amortization engine's legacy schedule function; Commit 8 of the
amortization-engine split implementation
(``docs/plans/2026-05-21-amortization-engine-split-implementation.md``)
inlined the math so this migration survives the Commit 9 deletion
of that legacy function.  The inline reproduces the engine's
confirmed-payment + contractual-fallback per-month logic for the
exact input shape the migration uses (confirmed-and-projected
payments, no ``extra_monthly``, no rate changes, no anchor) and
preserves the original "balance after the last confirmed row"
semantic (see the ``last_confirmed_balance`` capture in the inline
helper).

**Self-contained dependency policy.** This migration intentionally
imports nothing from :mod:`app` -- not models, not services, not
``ref_cache``.  All schema reads (loan enumeration, scenario lookup,
shadow-income payment history) go through raw SQL against the
catalog this migration is itself constructing.  The original draft
of this migration imported
:mod:`app.services.loan_payment_service` and :mod:`app.models.*`,
which produced a circular bootstrap deadlock: ``ref_cache.init()``
needed ``ref.loan_anchor_sources`` (a table this migration creates),
and ``loan_payment_service.get_payment_history()`` needed
``ref_cache.txn_type_id(INCOME)`` to run.  Migrations must not
depend on application services -- they live forever, run at
fragile lifecycle moments, and must survive aggressive refactors
in app code.

Downgrade drops the trigger, drops the table, and drops the ref
table.  Reversible because the backfill is reproducible from
immutable LoanParams data on the next upgrade.  Backfilled rows are
NOT preserved across the downgrade because the table itself is
dropped; an operator who rolls back and re-applies the migration
will see the same events materialised again (and the
``apply_audit_infrastructure`` step will re-attach the trigger so
the new INSERTs are captured).
"""

from datetime import date
from decimal import Decimal, ROUND_HALF_UP

import sqlalchemy as sa
from alembic import op



# Revision identifiers, used by Alembic.
revision = "d3d25212504b"
down_revision = "cfb15e782f86"
branch_labels = None
depends_on = None


# Ref-table seed values.  Inserted inline (not via
# ``seed_reference_data``) so the IDs are available to step 5 below
# inside the same migration transaction.  ``ON CONFLICT DO NOTHING``
# keeps the migration idempotent if a partial earlier run already
# inserted the rows.
_REF_SEED_SQL = (
    "INSERT INTO ref.loan_anchor_sources (name) VALUES "
    "('origination'), ('user_trueup') "
    "ON CONFLICT (name) DO NOTHING"
)


# Backfill SQL for the origination event.  One row per loan account
# (``has_amortization`` AccountType with a LoanParams row), inserted
# only when a matching origination row does not already exist.  The
# ``NOT EXISTS`` guard makes step 4 idempotent against partial
# earlier runs.  Mirrors the ``cfb15e782f86`` migration's
# ``INSERT_HISTORY_SQL`` shape so the project's two append-only
# anchor tables stay structurally parallel.
_BACKFILL_ORIGINATION_SQL = (
    "INSERT INTO budget.loan_anchor_events "
    "    (account_id, anchor_date, anchor_balance, source_id) "
    "SELECT lp.account_id, lp.origination_date, lp.original_principal, "
    "       (SELECT id FROM ref.loan_anchor_sources "
    "         WHERE name = 'origination') "
    "  FROM budget.loan_params lp "
    "  JOIN budget.accounts a ON a.id = lp.account_id "
    "  JOIN ref.account_types t ON t.id = a.account_type_id "
    " WHERE t.has_amortization = TRUE "
    "   AND NOT EXISTS ( "
    "     SELECT 1 FROM budget.loan_anchor_events ev "
    "      JOIN ref.loan_anchor_sources s ON s.id = ev.source_id "
    "      WHERE ev.account_id = lp.account_id "
    "        AND s.name = 'origination' "
    "   )"
)


# Raw SQL for shadow-income payment history on a debt account.  Mirrors
# the ORM query in ``app.services.loan_payment_service.get_payment_history``
# but joins ref tables directly so the migration does not depend on
# ``ref_cache`` (which is itself bootstrapping when this migration runs)
# or on the application service (which lives above the migration layer
# and may be refactored or removed).  String-name lookups on
# ``ref.transaction_types`` and ``ref.statuses`` are acceptable inside
# migrations -- the "IDs for logic, strings for display only" rule
# applies to application code, not to schema-bootstrap migrations
# which run below the ref-cache layer.  Both rows have been seeded
# since the initial migration.
_PAYMENT_HISTORY_SQL = (
    "SELECT pp.start_date AS payment_date, "
    "       COALESCE(t.actual_amount, t.estimated_amount) AS amount, "
    "       s.is_settled AS is_confirmed "
    "  FROM budget.transactions t "
    "  JOIN budget.pay_periods pp ON pp.id = t.pay_period_id "
    "  JOIN ref.statuses s ON s.id = t.status_id "
    "  JOIN ref.transaction_types tt ON tt.id = t.transaction_type_id "
    " WHERE t.account_id = :acct "
    "   AND t.scenario_id = :scen "
    "   AND t.transfer_id IS NOT NULL "
    "   AND tt.name = 'Income' "
    "   AND t.is_deleted = FALSE "
    "   AND s.excludes_from_balance = FALSE "
    " ORDER BY pp.start_date"
)


# Raw SQL for enumerating every loan account.  Selects the LoanParams
# columns the replay needs plus the user_id from the joined account.
# Reproduces the ORM-side filter (``account_type.has_amortization``)
# inline so the migration sees the same loan set the application
# would.
_LOAN_ENUMERATION_SQL = (
    "SELECT lp.account_id, lp.original_principal, lp.interest_rate, "
    "       lp.term_months, lp.origination_date, lp.payment_day, "
    "       lp.current_principal, lp.is_arm, a.user_id "
    "  FROM budget.loan_params lp "
    "  JOIN budget.accounts a ON a.id = lp.account_id "
    "  JOIN ref.account_types t ON t.id = a.account_type_id "
    " WHERE t.has_amortization = TRUE "
    " ORDER BY lp.account_id"
)


# Raw SQL for the user's baseline scenario id.  Returns ``None`` for
# a user with no baseline scenario (e.g. a brand-new account with no
# budget set up yet), in which case the payment list is empty.
_BASELINE_SCENARIO_SQL = (
    "SELECT id FROM budget.scenarios "
    " WHERE user_id = :u AND is_baseline = TRUE "
    " LIMIT 1"
)


_TWO_PLACES = Decimal("0.01")


def _replay_from_origination_inline(
    *,
    original_principal: Decimal,
    annual_rate: Decimal,
    term_months: int,
    origination_date: date,
    payments: list[tuple[date, Decimal, bool]],
) -> Decimal:
    """Replay shadow-income history forward from origination, in pure math.

    Reproduces the subset of the legacy
    ``app.services`` schedule function the migration needs
    (confirmed-and-projected payments, no ``extra_monthly``, no
    rate changes, no anchor) and returns the running balance
    captured AFTER the last confirmed payment is applied.  When no
    confirmed payment row is encountered the helper returns
    ``original_principal`` -- matching the original
    ``for row in reversed(schedule): if row.is_confirmed`` walk
    that returned the stored origination value when the legacy
    schedule contained no confirmed rows.

    Inlined here so the migration is self-contained against the
    Commit 9 deletion of the legacy schedule function (see Commit 8
    of
    ``docs/plans/2026-05-21-amortization-engine-split-implementation.md``).
    The per-month math mirrors the legacy engine bit-for-bit for
    the migration's input shape; future drift between the engine
    and this helper is acceptable because the engine has many
    features (rate changes, anchors, ``extra_monthly``,
    ``monthly_override``) the migration intentionally does not
    need.

    Two per-month branches mirror the legacy engine's
    recorded-month branch and its contractual fallback:

    * **Month with a recorded payment.** Interest accrues on the
      running balance; principal portion is ``total_payment -
      interest`` (may be negative -- negative amortization is valid
      for an underpayment).  The balance is reduced by the
      principal portion, capped at zero on overpayment.  The
      post-update balance is captured as ``last_confirmed_balance``
      only when ALL payments contributing to the month-key are
      confirmed (mirroring the engine's
      ``confirmed_by_month[key] = confirmed_by_month[key] and ...``
      AND-reduction in ``_build_payment_lookups``).

    * **Month with no recorded payment.** Contractual fallback:
      principal portion is ``monthly_payment - interest`` where
      ``monthly_payment`` is the standard amortization formula
      evaluated at origination terms.  The final row absorbs the
      remaining balance exactly (mirrors the engine's
      ``is_final`` branch).  The balance change is real (the engine
      walked these months too) but ``last_confirmed_balance`` is
      NOT updated because the schedule row would have
      ``is_confirmed=False`` and the migration's
      ``reversed(schedule)`` walk skipped it.

    Loop cap matches the engine's ``using_contractual`` branch:
    ``2 * term_months`` (engine source's ``remaining_months +
    term_months`` with ``remaining_months == term_months`` from the
    migration's call site).  Termination on ``balance <= 0`` is the
    realistic exit; the cap exists to guarantee the loop halts.

    Args:
        original_principal: Loan amount at origination.  Returned
            verbatim when the loan is degenerate (``<= 0`` or zero
            term) or when no payment row is confirmed.
        annual_rate: Annual interest rate as a Decimal-coercible
            value (e.g. ``Decimal("0.065")`` for 6.5%).
        term_months: Original loan term in months.  Used both for
            the contractual-payment formula and as the loop cap.
        origination_date: Loan origination date.  Payments dated
            before this are filtered (mirrors the engine's
            pre-origination filter in
            ``_build_payment_lookups``).
        payments: ``(payment_date, amount, is_confirmed)`` tuples.
            Pre-origination entries are filtered.  Multiple entries
            sharing a ``(year, month)`` key are summed; the
            corresponding ``is_confirmed`` flag is AND-reduced
            across them.

    Returns:
        Decimal: balance after the last confirmed payment applied,
        or ``original_principal`` when no confirmed payment row was
        encountered.  Quantized to cents via ``ROUND_HALF_UP``.
    """
    orig_principal_dec = Decimal(str(original_principal))
    if orig_principal_dec <= 0 or term_months <= 0:
        return orig_principal_dec

    amount_by_month: dict[tuple[int, int], Decimal] = {}
    confirmed_by_month: dict[tuple[int, int], bool] = {}
    for pay_date, amount, is_confirmed in payments:
        if pay_date < origination_date:
            continue
        key = (pay_date.year, pay_date.month)
        amount_by_month[key] = (
            amount_by_month.get(key, Decimal("0")) + Decimal(str(amount))
        )
        if key in confirmed_by_month:
            confirmed_by_month[key] = confirmed_by_month[key] and is_confirmed
        else:
            confirmed_by_month[key] = is_confirmed

    if not amount_by_month:
        return orig_principal_dec

    annual_rate_dec = Decimal(str(annual_rate))
    monthly_rate = (
        annual_rate_dec / 12 if annual_rate_dec > 0 else Decimal("0")
    )

    if monthly_rate <= 0:
        monthly_payment = (orig_principal_dec / term_months).quantize(
            _TWO_PLACES, rounding=ROUND_HALF_UP,
        )
    else:
        factor = (Decimal("1") + monthly_rate) ** term_months
        monthly_payment = (
            orig_principal_dec * (monthly_rate * factor)
            / (factor - Decimal("1"))
        ).quantize(_TWO_PLACES, rounding=ROUND_HALF_UP)

    max_months = term_months * 2

    balance = orig_principal_dec
    last_confirmed_balance: Decimal | None = None

    pay_year = origination_date.year
    pay_month = origination_date.month + 1
    if pay_month > 12:
        pay_month = 1
        pay_year += 1

    for month_num in range(1, max_months + 1):
        if balance <= 0:
            break

        interest = (balance * monthly_rate).quantize(
            _TWO_PLACES, rounding=ROUND_HALF_UP,
        )
        month_key = (pay_year, pay_month)

        if month_key in amount_by_month:
            total_payment = amount_by_month[month_key]
            principal_portion = total_payment - interest
            if principal_portion >= balance:
                balance = Decimal("0.00")
            else:
                balance = (balance - principal_portion).quantize(
                    _TWO_PLACES, rounding=ROUND_HALF_UP,
                )
                if balance < 0:
                    balance = Decimal("0.00")
            if confirmed_by_month[month_key]:
                last_confirmed_balance = balance
        else:
            principal_portion = monthly_payment - interest
            is_final = (
                principal_portion >= balance or month_num == max_months
            )
            if is_final:
                balance = Decimal("0.00")
            else:
                balance = (balance - principal_portion).quantize(
                    _TWO_PLACES, rounding=ROUND_HALF_UP,
                )
                if balance < 0:
                    balance = Decimal("0.00")

        if balance <= 0:
            break

        pay_month += 1
        if pay_month > 12:
            pay_month = 1
            pay_year += 1

    if last_confirmed_balance is None:
        return orig_principal_dec
    return last_confirmed_balance


def _replay_from_origination(
    connection, account_id, scenario_id, original_principal,
    interest_rate, term_months, origination_date,
):
    """Fetch shadow-income payment history and replay it from origination.

    Thin wrapper around :func:`_replay_from_origination_inline`:
    this function owns the raw-SQL fetch against
    ``budget.transactions`` (via :data:`_PAYMENT_HISTORY_SQL`) and
    delegates the pure-math replay to the inline helper.  Returns
    the ``remaining_balance`` after the last confirmed payment, or
    ``original_principal`` when no confirmed payments exist.

    Differs from ``debt_strategy._compute_real_principal`` on two
    counts: it does NOT short-circuit for ARMs (the divergence
    signal is the whole point of the backfill), and it does NOT
    fall back to stored ``current_principal`` (which would erase
    divergence for a fixed-rate loan with no payments).  Once the
    loan resolver lands in a future commit, migrations could
    delegate to it; this helper is intentionally local so this
    migration does not depend on code that may be refactored
    beneath it.

    All loan attributes are passed as primitives rather than via
    an ORM ``LoanParams`` instance so the migration does not need
    to import :mod:`app.models.loan_params` -- migrations must
    not depend on app code that may be refactored beneath them.

    Args:
        connection: SQLAlchemy bind from ``op.get_bind()`` for the
            payment-history SQL query.
        account_id: Debt account id for the payment lookup.
        scenario_id: Baseline scenario ID for the payment lookup.
            ``None`` means no payments are loaded (e.g. a brand-new
            user with no scenario yet).
        original_principal: Decimal-coercible loan original principal.
        interest_rate: Decimal-coercible annual interest rate.
        term_months: Integer loan term in months.
        origination_date: ``date`` the loan originated.

    Returns:
        Decimal: from-origination balance after replaying confirmed
        payments, in storage precision (Numeric(12,2) quantized).
    """
    orig_principal = Decimal(str(original_principal))
    rate = Decimal(str(interest_rate))

    if scenario_id is None:
        return orig_principal

    payment_rows = connection.execute(
        sa.text(_PAYMENT_HISTORY_SQL),
        {"acct": account_id, "scen": scenario_id},
    ).fetchall()

    if not payment_rows:
        return orig_principal

    payments = [
        (row.payment_date, Decimal(str(row.amount)), row.is_confirmed)
        for row in payment_rows
    ]

    return _replay_from_origination_inline(
        original_principal=orig_principal,
        annual_rate=rate,
        term_months=term_months,
        origination_date=origination_date,
        payments=payments,
    )


def _backfill_trueup_events(connection):
    """Insert a user_trueup event for every loan whose stored value diverges.

    Two classes of loan qualify (see the module docstring's step 5
    for the full rationale):

    * **ARM loans** -- always.  The from-origination replay using
      the current rate as a proxy for absent historical rate data
      is meaningless, so the dated trueup at
      ``(today, current_principal)`` is the only sane way to
      preserve the operator's displayed value through the Commit 15
      resolver cutover.

    * **Fixed-rate loans** -- only when
      :func:`_replay_from_origination` yields a balance different
      from the stored ``current_principal``.  A match means the
      origination event alone reproduces today's display; a mismatch
      means the operator hand-edited ``current_principal`` and the
      trueup preserves that edit.

    Idempotent via a same-day duplicate check against the unique
    functional index ``uq_loan_anchor_events_acct_date_bal_day``:
    if a same-day trueup with the same balance already exists, the
    INSERT is skipped.  Re-running the migration after a partial
    earlier run will not create duplicates.

    Uses raw SQL (no ORM ``Session``, no application models) so the
    migration is self-contained.  See module docstring "Self-contained
    dependency policy" for the rationale.

    Args:
        connection: SQLAlchemy bind from ``op.get_bind()``.

    Returns:
        list[tuple[int, str]]: ``(account_id, reason)`` for every
        trueup that was inserted.  Reasons: ``arm`` (always-true
        for ARMs) or ``fixed_divergence`` (fixed-rate replay
        diverged from stored).  Returned for the migration's own
        diagnostic logging and for test introspection.
    """
    today = date.today()
    inserted = []

    trueup_source_id = connection.execute(sa.text(
        "SELECT id FROM ref.loan_anchor_sources WHERE name = 'user_trueup'"
    )).scalar()

    # Walk every loan account via raw SQL.  ``has_amortization`` filter
    # mirrors the ORM-side semantics used by the production loan
    # resolver in Commit 13.
    loan_rows = connection.execute(sa.text(_LOAN_ENUMERATION_SQL)).fetchall()

    for loan in loan_rows:
        scenario_id = connection.execute(
            sa.text(_BASELINE_SCENARIO_SQL), {"u": loan.user_id},
        ).scalar()

        stored = Decimal(str(loan.current_principal))

        replay_balance = _replay_from_origination(
            connection=connection,
            account_id=loan.account_id,
            scenario_id=scenario_id,
            original_principal=loan.original_principal,
            interest_rate=loan.interest_rate,
            term_months=loan.term_months,
            origination_date=loan.origination_date,
        )

        if loan.is_arm:
            if replay_balance == stored:
                # The rare ARM whose stored value happens to match
                # the from-origination replay (e.g. brand-new ARM at
                # origination with no payments and current ==
                # original).  Origination event alone suffices; no
                # trueup needed.
                continue
            reason = "arm"
        else:
            if replay_balance == stored:
                continue
            reason = "fixed_divergence"

        # Same-day duplicate guard: the unique functional index
        # rejects literal duplicates but allows the same account
        # to receive two different trueups on the same day.  This
        # guard prevents a re-run from doubling the trueup row
        # for an account whose stored value has not changed.
        already = connection.execute(sa.text(
            "SELECT 1 FROM budget.loan_anchor_events "
            " WHERE account_id = :a "
            "   AND anchor_date = :d "
            "   AND anchor_balance = :b "
            "   AND ((created_at AT TIME ZONE 'UTC')::date) = "
            "       (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::date "
            " LIMIT 1"
        ), {"a": loan.account_id, "d": today, "b": stored}).scalar()
        if already:
            continue

        connection.execute(sa.text(
            "INSERT INTO budget.loan_anchor_events "
            "  (account_id, anchor_date, anchor_balance, source_id) "
            "VALUES (:a, :d, :b, :s)"
        ), {
            "a": loan.account_id,
            "d": today,
            "b": stored,
            "s": trueup_source_id,
        })
        inserted.append((loan.account_id, reason))

    return inserted


def upgrade():
    """Create the anchor-event table + ref source + audit trigger; backfill.

    Five-step forward migration (see module docstring for the full
    rationale).  Every step is idempotent so the migration can re-run
    after a partial failure without duplicating rows or triggers.
    """
    # ── Step 1: ref.loan_anchor_sources ─────────────────────────────
    op.create_table(
        "loan_anchor_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="ref",
    )
    op.execute(_REF_SEED_SQL)

    # ── Step 2: budget.loan_anchor_events ───────────────────────────
    op.create_table(
        "loan_anchor_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("anchor_date", sa.Date(), nullable=False),
        sa.Column(
            "anchor_balance", sa.Numeric(precision=12, scale=2),
            nullable=False,
        ),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False,
        ),
        sa.CheckConstraint(
            "anchor_balance >= 0",
            name="ck_loan_anchor_events_balance_nonneg",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["budget.accounts.id"], ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["ref.loan_anchor_sources.id"],
            name="fk_loan_anchor_events_source_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="budget",
    )
    op.create_index(
        "idx_loan_anchor_events_account",
        "loan_anchor_events", ["account_id", "anchor_date"],
        unique=False, schema="budget",
    )
    op.create_index(
        "uq_loan_anchor_events_acct_date_bal_day",
        "loan_anchor_events",
        [
            "account_id", "anchor_date", "anchor_balance",
            sa.literal_column("((created_at AT TIME ZONE 'UTC')::date)"),
        ],
        unique=True, schema="budget",
    )

    # ── Step 3: attach the audit trigger ────────────────────────────
    # The shared trigger function ``system.audit_trigger_func`` is
    # already in place from the rebuild migration
    # (``a5be2a99ea14``); attaching a row-level trigger to the new
    # table is all that is needed to start logging mutations.  The
    # DROP IF EXISTS pair makes the step idempotent against a re-run
    # of this migration.  Trigger name ``audit_<table>`` matches the
    # convention enumerated by the entrypoint trigger-count health
    # check.
    op.execute(
        "DROP TRIGGER IF EXISTS audit_loan_anchor_events "
        "ON budget.loan_anchor_events"
    )
    op.execute(
        "CREATE TRIGGER audit_loan_anchor_events "
        "AFTER INSERT OR UPDATE OR DELETE ON budget.loan_anchor_events "
        "FOR EACH ROW EXECUTE FUNCTION system.audit_trigger_func()"
    )

    # ── Step 4: backfill origination events ─────────────────────────
    op.execute(_BACKFILL_ORIGINATION_SQL)

    # ── Step 5: backfill conditional user_trueup events ─────────────
    bind = op.get_bind()
    _backfill_trueup_events(bind)


def downgrade():
    """Drop the trigger, table, and ref values.

    Reversible because the backfill is fully reproducible from
    immutable LoanParams data on the next upgrade.  The audit trail
    of the upgrade's INSERTs remains in ``system.audit_log`` -- the
    DELETE row produced by the table-drop CASCADE is captured by
    the trigger before the trigger itself is removed, so the
    forensic record survives the rollback.
    """
    # Inverse drop order.  PostgreSQL's DROP TABLE cascades the
    # row-level trigger as a dependent object so an explicit DROP
    # TRIGGER is not required; the other 30 audit triggers (on
    # surviving tables in AUDITED_TABLES) and the shared trigger
    # function ``system.audit_trigger_func`` stay attached untouched.
    op.drop_index(
        "uq_loan_anchor_events_acct_date_bal_day",
        table_name="loan_anchor_events", schema="budget",
    )
    op.drop_index(
        "idx_loan_anchor_events_account",
        table_name="loan_anchor_events", schema="budget",
    )
    op.drop_table("loan_anchor_events", schema="budget")
    op.drop_table("loan_anchor_sources", schema="ref")
