"""create loan_anchor_events table for event-derived loan resolver (E-18)

Revision ID: d3d25212504b
Revises: cfb15e782f86
Create Date: 2026-05-20

Review: solo developer, 2026-05-20 (audit financial_calculations CRIT-02/E-18, new audited table)

CRIT-02 / F-014: ``budget.loan_params.current_principal`` has zero
settle-driven writers in the codebase
(``grep -rEn '\\.current_principal\\s*=[^=]' app/ scripts/`` -> empty),
so confirmed PITI transfers never reduce it.  E-18 (decision D-A)
makes the loan principal event-derived: the resolver (Commit 13)
replays confirmed payments forward from the latest row in
:class:`budget.loan_anchor_events`.  This migration creates the
append-only table that backs the resolver and seeds it for every
existing loan account so the resolver reproduces today's displayed
principal exactly on first run -- no visible jump for the user.

The forward migration is composed of five steps:

  1. **Create ref.loan_anchor_sources** -- two-row reference table
     tagging every event row with its provenance
     (``origination`` / ``user_trueup``).  Seeded inline because
     downstream backfill in step 5 needs the source IDs in the same
     migration; ``seed_reference_data`` runs from the entrypoint
     after migrations and would not be visible to step 5.

  2. **Create budget.loan_anchor_events** -- the append-only event
     log.  Columns and constraints match the SQLAlchemy model
     declaration in ``app/models/loan_anchor_event.py``; this
     migration's autogenerated DDL was hand-checked against that
     module so a future ``flask db migrate --autogenerate`` produces
     an empty diff.

  3. **Attach the audit trigger** -- manual DROP TRIGGER IF EXISTS
     + CREATE TRIGGER for just the new table, following the C-28
     precedent (commit ``d477228fee56``).  Calling
     ``apply_audit_infrastructure`` here would work today but breaks
     a fresh-DB migration replay: the rebuild migration
     ``a5be2a99ea14`` is earlier in the chain and runs the SAME
     ``apply_audit_infrastructure`` against the CURRENT in-code
     ``AUDITED_TABLES`` -- which (after this commit) already
     references ``budget.loan_anchor_events``, a table that does
     not exist at that earlier point.  The narrow manual attach
     here keeps every prior migration replayable without modification.
     The entrypoint trigger-count health check picks up the new
     total automatically because
     ``EXPECTED_TRIGGER_COUNT = len(AUDITED_TABLES)``.

  4. **Backfill origination events** -- for every loan account
     (``account_type.has_amortization = True`` AND a LoanParams row
     exists), insert exactly one ``(origination_date,
     original_principal, source=origination)`` event.  The derivation
     is reproducible: those two fields are immutable on LoanParams
     by design.  Idempotent via ``WHERE NOT EXISTS`` on the natural
     ``(account_id, source=origination)`` shape so the migration is
     safe to re-run after a partial failure.

  5. **Backfill user_trueup events when stored differs from replay**
     -- this is the "display continuity" half of decision D-A.  Two
     classes of loan need a trueup so the resolver's first read
     matches the dashboard's current display:

     * **ARM loans:** the from-origination replay would have to use
       the current rate as a proxy for every historical month
       (rate history is partial or absent in production), which
       diverges from reality.  Symptom #3 verifies this: an ARM
       stored at $300,000.00 never moved through four settled
       transfers even though the expected post-transfer balance was
       $299,611.64.  The pragmatic backfill is a dated trueup at
       ``(today, current_principal)`` so the resolver projects
       forward from the user-verified value.

     * **Fixed-rate loans where stored != replay:** the from-
       origination replay using the original rate and term is
       mathematically exact, so a divergence here means the operator
       manually edited ``current_principal`` via the dashboard form
       at some point.  The trueup preserves that manual override
       through the Commit 15 cutover.

     Fixed-rate loans whose stored ``current_principal`` already
     matches the from-origination replay get no trueup row -- the
     origination event alone suffices, and adding a trueup would
     just clutter the audit trail.

Backfill replay helper:

The plan's Commit 12 specification notes ``you may use the existing
debt_strategy._compute_real_principal for the fixed-rate comparison
since the loan resolver does not exist yet`` -- but that helper
short-circuits for ARMs (returns the stored value as-is) and falls
back to the stored value for fixed-rate loans with no payment
history, both of which would erase the divergence signal this
backfill depends on.  Instead, the migration ships a small
:func:`_replay_from_origination` helper that runs the same engine
(:mod:`app.services.amortization_engine`) with payments from the
existing :func:`app.services.loan_payment_service.get_payment_history`
shadow-income feed.  The helper applies uniformly to ARM and fixed-
rate loans; the ARM-as-trueup classification falls out of the
divergence rule rather than a special case.  Once the loan resolver
lands in Commit 13, future backfill or migration code should
delegate to that resolver instead of recomputing the replay here.

Downgrade drops the trigger, drops the table, and drops the ref
table.  Reversible because the backfill is reproducible from
immutable LoanParams data on the next upgrade.  Backfilled rows are
NOT preserved across the downgrade because the table itself is
dropped; an operator who rolls back and re-applies the migration
will see the same events materialised again (and the
``apply_audit_infrastructure`` step will re-attach the trigger so
the new INSERTs are captured).
"""

from datetime import date
from decimal import Decimal

import sqlalchemy as sa
from alembic import op



# Revision identifiers, used by Alembic.
revision = "d3d25212504b"
down_revision = "cfb15e782f86"
branch_labels = None
depends_on = None


# Ref-table seed values.  Inserted inline (not via
# ``seed_reference_data``) so the IDs are available to step 5 below
# inside the same migration transaction.  ``ON CONFLICT DO NOTHING``
# keeps the migration idempotent if a partial earlier run already
# inserted the rows.
_REF_SEED_SQL = (
    "INSERT INTO ref.loan_anchor_sources (name) VALUES "
    "('origination'), ('user_trueup') "
    "ON CONFLICT (name) DO NOTHING"
)


# Backfill SQL for the origination event.  One row per loan account
# (``has_amortization`` AccountType with a LoanParams row), inserted
# only when a matching origination row does not already exist.  The
# ``NOT EXISTS`` guard makes step 4 idempotent against partial
# earlier runs.  Mirrors the ``cfb15e782f86`` migration's
# ``INSERT_HISTORY_SQL`` shape so the project's two append-only
# anchor tables stay structurally parallel.
_BACKFILL_ORIGINATION_SQL = (
    "INSERT INTO budget.loan_anchor_events "
    "    (account_id, anchor_date, anchor_balance, source_id) "
    "SELECT lp.account_id, lp.origination_date, lp.original_principal, "
    "       (SELECT id FROM ref.loan_anchor_sources "
    "         WHERE name = 'origination') "
    "  FROM budget.loan_params lp "
    "  JOIN budget.accounts a ON a.id = lp.account_id "
    "  JOIN ref.account_types t ON t.id = a.account_type_id "
    " WHERE t.has_amortization = TRUE "
    "   AND NOT EXISTS ( "
    "     SELECT 1 FROM budget.loan_anchor_events ev "
    "      JOIN ref.loan_anchor_sources s ON s.id = ev.source_id "
    "      WHERE ev.account_id = lp.account_id "
    "        AND s.name = 'origination' "
    "   )"
)


def _replay_from_origination(loan_params, scenario_id):
    """Replay confirmed payments through the amortization engine.

    Runs the full life-of-loan schedule from
    ``original_principal`` at ``origination_date`` with the loan's
    stored ``interest_rate``, replaying every confirmed shadow
    income transaction (the source the resolver in Commit 13 will
    also consume).  Returns the ``remaining_balance`` of the last
    confirmed row, or ``original_principal`` when no confirmed
    payments exist.

    Differs from ``debt_strategy._compute_real_principal`` on two
    counts: it does NOT short-circuit for ARMs (the divergence
    signal is the whole point of the backfill), and it does NOT
    fall back to stored ``current_principal`` (which would erase
    divergence for a fixed-rate loan with no payments).  Once the
    loan resolver lands in Commit 13, future migrations should
    delegate to it; this helper is intentionally local so Commit 12
    does not depend on code that does not yet exist.

    Args:
        loan_params: ORM ``LoanParams`` instance.
        scenario_id: Baseline scenario ID for the payment lookup.
            ``None`` means no payments are loaded (e.g. a brand-new
            user with no scenario yet).

    Returns:
        Decimal: from-origination balance after replaying confirmed
        payments, in storage precision (Numeric(12,2) quantized by
        the engine).
    """
    # pylint: disable=import-outside-toplevel
    from app.services import amortization_engine
    from app.services.loan_payment_service import get_payment_history

    orig_principal = Decimal(str(loan_params.original_principal))
    rate = Decimal(str(loan_params.interest_rate))

    payments = (
        get_payment_history(loan_params.account_id, scenario_id)
        if scenario_id is not None
        else []
    )

    if not payments:
        return orig_principal

    schedule = amortization_engine.generate_schedule(
        current_principal=orig_principal,
        annual_rate=rate,
        remaining_months=loan_params.term_months,
        origination_date=loan_params.origination_date,
        payment_day=loan_params.payment_day,
        original_principal=orig_principal,
        term_months=loan_params.term_months,
        payments=payments,
    )

    for row in reversed(schedule):
        if row.is_confirmed:
            return row.remaining_balance
    return orig_principal


def _backfill_trueup_events(connection):
    """Insert a user_trueup event for every loan whose stored value diverges.

    Two classes of loan qualify (see the module docstring's step 5
    for the full rationale):

    * **ARM loans** -- always.  The from-origination replay using
      the current rate as a proxy for absent historical rate data
      is meaningless, so the dated trueup at
      ``(today, current_principal)`` is the only sane way to
      preserve the operator's displayed value through the Commit 15
      resolver cutover.

    * **Fixed-rate loans** -- only when
      :func:`_replay_from_origination` yields a balance different
      from the stored ``current_principal``.  A match means the
      origination event alone reproduces today's display; a mismatch
      means the operator hand-edited ``current_principal`` and the
      trueup preserves that edit.

    Idempotent via a same-day duplicate check against the unique
    functional index ``uq_loan_anchor_events_acct_date_bal_day``:
    if a same-day trueup with the same balance already exists, the
    INSERT is skipped.  Re-running the migration after a partial
    earlier run will not create duplicates.

    Args:
        connection: SQLAlchemy bind from ``op.get_bind()``.

    Returns:
        list[tuple[int, str]]: ``(account_id, reason)`` for every
        trueup that was inserted.  Reasons: ``arm`` (always-true
        for ARMs) or ``fixed_divergence`` (fixed-rate replay
        diverged from stored).  Returned for the migration's own
        diagnostic logging and for test introspection.
    """
    # pylint: disable=import-outside-toplevel
    from app.models.loan_params import LoanParams
    from app.models.scenario import Scenario
    from sqlalchemy.orm import Session

    today = date.today()
    inserted = []

    # The migration runs inside Alembic's own transaction; binding a
    # Session to ``connection`` reuses that transaction so ORM
    # operations roll back with the migration on error.
    session = Session(bind=connection)
    try:
        trueup_source_id = connection.execute(sa.text(
            "SELECT id FROM ref.loan_anchor_sources WHERE name = 'user_trueup'"
        )).scalar()

        # Walk every loan account.  ``LoanParams.account_id`` carries
        # the user join via Account; we iterate the params rows and
        # look up the user's baseline scenario for the payment feed.
        params_rows = (
            session.query(LoanParams)
            .order_by(LoanParams.account_id)
            .all()
        )

        for params in params_rows:
            account = params.account  # eagerly resolves via FK
            user_id = account.user_id

            baseline = (
                session.query(Scenario)
                .filter_by(user_id=user_id, is_baseline=True)
                .first()
            )
            scenario_id = baseline.id if baseline is not None else None

            stored = Decimal(str(params.current_principal))

            if params.is_arm:
                replay_balance = _replay_from_origination(params, scenario_id)
                if replay_balance == stored:
                    # The rare ARM whose stored value happens to
                    # match the from-origination replay (e.g. brand-
                    # new ARM at origination with no payments and
                    # current == original).  Origination event alone
                    # suffices; no trueup needed.
                    continue
                reason = "arm"
            else:
                replay_balance = _replay_from_origination(params, scenario_id)
                if replay_balance == stored:
                    continue
                reason = "fixed_divergence"

            # Same-day duplicate guard: the unique functional index
            # rejects literal duplicates but allows the same account
            # to receive two different trueups on the same day.  This
            # guard prevents a re-run from doubling the trueup row
            # for an account whose stored value has not changed.
            already = connection.execute(sa.text(
                "SELECT 1 FROM budget.loan_anchor_events "
                " WHERE account_id = :a "
                "   AND anchor_date = :d "
                "   AND anchor_balance = :b "
                "   AND ((created_at AT TIME ZONE 'UTC')::date) = "
                "       (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::date "
                " LIMIT 1"
            ), {"a": params.account_id, "d": today, "b": stored}).scalar()
            if already:
                continue

            connection.execute(sa.text(
                "INSERT INTO budget.loan_anchor_events "
                "  (account_id, anchor_date, anchor_balance, source_id) "
                "VALUES (:a, :d, :b, :s)"
            ), {
                "a": params.account_id,
                "d": today,
                "b": stored,
                "s": trueup_source_id,
            })
            inserted.append((params.account_id, reason))
    finally:
        # Do not close the bind-bound session; closing would commit
        # the migration's open transaction prematurely.  ``Session``
        # objects bound to an external connection rely on the caller
        # for transaction control.
        session.close()

    return inserted


def upgrade():
    """Create the anchor-event table + ref source + audit trigger; backfill.

    Five-step forward migration (see module docstring for the full
    rationale).  Every step is idempotent so the migration can re-run
    after a partial failure without duplicating rows or triggers.
    """
    # ── Step 1: ref.loan_anchor_sources ─────────────────────────────
    op.create_table(
        "loan_anchor_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="ref",
    )
    op.execute(_REF_SEED_SQL)

    # ── Step 2: budget.loan_anchor_events ───────────────────────────
    op.create_table(
        "loan_anchor_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("anchor_date", sa.Date(), nullable=False),
        sa.Column(
            "anchor_balance", sa.Numeric(precision=12, scale=2),
            nullable=False,
        ),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False,
        ),
        sa.CheckConstraint(
            "anchor_balance >= 0",
            name="ck_loan_anchor_events_balance_nonneg",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["budget.accounts.id"], ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["ref.loan_anchor_sources.id"],
            name="fk_loan_anchor_events_source_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="budget",
    )
    op.create_index(
        "idx_loan_anchor_events_account",
        "loan_anchor_events", ["account_id", "anchor_date"],
        unique=False, schema="budget",
    )
    op.create_index(
        "uq_loan_anchor_events_acct_date_bal_day",
        "loan_anchor_events",
        [
            "account_id", "anchor_date", "anchor_balance",
            sa.literal_column("((created_at AT TIME ZONE 'UTC')::date)"),
        ],
        unique=True, schema="budget",
    )

    # ── Step 3: attach the audit trigger ────────────────────────────
    # The shared trigger function ``system.audit_trigger_func`` is
    # already in place from the rebuild migration
    # (``a5be2a99ea14``); attaching a row-level trigger to the new
    # table is all that is needed to start logging mutations.  The
    # DROP IF EXISTS pair makes the step idempotent against a re-run
    # of this migration.  Trigger name ``audit_<table>`` matches the
    # convention enumerated by the entrypoint trigger-count health
    # check.
    op.execute(
        "DROP TRIGGER IF EXISTS audit_loan_anchor_events "
        "ON budget.loan_anchor_events"
    )
    op.execute(
        "CREATE TRIGGER audit_loan_anchor_events "
        "AFTER INSERT OR UPDATE OR DELETE ON budget.loan_anchor_events "
        "FOR EACH ROW EXECUTE FUNCTION system.audit_trigger_func()"
    )

    # ── Step 4: backfill origination events ─────────────────────────
    op.execute(_BACKFILL_ORIGINATION_SQL)

    # ── Step 5: backfill conditional user_trueup events ─────────────
    bind = op.get_bind()
    _backfill_trueup_events(bind)


def downgrade():
    """Drop the trigger, table, and ref values.

    Reversible because the backfill is fully reproducible from
    immutable LoanParams data on the next upgrade.  The audit trail
    of the upgrade's INSERTs remains in ``system.audit_log`` -- the
    DELETE row produced by the table-drop CASCADE is captured by
    the trigger before the trigger itself is removed, so the
    forensic record survives the rollback.
    """
    # Inverse drop order.  PostgreSQL's DROP TABLE cascades the
    # row-level trigger as a dependent object so an explicit DROP
    # TRIGGER is not required; the other 30 audit triggers (on
    # surviving tables in AUDITED_TABLES) and the shared trigger
    # function ``system.audit_trigger_func`` stay attached untouched.
    op.drop_index(
        "uq_loan_anchor_events_acct_date_bal_day",
        table_name="loan_anchor_events", schema="budget",
    )
    op.drop_index(
        "idx_loan_anchor_events_account",
        table_name="loan_anchor_events", schema="budget",
    )
    op.drop_table("loan_anchor_events", schema="budget")
    op.drop_table("loan_anchor_sources", schema="ref")
