"""Plan step ``credit_card:CC-5-3``: the "Paid from" picker and the doors it posts to.

The surface half of the settle-with-tender door: the full-edit popover
renders a ``<select name="tender_account_id">`` over the accounts a payment
under the row may have moved through (rulings **R-CC39**, **R-CC34**: the
row's own first, then the owner's cash-flow set, drawn only when there is a
choice), preselected from what the row RECORDS (**R-CC42**); its Paid /
Received buttons carry the picker into ``mark_done`` by ``hx-include``, and
its Save carries it through the PATCH door.  What is graded here is what the
template EMITS -- a route test posts what a browser would -- and what each
door does with it: a settle on the card, a correction that re-points the
payment, the two refusals (a foreign account's 404, an outsider's 400), and
the surfaces that must stay byte-identical for an owner with no card.
"""

from __future__ import annotations

import re
from decimal import Decimal

from app import ref_cache
from app.enums import StatusEnum
from app.extensions import db
from app.models.transaction import Transaction
from app.services import entry_service, status_seam
from app.services.transaction_service import settle_transaction
from app.utils.dates import display_today
from tests._test_helpers import (
    create_account_of_type,
    generate_row_of,
    make_expense_template,
    typed,
)
from tests.test_routes._statement_forms import ReconcileFormReader

_PICKER = re.compile(
    r'<select name="tender_account_id" id="tender-(\d+)".*?</select>', re.S,
)
_OPTION = re.compile(r'<option value="(\d+)"( selected)?>([^<]*)</option>')


def _card(seed_user, name="Rewards Card"):
    return create_account_of_type(
        seed_user, db.session, "Credit Card", name,
        anchor_balance=Decimal("-500.00"),
    )


def _bill(seed_user, period, *, is_envelope=False, companion_visible=False):
    """A `$120.00` Hotel bill on checking, generated by its definition."""
    template = make_expense_template(
        db.session, seed_user, amount="120.00", name="Hotel",
        category_key="Rent", is_envelope=is_envelope,
        companion_visible=companion_visible,
    )
    row = generate_row_of(template, period)
    db.session.commit()
    return row


def _popover(auth_client, txn_id):
    response = auth_client.get(f"/transactions/{txn_id}/full-edit")
    assert response.status_code == 200
    return response.data.decode()


def _picker(html):
    """``[(account id, selected, label), ...]`` of the picker, or ``None``."""
    match = _PICKER.search(html)
    if match is None:
        return None
    return [
        (int(value), bool(selected), label)
        for value, selected, label in _OPTION.findall(match.group(0))
    ]


def _paid_button_includes(html, txn_id):
    """Whether the Paid / Received button carries the picker by ``hx-include``."""
    buttons = re.findall(
        r'<button[^>]*hx-post="[^"]*/mark-done"[^>]*>', html, re.S,
    )
    assert buttons, "the popover renders no mark-done button"
    return all(f'hx-include="#tender-{txn_id}"' in b for b in buttons)


def _form_fields(html):
    """What a browser submits for the popover's PATCH form, control by control."""
    start = html.index("<form hx-patch")
    form = html[start:html.index("</form>", start)]
    reader = ReconcileFormReader()
    reader.feed(form)
    payload = {}
    for name, value in reader.fields:
        payload[name] = value
    return payload


def _movement(txn_id):
    txn = db.session.get(Transaction, txn_id)
    db.session.expire(txn)
    movements = txn.covering_movements
    assert len(movements) == 1
    return movements[0]


class TestThePickerRendersOnlyWhereThereIsAChoice:
    """Rulings R-CC34 / R-CC39: the tuple, drawn only when it holds more than one."""

    def test_no_card_means_no_picker_and_no_hx_include(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        """An owner with no card: the popover carries no picker anywhere (byte-identical)."""
        with app.app_context():
            txn = _bill(seed_user, seed_periods_today[4])
            html = _popover(auth_client, txn.id)
            assert _picker(html) is None
            assert "tender_account_id" not in html
            assert "hx-include" not in html

    def test_a_projected_bill_offers_its_own_account_then_the_card(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        """Checking selected, the card second; the Paid button includes the picker."""
        with app.app_context():
            checking = seed_user["account"]
            card = _card(seed_user)
            txn = _bill(seed_user, seed_periods_today[4])
            html = _popover(auth_client, txn.id)
            assert _picker(html) == [
                (checking.id, True, checking.name),
                (card.id, False, card.name),
            ]
            assert _paid_button_includes(html, txn.id)
            assert "Paid from" in html

    def test_a_settled_card_bill_preselects_the_card(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        """What the row RECORDS is what the picker shows (R-CC42's one default)."""
        with app.app_context():
            checking = seed_user["account"]
            card = _card(seed_user)
            txn = _bill(seed_user, seed_periods_today[4])
            settle_transaction(txn, tender_account_id=card.id)
            db.session.commit()
            html = _popover(auth_client, txn.id)
            assert _picker(html) == [
                (checking.id, False, checking.name),
                (card.id, True, card.name),
            ]

    def test_a_reverted_card_bill_preselects_the_card_too(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        """The kept record's account, on a Projected row, so an untouched re-settle keeps it."""
        with app.app_context():
            card = _card(seed_user)
            txn = _bill(seed_user, seed_periods_today[4])
            settle_transaction(txn, tender_account_id=card.id)
            db.session.commit()
            auth_client.patch(f"/transactions/{txn.id}", data={
                "status_id": str(ref_cache.status_id(StatusEnum.PROJECTED)),
                "version_id": str(txn.version_id),
            })
            db.session.expire_all()
            txn = db.session.get(Transaction, txn.id)
            assert txn.status_id == ref_cache.status_id(StatusEnum.PROJECTED)
            html = _popover(auth_client, txn.id)
            selected = [acct for acct, chosen, _ in _picker(html) if chosen]
            assert selected == [card.id]

    def test_a_since_archived_tender_is_still_the_selected_option(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        """The recorded account is always an option, or the browser posts the first one.

        Found by the neutral review of this leaf: a bill paid from a card the
        owner has since archived; the active set no longer holds the card, so
        without this arm no option carried ``selected``, an untouched Save
        posted the row's own account as a CORRECTION (the payment re-pointed
        onto checking, both links released, silent 200) and the documented
        unlock path (Status = Projected) was refused for a tender nobody
        changed.  Four doors graded: the render, the untouched Save (an echo:
        no version bump, the movement where it was), the revert, and the
        Paid button on the reverted row (the picker's echo keeps the card).
        """
        with app.app_context():
            checking = seed_user["account"]
            card = _card(seed_user)
            txn = _bill(seed_user, seed_periods_today[4])
            settle_transaction(txn, tender_account_id=card.id)
            db.session.commit()
            card.is_active = False
            db.session.commit()

            html = _popover(auth_client, txn.id)
            assert _picker(html) == [
                (checking.id, False, checking.name),
                (card.id, True, card.name),
            ]

            version_before = txn.version_id
            payload = _form_fields(html)
            assert payload["tender_account_id"] == str(card.id)
            assert auth_client.patch(f"/transactions/{txn.id}", data=payload).status_code == 200
            db.session.expire_all()
            assert db.session.get(Transaction, txn.id).version_id == version_before
            assert _movement(txn.id).account_id == card.id

            payload = _form_fields(_popover(auth_client, txn.id))
            payload["status_id"] = str(ref_cache.status_id(StatusEnum.PROJECTED))
            assert auth_client.patch(f"/transactions/{txn.id}", data=payload).status_code == 200
            db.session.expire_all()
            assert db.session.get(Transaction, txn.id).status_id == ref_cache.status_id(
                StatusEnum.PROJECTED,
            )

            html = _popover(auth_client, txn.id)
            assert [a for a, chosen, _ in _picker(html) if chosen] == [card.id]
            assert _paid_button_includes(html, txn.id)
            response = auth_client.post(
                f"/transactions/{txn.id}/mark-done",
                data={"tender_account_id": _form_fields(html)["tender_account_id"]},
            )
            assert response.status_code == 200
            assert _movement(txn.id).account_id == card.id

    def test_an_envelope_holding_purchases_renders_no_picker(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        """The Actual box's own gate: a row settling from its purchases has no ONE payment."""
        with app.app_context():
            _card(seed_user)
            txn = _bill(seed_user, seed_periods_today[4], is_envelope=True)
            entry_service.create_entry(
                txn.id, seed_user["user"].id,
                entry_service.EntryDetails(
                    figure=typed(Decimal("40.00")), description="Deposit",
                    purchased_on=display_today(),
                ),
            )
            db.session.commit()
            html = _popover(auth_client, txn.id)
            assert _picker(html) is None
            assert not _paid_button_includes(html, txn.id)

    def test_a_cancelled_row_renders_no_picker(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        """A row that books no payment offers no account to book it on."""
        with app.app_context():
            _card(seed_user)
            txn = _bill(seed_user, seed_periods_today[4])
            response = auth_client.post(f"/transactions/{txn.id}/cancel")
            assert response.status_code == 200
            html = _popover(auth_client, txn.id)
            assert _picker(html) is None


class TestMarkDoneTakesTheTender:
    """The Paid button's door, posted as ``hx-include`` would."""

    def test_the_picker_settles_the_bill_on_the_card(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        with app.app_context():
            card = _card(seed_user)
            txn = _bill(seed_user, seed_periods_today[4])
            response = auth_client.post(
                f"/transactions/{txn.id}/mark-done",
                data={"tender_account_id": str(card.id)},
            )
            assert response.status_code == 200
            movement = _movement(txn.id)
            assert movement.account_id == card.id
            assert movement.amount == Decimal("120.00")

    def test_a_click_with_no_picker_settles_on_the_rows_account(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        """The cell's checkmark and the mobile card: nothing posted, the row's own account."""
        with app.app_context():
            _card(seed_user)
            txn = _bill(seed_user, seed_periods_today[4])
            response = auth_client.post(f"/transactions/{txn.id}/mark-done")
            assert response.status_code == 200
            assert _movement(txn.id).account_id == txn.account_id

    def test_a_foreign_account_is_a_404_fragment(
        self, app, auth_client, seed_user, seed_periods_today, second_user,
    ):
        """The security response rule, as the designed fragment; nothing settled."""
        with app.app_context():
            theirs = create_account_of_type(
                second_user, db.session, "Credit Card", "Their Card",
                anchor_balance=Decimal("-10.00"),
            )
            db.session.commit()
            txn = _bill(seed_user, seed_periods_today[4])
            response = auth_client.post(
                f"/transactions/{txn.id}/mark-done",
                data={"tender_account_id": str(theirs.id)},
            )
            assert response.status_code == 404
            assert b"Account not found." in response.data
            db.session.expire_all()
            fresh = db.session.get(Transaction, txn.id)
            assert fresh.status_id == ref_cache.status_id(StatusEnum.PROJECTED)
            assert fresh.covering_movements == []

    def test_an_account_outside_the_set_is_a_400_fragment(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        with app.app_context():
            _card(seed_user)
            savings = create_account_of_type(
                seed_user, db.session, "Savings", "Rainy Day",
            )
            db.session.commit()
            txn = _bill(seed_user, seed_periods_today[4])
            response = auth_client.post(
                f"/transactions/{txn.id}/mark-done",
                data={"tender_account_id": str(savings.id)},
            )
            assert response.status_code == 400
            assert b"not an account a payment can be paid from" in response.data
            db.session.expire_all()
            assert db.session.get(Transaction, txn.id).covering_movements == []

    def test_a_companion_settles_the_owners_bill_on_the_owners_card(
        self, app, seed_user, seed_periods_today, companion_client,
    ):
        """Ruling R-CC11: the gate is the ROW's owner's set, so the owner's card is admitted."""
        with app.app_context():
            card = _card(seed_user)
            txn = _bill(
                seed_user, seed_periods_today[4], companion_visible=True,
            )
            response = companion_client.post(
                f"/transactions/{txn.id}/mark-done",
                data={
                    "tender_account_id": str(card.id),
                    "render": "mobile_card", "card_prefix": "tp",
                    "can_edit": "0",
                },
            )
            assert response.status_code == 200
            movement = _movement(txn.id)
            assert movement.account_id == card.id
            assert movement.owner_id == seed_user["user"].id


class TestThePatchDoorTakesTheTender:
    """The popover's Save, posting exactly what the form renders."""

    def test_settling_from_the_status_dropdown_books_on_the_picked_card(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        """Status = Paid beside 'Paid from' = the card: one Save, the movement on the card."""
        with app.app_context():
            card = _card(seed_user)
            txn = _bill(seed_user, seed_periods_today[4])
            payload = _form_fields(_popover(auth_client, txn.id))
            assert payload["tender_account_id"] == str(txn.account_id)
            payload["status_id"] = str(ref_cache.status_id(StatusEnum.DONE))
            payload["tender_account_id"] = str(card.id)
            response = auth_client.patch(f"/transactions/{txn.id}", data=payload)
            assert response.status_code == 200
            assert _movement(txn.id).account_id == card.id

    def test_an_untouched_save_on_a_settled_card_bill_writes_nothing(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        """The echo: the form re-posts the card it showed; no re-point, no version bump."""
        with app.app_context():
            card = _card(seed_user)
            txn = _bill(seed_user, seed_periods_today[4])
            settle_transaction(txn, tender_account_id=card.id)
            db.session.commit()
            version_before = txn.version_id
            payload = _form_fields(_popover(auth_client, txn.id))
            assert payload["tender_account_id"] == str(card.id)
            response = auth_client.patch(f"/transactions/{txn.id}", data=payload)
            assert response.status_code == 200
            db.session.expire_all()
            fresh = db.session.get(Transaction, txn.id)
            assert fresh.version_id == version_before
            assert _movement(txn.id).account_id == card.id

    def test_changing_the_picker_on_a_settled_bill_re_points_the_payment(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        """A checking-settled bill corrected to the card, without reverting."""
        with app.app_context():
            checking = seed_user["account"]
            card = _card(seed_user)
            txn = _bill(seed_user, seed_periods_today[4])
            settle_transaction(txn)
            db.session.commit()
            assert _movement(txn.id).account_id == checking.id
            payload = _form_fields(_popover(auth_client, txn.id))
            payload["tender_account_id"] = str(card.id)
            response = auth_client.patch(f"/transactions/{txn.id}", data=payload)
            assert response.status_code == 200
            db.session.expire_all()
            fresh = db.session.get(Transaction, txn.id)
            assert fresh.status_id == ref_cache.status_id(StatusEnum.DONE)
            assert _movement(txn.id).account_id == card.id
            assert status_seam.tender_account_id_of(fresh) == card.id

    def test_a_revert_with_the_picker_untouched_proceeds(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        """The documented unlock path: Status = Projected, the picker echoing the card."""
        with app.app_context():
            card = _card(seed_user)
            txn = _bill(seed_user, seed_periods_today[4])
            settle_transaction(txn, tender_account_id=card.id)
            db.session.commit()
            payload = _form_fields(_popover(auth_client, txn.id))
            payload["status_id"] = str(ref_cache.status_id(StatusEnum.PROJECTED))
            response = auth_client.patch(f"/transactions/{txn.id}", data=payload)
            assert response.status_code == 200
            db.session.expire_all()
            fresh = db.session.get(Transaction, txn.id)
            assert fresh.status_id == ref_cache.status_id(StatusEnum.PROJECTED)
            kept = _movement(txn.id)
            assert kept.settled_on is None
            assert kept.account_id == card.id

    def test_a_changed_picker_beside_a_revert_is_refused(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        with app.app_context():
            checking = seed_user["account"]
            card = _card(seed_user)
            txn = _bill(seed_user, seed_periods_today[4])
            settle_transaction(txn, tender_account_id=card.id)
            db.session.commit()
            payload = _form_fields(_popover(auth_client, txn.id))
            payload["status_id"] = str(ref_cache.status_id(StatusEnum.PROJECTED))
            payload["tender_account_id"] = str(checking.id)
            response = auth_client.patch(f"/transactions/{txn.id}", data=payload)
            assert response.status_code == 400
            assert b"is not settling, so a &#39;Paid from&#39; account" in response.data \
                or b"is not settling, so a 'Paid from' account" in response.data
            db.session.expire_all()
            fresh = db.session.get(Transaction, txn.id)
            assert fresh.status_id == ref_cache.status_id(StatusEnum.DONE)
            assert _movement(txn.id).account_id == card.id

    def test_a_foreign_account_through_the_patch_door_is_a_404(
        self, app, auth_client, seed_user, seed_periods_today, second_user,
    ):
        with app.app_context():
            theirs = create_account_of_type(
                second_user, db.session, "Credit Card", "Their Card",
                anchor_balance=Decimal("-10.00"),
            )
            db.session.commit()
            _card(seed_user)
            txn = _bill(seed_user, seed_periods_today[4])
            settle_transaction(txn)
            db.session.commit()
            payload = _form_fields(_popover(auth_client, txn.id))
            payload["tender_account_id"] = str(theirs.id)
            response = auth_client.patch(f"/transactions/{txn.id}", data=payload)
            assert response.status_code == 404
            assert b"Account not found." in response.data
            db.session.expire_all()
            assert _movement(txn.id).account_id == txn.account_id

    def test_a_tender_on_an_envelope_with_purchases_is_refused_by_the_route(
        self, app, auth_client, seed_user, seed_periods_today,
    ):
        """The crafted-request backstop: the popover renders no picker, the door refuses one."""
        with app.app_context():
            card = _card(seed_user)
            txn = _bill(seed_user, seed_periods_today[4], is_envelope=True)
            entry_service.create_entry(
                txn.id, seed_user["user"].id,
                entry_service.EntryDetails(
                    figure=typed(Decimal("40.00")), description="Deposit",
                    purchased_on=display_today(),
                ),
            )
            db.session.commit()
            payload = _form_fields(_popover(auth_client, txn.id))
            assert "tender_account_id" not in payload
            payload["tender_account_id"] = str(card.id)
            response = auth_client.patch(f"/transactions/{txn.id}", data=payload)
            assert response.status_code == 400
            assert b"Pick the account on the purchase instead" in response.data
