#!/usr/bin/env bash
# PreToolUse (Write|Edit|MultiEdit): pause when a migration file is hand-edited.
# Migrations should be generated by 'flask db migrate', not written by hand.
# Reads the edited path from the stdin JSON payload (see _hooklib.sh).
#
# Mechanism (polyglot audit 2026-06-12, HOOK/SH-05): the original hook echoed a
# warning to stdout with exit 0, but PreToolUse stdout on exit 0 is
# transcript-only -- neither the model nor the developer saw it, so "the
# developer decides" never actually happened. The documented channel that
# matches the intent is the PreToolUse JSON output with permissionDecision
# "ask": the harness pauses the tool call and puts the decision in front of the
# developer. Some hand-edits (CHECK constraints, data backfills, working
# downgrades) are legitimate, so "ask" -- not "deny" -- is correct.

set -uo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/_hooklib.sh"

FILE="$(hook_target_relpath)" || exit 2
[[ "$FILE" == migrations/versions/*.py ]] || exit 0

REASON="Hand-editing migration file $FILE. Migrations should be generated with \
'flask db migrate -m \"description\"'. Legitimate hand-edits: CHECK constraints, \
data backfills (CLAUDE.md: backfills belong in migrations), working downgrades. \
Approve if intentional; deny to abort and regenerate."

python3 -c '
import json
import sys

print(json.dumps({
    "hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": "ask",
        "permissionDecisionReason": sys.argv[1],
    }
}))
' "$REASON"
exit 0
