#!/usr/bin/env bash
# PreToolUse (Write|Edit|MultiEdit): warn when a migration file is hand-edited.
# Migrations should be generated by 'flask db migrate', not written by hand.
# Reads the edited path from the stdin JSON payload (see _hooklib.sh). Exit 0
# allows the edit with a warning (some hand-edits -- CHECK constraints, data
# backfill -- are legitimate); the developer decides.

set -uo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/_hooklib.sh"

FILE="$(hook_target_relpath)"
[[ "$FILE" == migrations/versions/*.py ]] || exit 0

echo "=== MIGRATION FILE EDIT ==="
echo "You are editing a migration file directly ($FILE)."
echo "Migrations should be generated with 'flask db migrate -m \"description\"'."
echo "If this hand-edit is intentional (CHECK constraints, data backfill, a"
echo "working downgrade), proceed. Otherwise abort and regenerate."
exit 0
