#!/usr/bin/env bash
# PreToolUse: Warn when directly editing migration files.
# Migrations should be generated by 'flask db migrate', not hand-edited.
# Exit 0 = allow with warning. Exit 1 = block.

FILE="$1"

[[ "$FILE" != migrations/versions/*.py ]] && exit 0

echo "=== MIGRATION FILE EDIT ==="
echo "You are editing a migration file directly."
echo "Migrations should be generated with 'flask db migrate -m \"description\"'."
echo "If this hand-edit is intentional (e.g., adding CHECK constraints or"
echo "data backfill logic), proceed. Otherwise, abort and regenerate."
# Allow with warning (exit 0). Change to exit 1 to block entirely.
exit 0
